// PROVISORISCH generiert (Schritt 3, Migration) aus toc/data + audit + tagMappings.
// lf, aufgabenfamilie und ap1_relevanz sind Hypothesen bis zum fachlichen Audit.
// fachlich wurde 1:1 uebernommen - nichts wurde hochgestuft.
import type { LessonMeta } from './schema'

export const lf1: LessonMeta[] = [
  {
    slug: "afa-abschreibung",
    titel: "AfA – lineare Abschreibung",
    lf: 1,
    aufgabenfamilie: ["rechnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "aida-formel",
    titel: "AIDA-Formel & Werbewirkung",
    lf: 1,
    aufgabenfamilie: ["begruenden"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "angebotsvergleich",
    titel: "Angebotsvergleich (quantitativ & qualitativ)",
    lf: 1,
    aufgabenfamilie: ["rechnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "arbeitnehmerrechte",
    titel: "Arbeitnehmerrechte & Kündigungsschutz",
    lf: 1,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "mittel",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "aufbauorganisation",
    titel: "Aufbauorganisation, Vollmachten & Prokura",
    lf: 1,
    aufgabenfamilie: ["anwenden"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "bbig-ausbildungsvertrag",
    titel: "BBiG & Ausbildungsvertrag",
    lf: 1,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "mittel",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "break-even",
    titel: "Break-Even-Analyse",
    lf: 1,
    aufgabenfamilie: ["rechnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "crm-erp-dms",
    titel: "CRM, ERP, DMS & CMS – Unternehmenssoftware",
    lf: 1,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "eigenfremdfinanzierung",
    titel: "Eigen- & Fremdfinanzierung",
    lf: 1,
    aufgabenfamilie: ["rechnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "energiekosten",
    titel: "Energiekosten, Wirkungsgrad & Amortisation",
    lf: 1,
    aufgabenfamilie: ["rechnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "gewaehrleistung",
    titel: "Gewährleistung & Garantie",
    lf: 1,
    aufgabenfamilie: ["begruenden"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: ["bgb-433-kaufvertrag", "bgb-434-sachmangel", "bgb-437-maengelrechte", "bgb-438-verjaehrung-maengel", "bgb-443-garantie", "hgb-377-maengelruege"], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "gewinnermittlung",
    titel: "Gewinnermittlung & Deckungsbeitrag",
    lf: 1,
    aufgabenfamilie: ["rechnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "handelskalkulation",
    titel: "Handelskalkulation (Vorwärts/Rückwärts)",
    lf: 1,
    aufgabenfamilie: ["rechnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "kauf-leasing-miete",
    titel: "Kauf, Leasing & Miete im Vergleich",
    lf: 1,
    aufgabenfamilie: ["begruenden"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "kaufmaennische-rechenaufgaben",
    titel: "Kaufmännische Rechenaufgaben (Kosten, Leasing, Skonto)",
    lf: 1,
    aufgabenfamilie: ["rechnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "maengelruege",
    titel: "Mängelrüge im Handelskauf",
    lf: 1,
    aufgabenfamilie: ["begruenden"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "make-or-buy",
    titel: "Make-or-Buy-Entscheidung",
    lf: 1,
    aufgabenfamilie: ["begruenden"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "marktformen",
    titel: "Marktformen (Monopol, Polypol, Oligopol)",
    lf: 1,
    aufgabenfamilie: ["begruenden"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "nutzwertanalyse",
    titel: "Nutzwertanalyse",
    lf: 1,
    aufgabenfamilie: ["rechnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "organisationsformen-leitbild-nachhaltigkeit-esg",
    titel: "Organisationsformen, Leitbild, Nachhaltigkeit & ESG",
    lf: 1,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "rechnung-zahlungsziel-aufbewahrungsfristen",
    titel: "Rechnung, Zahlungsziel & Aufbewahrungsfristen",
    lf: 1,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "variable-fixe-kosten",
    titel: "Variable & fixe Kosten",
    lf: 1,
    aufgabenfamilie: ["rechnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "vertragsarten",
    titel: "Vertragsarten: Kaufvertrag, Dienstvertrag & Werkvertrag",
    lf: 1,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "vertragsstoerungen",
    titel: "Vertragsstörungen (Verzug, Mängel, Unmöglichkeit)",
    lf: 1,
    aufgabenfamilie: ["begruenden"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "zweiseitiger-handelskauf",
    titel: "Zweiseitiger Handelskauf",
    lf: 1,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
]
