// PROVISORISCH generiert (Schritt 3, Migration) aus toc/data + audit + tagMappings.
// lf, aufgabenfamilie und ap1_relevanz sind Hypothesen bis zum fachlichen Audit.
// fachlich wurde 1:1 uebernommen - nichts wurde hochgestuft.
import type { LessonMeta } from './schema'

export const lf2: LessonMeta[] = [
  {
    slug: "bit-byte",
    titel: "Bit & Byte - die kleinsten Einheiten",
    lf: 2,
    aufgabenfamilie: ["rechnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "teilgeprueft",
    quellen: { q1_scope: ["kmk-rahmenlehrplan", "fiausbv", "bibb-fachinformatiker"], q2_fachquelle: ["nist-ir-8354-digital-investigation", "iec-80000-13", "nist-binary-prefixes", "bipm-si-prefixes", "ansi-x3-4-ascii", "unicode-utf-8"], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "cpu-ram-speicher",
    titel: "CPU, RAM und Massenspeicher",
    lf: 2,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: ["kmk-rahmenlehrplan", "fiausbv", "bibb-fachinformatiker"], q2_fachquelle: ["ibm-cpu-instruction-cycle", "intel-cpu-clock-speed", "microsoft-ssd-hdd-storage", "nvmexpress-faq", "crucial-ddr-generations"], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "dateisysteme",
    titel: "Dateisysteme (FAT32, NTFS, ext4, APFS)",
    lf: 2,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "datenrate-berechnung",
    titel: "Datenrate & Downloadzeit berechnen",
    lf: 2,
    aufgabenfamilie: ["rechnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "teilgeprueft",
    quellen: { q1_scope: ["kmk-rahmenlehrplan", "fiausbv", "bibb-fachinformatiker"], q2_fachquelle: ["bipm-si-prefixes", "nist-binary-prefixes", "iec-80000-13", "rfc-9293", "rfc-9110", "ieee-80211-working-group", "bsi-wlan-lan-grundlagen"], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "hardware-schnittstellen",
    titel: "Hardware, Schnittstellen & Peripherie auswählen",
    lf: 2,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "homeoffice-ergonomie",
    titel: "Ergonomie, Barrierefreiheit & Telearbeit",
    lf: 2,
    aufgabenfamilie: ["anwenden"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "teilgeprueft",
    quellen: { q1_scope: ["kmk-rahmenlehrplan", "fiausbv", "bibb-fachinformatiker"], q2_fachquelle: ["arbstaettv", "arbschg", "dguv-215-410", "baua-mobile-arbeit-homeoffice", "w3c-wcag", "bitv-2-0"], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "linux-chmod",
    titel: "Linux-Dateiberechtigungen (chmod, rwx)",
    lf: 2,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: ["posix-chmod", "gnu-coreutils-chmod", "linux-man-pages-chmod2"], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "prefixe",
    titel: "SI- und Binärpräfixe (KB vs. KiB)",
    lf: 2,
    aufgabenfamilie: ["rechnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "teilgeprueft",
    quellen: { q1_scope: ["kmk-rahmenlehrplan", "fiausbv", "bibb-fachinformatiker"], q2_fachquelle: ["iec-80000-13", "nist-binary-prefixes", "bipm-si-prefixes", "jedec-100b-01", "ibm-storage-units", "gnu-coreutils-df"], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "prozess-thread",
    titel: "Prozesse, Threads & Tasks",
    lf: 2,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "raid-systeme",
    titel: "RAID-Systeme (0, 1, 5, 6, 10)",
    lf: 2,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "scan-bilddaten",
    titel: "Scan- & Bilddaten rechnen (DPI, Farbtiefe)",
    lf: 2,
    aufgabenfamilie: ["rechnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "usv-systeme",
    titel: "USV-Systeme",
    lf: 2,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "virtualisierung",
    titel: "Virtualisierung & Hypervisor",
    lf: 2,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "von-neumann",
    titel: "Von-Neumann-Architektur",
    lf: 2,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: ["smithsonian-edvac-first-draft", "computer-history-museum-edvac", "ibm-cpu-instruction-cycle", "cornell-cpu-stages"], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "zahlensysteme",
    titel: "Zahlensysteme (Dual, Hex, Dezimal)",
    lf: 2,
    aufgabenfamilie: ["rechnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "teilgeprueft",
    quellen: { q1_scope: ["kmk-rahmenlehrplan", "fiausbv", "bibb-fachinformatiker"], q2_fachquelle: ["nist-ir-8354-digital-investigation", "iec-80000-13", "posix-chmod", "rfc-9542", "w3c-css-color-4", "rfc-4632", "ieee-754-2019"], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "zentral-dezentral",
    titel: "Zentrale vs. dezentrale IT-Systeme",
    lf: 2,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
]
