// PROVISORISCH generiert (Schritt 3, Migration) aus toc/data + audit + tagMappings.
// lf, aufgabenfamilie und ap1_relevanz sind Hypothesen bis zum fachlichen Audit.
// fachlich wurde 1:1 uebernommen - nichts wurde hochgestuft.
import type { LessonMeta } from './schema'

export const lf3: LessonMeta[] = [
  {
    slug: "datenvolumen-berechnung",
    titel: "Datenmengen, Scan & Übertragung — komplett rechnen",
    lf: 3,
    aufgabenfamilie: ["rechnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "teilgeprueft",
    quellen: { q1_scope: ["kmk-rahmenlehrplan", "fiausbv", "bibb-fachinformatiker"], q2_fachquelle: ["bipm-si-prefixes", "nist-binary-prefixes", "iec-80000-13", "nist-ir-8354-digital-investigation", "rfc-791", "rfc-9293", "rfc-9110", "iso-iec-10918-1-jpeg", "w3c-png-3", "itu-t-h264", "itu-t-g1010"], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "firewall-dmz",
    titel: "Firewall und DMZ",
    lf: 3,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "teilgeprueft",
    quellen: { q1_scope: ["kmk-rahmenlehrplan", "fiausbv", "bibb-fachinformatiker"], q2_fachquelle: ["bsi-net-3-2-firewall", "bsi-net-1-1-netzarchitektur", "bsi-firewall", "bsi-router-wlan-vpn", "rfc-1918"], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "imap-pop3-smtp",
    titel: "E-Mail-Protokolle (IMAP, POP3, SMTP)",
    lf: 3,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "ipv4-subnetting",
    titel: "IPv4 & Subnetting",
    lf: 3,
    aufgabenfamilie: ["rechnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "teilgeprueft",
    quellen: { q1_scope: [], q2_fachquelle: ["rfc-791", "rfc-4632", "rfc-1918", "rfc-3021", "iana-ipv4-special-registry"], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "ipv6-grundlagen",
    titel: "IPv6 – Aufbau & Adressierung",
    lf: 3,
    aufgabenfamilie: ["rechnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "teilgeprueft",
    quellen: { q1_scope: ["kmk-rahmenlehrplan", "fiausbv", "bibb-fachinformatiker"], q2_fachquelle: ["rfc-8200", "rfc-4291", "rfc-5952", "rfc-4862", "rfc-8981", "rfc-7217", "rfc-4193", "rfc-3849"], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "netzwerkkonfiguration",
    titel: "Netzwerkkonfiguration, DHCP, DNS & Diagnose",
    lf: 3,
    aufgabenfamilie: ["diagnostizieren"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "teilgeprueft",
    quellen: { q1_scope: ["kmk-rahmenlehrplan", "fiausbv", "bibb-fachinformatiker"], q2_fachquelle: ["rfc-2131", "rfc-1034", "rfc-1035", "rfc-826", "rfc-3927", "rfc-791", "iana-ipv4-special-registry"], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "osi-modell",
    titel: "OSI-Modell – sieben Schichten",
    lf: 3,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "teilgeprueft",
    quellen: { q1_scope: ["kmk-rahmenlehrplan", "fiausbv", "bibb-fachinformatiker"], q2_fachquelle: ["itu-x200-osi-basic-model", "iso-7498-1", "rfc-1122", "rfc-791", "rfc-826", "rfc-9293", "rfc-768", "rfc-9110", "rfc-8446"], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "port-forwarding",
    titel: "Port Forwarding und NAT",
    lf: 3,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "teilgeprueft",
    quellen: { q1_scope: ["kmk-rahmenlehrplan", "fiausbv", "bibb-fachinformatiker"], q2_fachquelle: ["rfc-1918", "rfc-2663", "rfc-3022", "rfc-5737", "rfc-6333", "rfc-6888", "bsi-router-wlan-vpn", "bsi-firewall", "bsi-net-1-1-netzarchitektur", "bsi-vpn"], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "tcp-udp",
    titel: "TCP vs. UDP",
    lf: 3,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "teilgeprueft",
    quellen: { q1_scope: ["kmk-rahmenlehrplan", "fiausbv", "bibb-fachinformatiker"], q2_fachquelle: ["rfc-9293", "rfc-768", "rfc-6335", "iana-service-port-registry", "rfc-1035", "rfc-7766", "rfc-2131", "rfc-9110", "rfc-8446"], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "wlan-standards",
    titel: "WLAN-Standards und WLAN-Sicherheit",
    lf: 3,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "teilgeprueft",
    quellen: { q1_scope: ["kmk-rahmenlehrplan", "fiausbv", "bibb-fachinformatiker"], q2_fachquelle: ["ieee-80211-working-group", "ieee-sa-p802-11", "ieee-80211ax-2021", "ieee-80211be-2024", "wifi-alliance-security", "bsi-wlan-lan-grundlagen", "bsi-wlan-sicherheitstipps", "microsoft-windows-wifi"], q3_pruefungsrealitaet: [] },
  },
]
