// PROVISORISCH generiert (Schritt 3, Migration) aus toc/data + audit + tagMappings.
// lf, aufgabenfamilie und ap1_relevanz sind Hypothesen bis zum fachlichen Audit.
// fachlich wurde 1:1 uebernommen - nichts wurde hochgestuft.
import type { LessonMeta } from './schema'

export const lf4: LessonMeta[] = [
  {
    slug: "backup-strategien",
    titel: "Backup-Strategien (Voll, Inkrementell, Differenziell)",
    lf: 4,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "dsgvo-basics",
    titel: "DSGVO – die sieben Grundsätze",
    lf: 4,
    aufgabenfamilie: ["begruenden"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "endpoint-security",
    titel: "Endpoint-Security & Schutzmaßnahmen",
    lf: 4,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "malware-grundlagen",
    titel: "Malware — Viren, Würmer, Trojaner, Ransomware",
    lf: 4,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "mtbf-mttf",
    titel: "MTBF & MTTF – Ausfallwahrscheinlichkeit",
    lf: 4,
    aufgabenfamilie: ["rechnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "passwoerter-hashing",
    titel: "Passwörter & Hashing (Salt, Pepper)",
    lf: 4,
    aufgabenfamilie: ["begruenden"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "pki-zertifikate",
    titel: "PKI, CA & Zertifikate",
    lf: 4,
    aufgabenfamilie: ["begruenden"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: ["bibb-fachinformatiker"], q2_fachquelle: ["rfc-5280", "rfc-6960", "rfc-8446", "bsi-kryptografie", "bsi-tr-02102-1"], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "schutzziele",
    titel: "Schutzziele, Schutzbedarf, ISMS & BSI-Grundschutz",
    lf: 4,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "ssh-telnet",
    titel: "SSH vs. Telnet",
    lf: 4,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "verschluesselung-hash-vpn",
    titel: "Verschlüsselung, Hashing, Zertifikate, Signatur & VPN",
    lf: 4,
    aufgabenfamilie: ["begruenden"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "verschluesselung-sicherheit",
    titel: "Verschlüsselung & IT-Sicherheit",
    lf: 4,
    aufgabenfamilie: ["begruenden"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
]
