// PROVISORISCH generiert (Schritt 3, Migration) aus toc/data + audit + tagMappings.
// lf, aufgabenfamilie und ap1_relevanz sind Hypothesen bis zum fachlichen Audit.
// fachlich wurde 1:1 uebernommen - nichts wurde hochgestuft.
import type { LessonMeta } from './schema'

export const lf5: LessonMeta[] = [
  {
    slug: "audio-kompression",
    titel: "Audio, MP3 & Datenkompression",
    lf: 5,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "cloud-konzepte",
    titel: "Cloud-Konzepte (IaaS, PaaS, SaaS)",
    lf: 5,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "er-grundlagen",
    titel: "Was ist eine Datenbank? & ER-Modell",
    lf: 5,
    aufgabenfamilie: ["zeichnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "git-versionsverwaltung",
    titel: "Git & Versionsverwaltung",
    lf: 5,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "mittel",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "ki-grundlagen",
    titel: "KI-Grundlagen (ML, neuronale Netze)",
    lf: 5,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "libraries-frameworks",
    titel: "Libraries vs. Frameworks",
    lf: 5,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "mittel",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "lizenzmodelle",
    titel: "Lizenzmodelle (Open Source, proprietär, SaaS)",
    lf: 5,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "mockup-wireframe",
    titel: "Mockup & Wireframe",
    lf: 5,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "normalisierung",
    titel: "Normalisierung (1NF, 2NF, 3NF)",
    lf: 5,
    aufgabenfamilie: ["zeichnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "oop-basics",
    titel: "OOP-Grundlagen (Klassen, Objekte, Vererbung)",
    lf: 5,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "mittel",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "programmierparadigmen",
    titel: "Programmierparadigmen (OOP, prozedural, funktional)",
    lf: 5,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "pseudocode-einstieg",
    titel: "Pseudocode, Algorithmen & Kontrollstrukturen",
    lf: 5,
    aufgabenfamilie: ["anwenden"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: ["kmk-rahmenlehrplan", "fiausbv", "bibb-fachinformatiker"], q2_fachquelle: ["openstax-boolean-operations"], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "responsive-webdesign",
    titel: "Responsive Webdesign",
    lf: 5,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "sql-grundlagen",
    titel: "SQL-Grundlagen (SELECT, JOIN, DML)",
    lf: 5,
    aufgabenfamilie: ["anwenden"],
    ap1_relevanz: "mittel",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "stamm-bewegungsdaten",
    titel: "Stamm- und Bewegungsdaten",
    lf: 5,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: ["kmk-rahmenlehrplan", "fiausbv", "bibb-fachinformatiker"], q2_fachquelle: ["sap-mdm-definition", "microsoft-enterprise-data-types", "ibm-master-data-management", "dsgvo"], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "teststrategien",
    titel: "Teststrategien (White-Box, Black-Box, Unit-Tests)",
    lf: 5,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "uml-aktivitaet",
    titel: "UML-Aktivitätsdiagramm",
    lf: 5,
    aufgabenfamilie: ["zeichnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "uml-beziehungen",
    titel: "UML-Beziehungen (Komposition, Aggregation)",
    lf: 5,
    aufgabenfamilie: ["zeichnen"],
    ap1_relevanz: "mittel",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "use-case-diagramm",
    titel: "UML-Use-Case-Diagramm",
    lf: 5,
    aufgabenfamilie: ["zeichnen"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "website-statisch-dynamisch",
    titel: "Statische vs. dynamische Webseiten",
    lf: 5,
    aufgabenfamilie: ["anwenden"],
    ap1_relevanz: "hoch",
    jahr: [1],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
]
