// PROVISORISCH generiert (Schritt 3, Migration) aus toc/data + audit + tagMappings.
// lf, aufgabenfamilie und ap1_relevanz sind Hypothesen bis zum fachlichen Audit.
// fachlich wurde 1:1 uebernommen - nichts wurde hochgestuft.
import type { LessonMeta } from './schema'

export const lf6: LessonMeta[] = [
  {
    slug: "bedarfsanalyse-feedback",
    titel: "Bedarfsanalyse, Kommunikation & Feedback",
    lf: 6,
    aufgabenfamilie: ["diagnostizieren"],
    ap1_relevanz: "hoch",
    jahr: [2],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "bpmn",
    titel: "BPMN – Prozesse modellieren",
    lf: 6,
    aufgabenfamilie: ["zeichnen"],
    ap1_relevanz: "hoch",
    jahr: [2],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "efqm-modell",
    titel: "EFQM-Modell",
    lf: 6,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "mittel",
    jahr: [2],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "fehlermanagement-stoerungsannahme",
    titel: "Fehlermanagement & Störungsannahme",
    lf: 6,
    aufgabenfamilie: ["diagnostizieren"],
    ap1_relevanz: "hoch",
    jahr: [2],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "gantt-diagramm",
    titel: "Gantt-Diagramm — Balkenplan",
    lf: 6,
    aufgabenfamilie: ["zeichnen"],
    ap1_relevanz: "hoch",
    jahr: [2],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "iso-25010",
    titel: "ISO 25010 – Softwarequalität",
    lf: 6,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [2],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "iso-9000",
    titel: "ISO 9000–9004",
    lf: 6,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [2],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "lastenheft-pflichtenheft",
    titel: "Lastenheft & Pflichtenheft",
    lf: 6,
    aufgabenfamilie: ["anwenden"],
    ap1_relevanz: "hoch",
    jahr: [2],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "machbarkeitsanalyse",
    titel: "Machbarkeitsanalyse",
    lf: 6,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [2],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "mitarbeitermotivation-teamphasen-change",
    titel: "Mitarbeitermotivation, Teamphasen und Change",
    lf: 6,
    aufgabenfamilie: ["begruenden"],
    ap1_relevanz: "hoch",
    jahr: [2],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "netzplan",
    titel: "Netzplantechnik (FAZ/FEZ/SAZ/SEZ)",
    lf: 6,
    aufgabenfamilie: ["zeichnen"],
    ap1_relevanz: "hoch",
    jahr: [2],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "pdca-zyklus",
    titel: "PDCA-Zyklus",
    lf: 6,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "hoch",
    jahr: [2],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "projektubergabe",
    titel: "Projektübergabe & Abnahme",
    lf: 6,
    aufgabenfamilie: ["zuordnen"],
    ap1_relevanz: "mittel",
    jahr: [2],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "schulung-einweisung-key-user",
    titel: "Schulung, Einweisung, Key User & Multiplikatoren",
    lf: 6,
    aufgabenfamilie: ["anwenden"],
    ap1_relevanz: "hoch",
    jahr: [2],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "schulz-von-thun",
    titel: "4-Seiten-Modell nach Schulz von Thun",
    lf: 6,
    aufgabenfamilie: ["begruenden"],
    ap1_relevanz: "hoch",
    jahr: [2],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "scrum",
    titel: "Scrum – Accountabilities, Events, Artefakte",
    lf: 6,
    aufgabenfamilie: ["anwenden"],
    ap1_relevanz: "hoch",
    jahr: [2],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "serviceanfragen-support-level",
    titel: "Serviceanfragen, Ticketsystem & Support-Level",
    lf: 6,
    aufgabenfamilie: ["diagnostizieren"],
    ap1_relevanz: "hoch",
    jahr: [2],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
  {
    slug: "vorgehensmodelle",
    titel: "Vorgehensmodelle (Wasserfall, V-Modell, Agil)",
    lf: 6,
    aufgabenfamilie: ["anwenden"],
    ap1_relevanz: "hoch",
    jahr: [2],
    erklaert_fakten: true,
    fachlich: "ungeprueft",
    quellen: { q1_scope: [], q2_fachquelle: [], q3_pruefungsrealitaet: [] },
  },
]
