import type { SourceEntry } from "../../lib/quellen/types"

export const sourceBank: SourceEntry[] = [
  {
    id: 'bibb-fachinformatiker',
    label: 'BIBB - Fachinformatiker/Fachinformatikerin, Umsetzungshilfe',
    href: 'https://www.bibb.de/dienst/publikationen/de/16661',
    detail: 'Ausbildungsordnung, Ausbildungsrahmenplan, Lernfelder und Prüfungsstruktur der modernisierten IT-Berufe.',
    tags: ['ordnung', 'ausbildung', 'ap1', 'ap2', 'projekt', 'wirtschaft', 'sicherheit'],
  },
  {
    id: 'fiausbv',
    label: 'Fachinformatikerausbildungsverordnung (FIAusbV)',
    href: 'https://www.gesetze-im-internet.de/fiausbv/BJNR025000020.html',
    detail: 'Amtliche Rechtsgrundlage mit Ausbildungsrahmenplan und Anforderungen an die Abschlusspruefung.',
    tags: ['ordnung', 'ausbildung', 'recht', 'ap1', 'ap2'],
  },
  {
    id: 'kmk-rahmenlehrplan',
    label: 'KMK - Rahmenlehrplan Fachinformatiker/Fachinformatikerin',
    href: 'https://www.kmk.org/fileadmin/Dateien/pdf/Bildung/BeruflicheBildung/rlp/Fachinformatiker_19-12-13_EL.pdf',
    detail: 'Berufsschulische Lernfelder für die Fachinformatiker-Ausbildung.',
    tags: ['ordnung', 'ausbildung', 'lernfelder', 'ap1', 'ap2'],
  },
  {
    id: 'hgb-rechtsformen',
    label: 'Handelsgesetzbuch - Kaufmann, OHG und KG',
    href: 'https://www.gesetze-im-internet.de/hgb/',
    detail: 'Amtliche Grundlage für Kaufmannsbegriff, offene Handelsgesellschaft und Kommanditgesellschaft.',
    tags: ['wirtschaft', 'recht', 'organisation', 'rechtsform', 'unternehmensform', 'einzelunternehmen', 'ohg', 'kg'],
  },
  {
    id: 'gmbhg-13-gmbh',
    label: 'GmbHG Paragraf 13 - Juristische Person; Handelsgesellschaft',
    href: 'https://www.gesetze-im-internet.de/gmbhg/__13.html',
    detail: 'Amtliche Grundlage zur GmbH mit eigener Rechtspersoenlichkeit und Haftung mit Gesellschaftsvermoegen.',
    tags: ['wirtschaft', 'recht', 'organisation', 'rechtsform', 'unternehmensform', 'gmbh'],
  },
  {
    id: 'aktg-1-ag',
    label: 'AktG Paragraf 1 - Wesen der Aktiengesellschaft',
    href: 'https://www.gesetze-im-internet.de/aktg/__1.html',
    detail: 'Amtliche Grundlage zur Aktiengesellschaft mit eigener Rechtspersoenlichkeit und in Aktien zerlegtem Grundkapital.',
    tags: ['wirtschaft', 'recht', 'organisation', 'rechtsform', 'unternehmensform', 'aktiengesellschaft', 'ag'],
  },
  {
    id: 'lksg-sorgfaltspflichten',
    label: 'Lieferkettensorgfaltspflichtengesetz',
    href: 'https://www.gesetze-im-internet.de/lksg/',
    detail: 'Amtliche Grundlage zu Anwendungsbereich, Risikomanagement und menschenrechtlichen sowie umweltbezogenen Sorgfaltspflichten.',
    tags: ['wirtschaft', 'recht', 'nachhaltigkeit', 'esg', 'lieferkette', 'governance'],
  },
  {
    id: 'eu-taxonomie-2020-852',
    label: 'Verordnung (EU) 2020/852 - EU-Taxonomie',
    href: 'https://eur-lex.europa.eu/eli/reg/2020/852/oj/eng',
    detail: 'Offizielle EU-Grundlage zu Umweltzielen und Kriterien für oekologisch nachhaltige wirtschaftliche Taetigkeiten.',
    tags: ['wirtschaft', 'nachhaltigkeit', 'esg', 'environmental', 'taxonomie', 'kreislaufwirtschaft'],
  },
  {
    id: 'eu-csrd-2022-2464',
    label: 'Richtlinie (EU) 2022/2464 - Corporate Sustainability Reporting Directive',
    href: 'https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:32022L2464',
    detail: 'Offizielle EU-Grundlage zur Nachhaltigkeitsberichterstattung bestimmter Unternehmen.',
    tags: ['wirtschaft', 'nachhaltigkeit', 'esg', 'bericht', 'governance', 'csrd'],
  },
  {
    id: 'bundesregierung-sdgs',
    label: 'Bundesregierung - Die 17 globalen Nachhaltigkeitsziele',
    href: 'https://www.bundesregierung.de/breg-de/themen/nachhaltigkeitspolitik/nachhaltigkeitsziele-verstaendlich-erklaert-232174',
    detail: 'Offizielle Orientierung zu den Sustainable Development Goals der Agenda 2030.',
    tags: ['wirtschaft', 'nachhaltigkeit', 'sdg', 'esg'],
  },
  {
    id: 'ustg-14-rechnungen',
    label: 'UStG Paragraf 14 - Ausstellung von Rechnungen',
    href: 'https://www.gesetze-im-internet.de/ustg_1980/__14.html',
    detail: 'Amtliche Grundlage für Rechnungsbegriff, E-Rechnung und Pflichtangaben.',
    tags: ['rechnung', 'e-rechnung', 'umsatzsteuer', 'pflichtangaben', 'wirtschaft', 'recht'],
  },
  {
    id: 'ustg-14b-aufbewahrung-rechnungen',
    label: 'UStG Paragraf 14b - Aufbewahrung von Rechnungen',
    href: 'https://www.gesetze-im-internet.de/ustg_1980/__14b.html',
    detail: 'Amtliche Grundlage für Aufbewahrung von Rechnungen, Fristbeginn und Sonderfaelle.',
    tags: ['rechnung', 'aufbewahrung', 'aufbewahrungsfrist', 'buchungsbeleg', 'wirtschaft', 'recht'],
  },
  {
    id: 'ustdv-33-kleinbetragsrechnungen',
    label: 'UStDV Paragraf 33 - Rechnungen über Kleinbetraege',
    href: 'https://www.gesetze-im-internet.de/ustdv_1980/__33.html',
    detail: 'Vereinfachte Pflichtangaben für Kleinbetragsrechnungen bis 250 Euro.',
    tags: ['rechnung', 'kleinbetragsrechnung', 'pflichtangaben', 'umsatzsteuer', 'wirtschaft', 'recht'],
  },
  {
    id: 'ao-147-aufbewahrung',
    label: 'AO Paragraf 147 - Aufbewahrung von Unterlagen',
    href: 'https://www.gesetze-im-internet.de/ao_1977/__147.html',
    detail: 'Steuerliche Aufbewahrungsfristen für Buecher, Buchungsbelege und Geschäftsbriefe.',
    tags: ['aufbewahrung', 'aufbewahrungsfrist', 'buchungsbeleg', 'rechnung', 'wirtschaft', 'recht'],
  },
  {
    id: 'hgb-257-aufbewahrung',
    label: 'HGB Paragraf 257 - Aufbewahrung von Unterlagen',
    href: 'https://www.gesetze-im-internet.de/hgb/__257.html',
    detail: 'Handelsrechtliche Aufbewahrungsfristen für Kaufleute.',
    tags: ['aufbewahrung', 'aufbewahrungsfrist', 'buchungsbeleg', 'rechnung', 'wirtschaft', 'recht'],
  },
  {
    id: 'bgb-271-leistungszeit',
    label: 'BGB Paragraf 271 - Leistungszeit',
    href: 'https://www.gesetze-im-internet.de/bgb/__271.html',
    detail: 'Grundregel zur Faelligkeit, wenn keine Leistungszeit bestimmt ist.',
    tags: ['zahlungsziel', 'faelligkeit', 'zahlung', 'recht'],
  },
  {
    id: 'bgb-286-verzug',
    label: 'BGB Paragraf 286 - Verzug des Schuldners',
    href: 'https://www.gesetze-im-internet.de/bgb/__286.html',
    detail: 'Mahnung, kalendermaessiger Termin und 30-Tage-Regel bei Entgeltforderungen.',
    tags: ['zahlungsziel', 'zahlungsverzug', 'mahnung', 'zahlung', 'recht'],
  },
  {
    id: 'bgb-288-verzugszinsen',
    label: 'BGB Paragraf 288 - Verzugszinsen und Verzugsschaden',
    href: 'https://www.gesetze-im-internet.de/bgb/__288.html',
    detail: 'Amtliche Grundlage für Verzugszinsen und 40-Euro-Pauschale im B2B-Verzug.',
    tags: ['zahlungsverzug', 'verzugszinsen', 'zahlung', 'recht'],
  },
  {
    id: 'bmf-e-rechnung-faq',
    label: 'BMF - FAQ zur verpflichtenden E-Rechnung ab 2025',
    href: 'https://www.bundesfinanzministerium.de/Content/DE/FAQ/e-rechnung.html',
    detail: 'Aktueller Stand zur E-Rechnung, sonstiger Rechnung, Ausnahmen und Übergangsregeln.',
    tags: ['rechnung', 'e-rechnung', 'umsatzsteuer', 'wirtschaft', 'recht'],
  },
  {
    id: 'gabler-nutzwertanalyse',
    label: 'Springer Gabler Wirtschaftslexikon - Nutzwertanalyse',
    href: 'https://wirtschaftslexikon.gabler.de/definition/nutzwertanalyse-42926',
    detail: 'Fachlexikon zur Bewertung von Alternativen mit gewichteten Kriterien und Nutzwerten.',
    tags: ['wirtschaft', 'angebot', 'angebotsvergleich', 'nutzwertanalyse', 'entscheidung'],
  },
  {
    id: 'gabler-make-or-buy',
    label: 'Springer Gabler Wirtschaftslexikon - Make or Buy',
    href: 'https://wirtschaftslexikon.gabler.de/definition/make-or-buy-38068',
    detail: 'Fachlexikon zur Entscheidung zwischen Eigenproduktion, Fremdbezug und vertikaler Integration.',
    tags: ['wirtschaft', 'entscheidung', 'make-or-buy', 'eigenfertigung', 'fremdbezug', 'transaktionskosten'],
  },
  {
    id: 'gabler-transaktionskosten',
    label: 'Springer Gabler Wirtschaftslexikon - Transaktionskosten',
    href: 'https://wirtschaftslexikon.gabler.de/definition/transaktionskosten-48987',
    detail: 'Fachlexikon zu Kosten der Anbahnung, Abwicklung und Koordination wirtschaftlicher Transaktionen.',
    tags: ['wirtschaft', 'entscheidung', 'make-or-buy', 'transaktionskosten'],
  },
  {
    id: 'ihk-pfalz-preisgestaltung-kalkulation',
    label: 'IHK Pfalz - Preisgestaltung und Kalkulation',
    href: 'https://www.ihk.de/pfalz/innovation-umwelt-und-existenzgruendung/unternehmensfuehrung/unternehmenssteuerung/preisgestaltung-kalkulation-1279088',
    detail: 'Kaufmaennische Orientierung zu Preisbildung, Kalkulation und Angebotsrechnung.',
    tags: ['wirtschaft', 'angebot', 'angebotsvergleich', 'handelskalkulation', 'bezugspreis', 'kalkulation'],
  },
  {
    id: 'gabler-finanzierung',
    label: 'Springer Gabler Wirtschaftslexikon - Finanzierung',
    href: 'https://wirtschaftslexikon.gabler.de/definition/finanzierung-33079',
    detail: 'Fachlexikon zur Mittelbeschaffung, Innen- und Aussenfinanzierung sowie Eigen- und Fremdfinanzierung.',
    tags: ['finanzierung', 'innenfinanzierung', 'aussenfinanzierung', 'eigenfinanzierung', 'fremdfinanzierung'],
  },
  {
    id: 'gabler-eigenfinanzierung',
    label: 'Springer Gabler Wirtschaftslexikon - Eigenfinanzierung',
    href: 'https://wirtschaftslexikon.gabler.de/definition/eigenfinanzierung-35656',
    detail: 'Fachlexikon zu Eigenfinanzierung als Beschaffung von Eigenkapital.',
    tags: ['finanzierung', 'eigenfinanzierung', 'eigenkapital'],
  },
  {
    id: 'gabler-fremdfinanzierung',
    label: 'Springer Gabler Wirtschaftslexikon - Fremdfinanzierung',
    href: 'https://wirtschaftslexikon.gabler.de/definition/fremdfinanzierung-35508',
    detail: 'Fachlexikon zu Fremdfinanzierung, Glaeubigerstellung, Fristigkeit, Zins und Tilgung.',
    tags: ['finanzierung', 'fremdfinanzierung', 'fremdkapital', 'darlehen', 'kredit'],
  },
  {
    id: 'bgb-488-darlehensvertrag',
    label: 'BGB Paragraf 488 - Darlehensvertrag',
    href: 'https://www.gesetze-im-internet.de/bgb/__488.html',
    detail: 'Amtliche Grundlage für Bereitstellung eines Darlehens, Zinszahlung und Rueckzahlung.',
    tags: ['finanzierung', 'darlehen', 'kredit', 'zins', 'tilgung'],
  },
  {
    id: 'hgb-247-bilanz',
    label: 'HGB Paragraf 247 - Inhalt der Bilanz',
    href: 'https://www.gesetze-im-internet.de/hgb/__247.html',
    detail: 'Amtliche Grundlage für den gesonderten Ausweis von Vermoegen, Eigenkapital, Schulden und Rechnungsabgrenzung.',
    tags: ['finanzierung', 'bilanz', 'eigenkapital', 'fremdkapital'],
  },
  {
    id: 'hgb-266-bilanzgliederung',
    label: 'HGB Paragraf 266 - Gliederung der Bilanz',
    href: 'https://www.gesetze-im-internet.de/hgb/__266.html',
    detail: 'Amtliche Bilanzgliederung mit Eigenkapital, Rueckstellungen und Verbindlichkeiten auf der Passivseite.',
    tags: ['finanzierung', 'bilanz', 'eigenkapital', 'fremdkapital'],
  },
  {
    id: 'bgb-433-kaufvertrag',
    label: 'BGB Paragraf 433 - Kaufvertrag',
    href: 'https://www.gesetze-im-internet.de/bgb/__433.html',
    detail: 'Amtliche Grundlage für Übergabe, Eigentumsverschaffung, Kaufpreiszahlung und Abnahme.',
    tags: ['wirtschaft', 'recht', 'vertragsrecht', 'vertragsarten', 'kaufvertrag', 'kauf', 'kauf-leasing-miete'],
  },
  {
    id: 'bgb-611-dienstvertrag',
    label: 'BGB Paragraf 611 - Dienstvertrag',
    href: 'https://www.gesetze-im-internet.de/bgb/__611.html',
    detail: 'Amtliche Grundlage für versprochene Dienste gegen Verguetung.',
    tags: ['recht', 'vertragsrecht', 'vertragsarten', 'dienstvertrag', 'dienstleistung'],
  },
  {
    id: 'bgb-631-werkvertrag',
    label: 'BGB Paragraf 631 - Werkvertrag',
    href: 'https://www.gesetze-im-internet.de/bgb/__631.html',
    detail: 'Amtliche Grundlage für Herstellung eines Werks oder herbeizufuehrenden Erfolgs gegen Verguetung.',
    tags: ['recht', 'vertragsrecht', 'vertragsarten', 'werkvertrag', 'erfolgspflicht'],
  },
  {
    id: 'bgb-640-abnahme',
    label: 'BGB Paragraf 640 - Abnahme',
    href: 'https://www.gesetze-im-internet.de/bgb/__640.html',
    detail: 'Amtliche Grundlage für die Abnahme eines vertragsgemaess hergestellten Werks.',
    tags: ['recht', 'vertragsrecht', 'vertragsarten', 'werkvertrag', 'abnahme'],
  },
  {
    id: 'bgb-641-verguetung-werkvertrag',
    label: 'BGB Paragraf 641 - Faelligkeit der Verguetung',
    href: 'https://www.gesetze-im-internet.de/bgb/__641.html',
    detail: 'Amtliche Grundlage zur Verguetung beim Werkvertrag im Zusammenhang mit der Abnahme.',
    tags: ['recht', 'vertragsrecht', 'vertragsarten', 'werkvertrag', 'abnahme', 'verguetung'],
  },
  {
    id: 'bgb-535-mietvertrag',
    label: 'BGB Paragraf 535 - Mietvertrag',
    href: 'https://www.gesetze-im-internet.de/bgb/__535.html',
    detail: 'Amtliche Grundlage der zeitweisen Gebrauchsueberlassung gegen Miete.',
    tags: ['wirtschaft', 'recht', 'miete', 'kauf-leasing-miete'],
  },
  {
    id: 'hgb-246-zurechnung',
    label: 'HGB Paragraf 246 - Wirtschaftliche Zurechnung',
    href: 'https://www.gesetze-im-internet.de/hgb/__246.html',
    detail: 'Bilanzierungsgrundsatz, nach dem Vermoegensgegenstaende beim wirtschaftlich Zurechenbaren auszuweisen sind.',
    tags: ['wirtschaft', 'recht', 'bilanz', 'leasing', 'kauf-leasing-miete'],
  },
  {
    id: 'hgb-255-anschaffungskosten',
    label: 'HGB Paragraf 255 - Anschaffungskosten',
    href: 'https://www.gesetze-im-internet.de/hgb/__255.html',
    detail: 'Definition der Anschaffungskosten als Grundlage für Kauf- und Aktivierungsfragen.',
    tags: ['wirtschaft', 'recht', 'bilanz', 'kauf', 'kauf-leasing-miete', 'angebot', 'bezugspreis', 'anschaffungskosten'],
  },
  {
    id: 'estg-7-afa',
    label: 'EStG Paragraf 7 - Absetzung für Abnutzung',
    href: 'https://www.gesetze-im-internet.de/estg/__7.html',
    detail: 'Amtliche Grundlage für lineare AfA bei Wirtschaftsguetern mit Nutzungsdauer über einem Jahr.',
    tags: ['wirtschaft', 'afa', 'abschreibung', 'kauf-leasing-miete'],
  },
  {
    id: 'bafin-finanzierungsleasing',
    label: 'BaFin - Merkblatt Finanzierungsleasing',
    href: 'https://www.bafin.de/SharedDocs/Veroeffentlichungen/DE/Merkblatt/mb_090119_tatbestand_finanzierungsleasing.html',
    detail: 'Abgrenzung von Finanzierungsleasing und Operate-Leasing aus aufsichtsrechtlicher Sicht.',
    tags: ['wirtschaft', 'recht', 'leasing', 'finance-leasing', 'operate-leasing', 'kauf-leasing-miete'],
  },
  {
    id: 'microsoft-processes-threads',
    label: 'Microsoft Learn - About Processes and Threads',
    href: 'https://learn.microsoft.com/en-us/windows/win32/procthread/about-processes-and-threads',
    detail: 'Offizielle Microsoft-Dokumentation zu Prozessressourcen, Threads, Thread-Kontext und preemptivem Multitasking.',
    tags: ['betriebssystem', 'prozess', 'thread', 'task', 'scheduler', 'multitasking'],
  },
  {
    id: 'microsoft-processes-threads-overview',
    label: 'Microsoft Learn - Processes and Threads',
    href: 'https://learn.microsoft.com/en-us/windows/win32/procthread/processes-and-threads',
    detail: 'Grunddefinitionen: Prozess als ausgefuehrtes Programm und Thread als Einheit fuer Prozessorzeit.',
    tags: ['betriebssystem', 'prozess', 'thread', 'task'],
  },
  {
    id: 'microsoft-scheduling-priorities',
    label: 'Microsoft Learn - Scheduling Priorities',
    href: 'https://learn.microsoft.com/en-us/windows/win32/procthread/scheduling-priorities',
    detail: 'Offizielle Beschreibung von Thread-Prioritaeten, Zeitscheiben und Unterbrechung durch hoehere Prioritaet.',
    tags: ['betriebssystem', 'scheduler', 'thread', 'prioritaet', 'multitasking'],
  },
  {
    id: 'linux-kernel-cfs',
    label: 'Linux Kernel Documentation - CFS Scheduler',
    href: 'https://docs.kernel.org/scheduler/sched-design-CFS.html',
    detail: 'Linux-Kernel-Dokumentation zum Scheduler und zur fairen Verteilung von CPU-Zeit auf Tasks.',
    tags: ['betriebssystem', 'linux', 'scheduler', 'task', 'prozess', 'thread'],
  },
  {
    id: 'microsoft-ad-ds-overview',
    label: 'Microsoft Learn - Active Directory Domain Services overview',
    href: 'https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/virtual-dc/active-directory-domain-services-overview',
    detail: 'Offizielle Beschreibung zentraler Verzeichnisdienste, Benutzer-, Computer-, Gruppen- und Rechteverwaltung.',
    tags: ['betriebssystem', 'zentral', 'dezentral', 'verzeichnisdienst', 'active-directory', 'benutzerverwaltung', 'client-server'],
  },
  {
    id: 'bsi-cloud-grundlagen',
    label: 'BSI - Cloud Computing Grundlagen',
    href: 'https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Informationen-und-Empfehlungen/Empfehlungen-nach-Angriffszielen/Cloud-Computing/Grundlagen/grundlagen.html',
    detail: 'BSI-Grundlagen zu Cloud Computing, gemeinsam genutzten Ressourcen, Skalierbarkeit, Elastizitaet und Selbstbedienung.',
    tags: ['cloud', 'zentral', 'dezentral', 'hybrid', 'betriebssystem', 'it-infrastruktur'],
  },
  {
    id: 'nist-sp-800-145',
    label: 'NIST SP 800-145 - The NIST Definition of Cloud Computing',
    href: 'https://www.nist.gov/publications/nist-definition-cloud-computing',
    detail: 'Standarddefinition von Cloud Computing mit wesentlichen Merkmalen, Service- und Bereitstellungsmodellen.',
    tags: ['cloud', 'iaas', 'paas', 'saas', 'hybrid', 'it-infrastruktur'],
  },
  {
    id: 'ieee-80211-working-group',
    label: 'IEEE 802.11 Working Group - About 802.11',
    href: 'https://www.ieee802.org/11/abt80211.html',
    detail: 'Offizielle Einordnung der IEEE-802.11-Arbeitsgruppe und des Standards fuer Wireless LAN MAC/PHY.',
    tags: ['wlan', 'wifi', 'wi-fi', '802.11', 'funknetz', 'access-point'],
  },
  {
    id: 'ieee-sa-p802-11',
    label: 'IEEE SA - P802.11',
    href: 'https://standards.ieee.org/802_11.html',
    detail: 'Offizielle IEEE-Seite zum 802.11-Standard fuer Wireless LAN.',
    tags: ['wlan', 'wifi', 'wi-fi', '802.11', 'standard'],
  },
  {
    id: 'wifi-alliance-security',
    label: 'Wi-Fi Alliance - Wi-Fi security',
    href: 'https://www.wi-fi.org/discover-wi-fi/security',
    detail: 'Wi-Fi-Alliance-Informationen zu WPA3 und WLAN-Sicherheitsgenerationen.',
    tags: ['wlan', 'wifi', 'wi-fi', 'wpa2', 'wpa3', 'sicherheit'],
  },
  {
    id: 'bsi-wlan-lan-grundlagen',
    label: 'BSI - WLAN und LAN: was man wissen sollte',
    href: 'https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Router-WLAN-VPN/WLAN-LAN-was-man-wissen-sollte/wlan-lan-was-man-wissen-sollte_node.html',
    detail: 'BSI-Grundlagen zu WLAN, LAN und der Empfehlung, WPA2 oder WPA3 zu verwenden.',
    tags: ['wlan', 'lan', 'wpa2', 'wpa3', 'sicherheit'],
  },
  {
    id: 'bsi-wlan-sicherheitstipps',
    label: 'BSI - Sicherheitstipps im privaten und oeffentlichen WLAN',
    href: 'https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Router-WLAN-VPN/Sicherheitstipps-fuer-privates-und-oeffentliches-WLAN/sicherheitstipps-fuer-privates-und-oeffentliches-wlan.html',
    detail: 'BSI-Empfehlungen zu Routerpasswoertern, sicherer Konfiguration und vorsichtiger Nutzung fremder WLANs.',
    tags: ['wlan', 'router', 'sicherheit', 'passwort', 'gastnetz'],
  },
  {
    id: 'bsi-router-wlan-vpn',
    label: 'BSI - Router und WLAN sicher einrichten',
    href: 'https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Router-WLAN-VPN/router-wlan-vpn.html',
    detail: 'BSI-Hinweise zum sicheren Betrieb von Routern als zentrale Schnittstelle zwischen Internet und Heimnetz.',
    tags: ['router', 'nat', 'port-forwarding', 'firewall', 'vpn', 'sicherheit', 'netzwerk'],
  },
  {
    id: 'bsi-firewall',
    label: 'BSI - Firewall - Schutz vor dem Angriff von aussen',
    href: 'https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Virenschutz-Firewall/Firewall/firewall.html',
    detail: 'BSI-Grundlagen zur Aufgabe von Firewalls zwischen internem und externem Netz.',
    tags: ['firewall', 'sicherheit', 'netzwerk', 'port-forwarding', 'dmz'],
  },
  {
    id: 'bsi-net-1-1-netzarchitektur',
    label: 'BSI IT-Grundschutz - NET.1.1 Netzarchitektur und -design',
    href: 'https://it-grundschutzkompendium.de/net_netze_und_kommunikation/net.1.1_netzarchitektur_und_-design',
    detail: 'BSI-Grundschutz-Baustein zu Netztrennung in Zonen, DMZ, Aussenanbindung und Absicherung von Zonenuebergaengen.',
    tags: ['firewall', 'dmz', 'netzsegmentierung', 'sicherheit', 'netzwerk', 'allowlist'],
  },
  {
    id: 'bsi-net-3-2-firewall',
    label: 'BSI IT-Grundschutz - NET.3.2 Firewall',
    href: 'https://it-grundschutzkompendium.de/net_netze_und_kommunikation/net.3.2_firewall',
    detail: 'BSI-Grundschutz-Baustein zu Firewalls als Kopplung IP-basierter Netze und zur Einschraenkung erlaubter Kommunikation.',
    tags: ['firewall', 'dmz', 'paketfilter', 'application-layer-gateway', 'sicherheit', 'netzwerk'],
  },
  {
    id: 'bsi-vpn',
    label: 'BSI - Virtual Private Networks (VPNs)',
    href: 'https://www.bsi.bund.de/EN/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Router-WLAN-VPN/Virtual-Private-Networks-VPN/virtual-private-networks-vpn_node.html',
    detail: 'BSI-Erklaerung zu VPNs und Hinweis, dass Port Forwarding fuer eigene VPN-/NAS-Loesungen risikobehaftet sein kann.',
    tags: ['vpn', 'router', 'port-forwarding', 'sicherheit', 'netzwerk'],
  },
  {
    id: 'gabler-mitarbeitermotivation',
    label: 'Springer Gabler Wirtschaftslexikon - Mitarbeitermotivation',
    href: 'https://wirtschaftslexikon.gabler.de/definition/mitarbeitermotivation-52003',
    detail: 'Fachlexikon zu Mitarbeitermotivation und Einflussfaktoren im Unternehmen.',
    tags: ['motivation', 'team', 'change', 'personal', 'kommunikation'],
  },
  {
    id: 'tuckman-jensen-teamphasen',
    label: 'Tuckman & Jensen - Stages of Small-Group Development Revisited',
    href: 'https://doi.org/10.1177/105960117700200404',
    detail: 'Wissenschaftliche Quelle für Forming, Storming, Norming, Performing und Adjourning.',
    tags: ['team', 'teamphasen', 'projekt', 'kommunikation'],
  },
  {
    id: 'gabler-change-management',
    label: 'Springer Gabler Wirtschaftslexikon - Change Management',
    href: 'https://wirtschaftslexikon.gabler.de/definition/change-management-28354',
    detail: 'Fachlexikon zu Zielen, Anlaessen und Gestaltung organisatorischer Veraenderungen.',
    tags: ['change', 'projekt', 'kommunikation', 'prozess'],
  },
  {
    id: 'iso-10015',
    label: 'ISO 10015:2019 - Quality management - Guidelines for competence management and people development',
    href: 'https://www.iso.org/standard/69459.html',
    detail: 'Internationale Norm mit Leitlinien zu Kompetenzmanagement und Entwicklung von Personen in Organisationen.',
    tags: ['schulung', 'kompetenz', 'qualitaet', 'personal', 'prozess'],
  },
  {
    id: 'gabler-crm',
    label: 'Springer Gabler Wirtschaftslexikon - Customer Relationship Management (CRM)',
    href: 'https://wirtschaftslexikon.gabler.de/definition/customer-relationship-management-crm-30809',
    detail: 'Fachlexikon zu CRM als strategischem Ansatz für Kundenlebenszyklus, Kundenprozesse und CRM-Software.',
    tags: ['unternehmenssoftware', 'crm', 'software', 'service'],
  },
  {
    id: 'gabler-erp-system',
    label: 'Springer Gabler Wirtschaftslexikon - Enterprise-Resource-Planning-System',
    href: 'https://wirtschaftslexikon.gabler.de/definition/enterprise-resource-planning-system-51587',
    detail: 'Fachlexikon zu ERP-Systemen mit Modulen, gemeinsamer Datenbasis und bereichsuebergreifender Prozessunterstuetzung.',
    tags: ['unternehmenssoftware', 'erp', 'software'],
  },
  {
    id: 'gabler-dms',
    label: 'Springer Gabler Wirtschaftslexikon - Dokumentenmanagementsystem',
    href: 'https://wirtschaftslexikon.gabler.de/definition/dokumentenmanagementsystem-32496',
    detail: 'Fachlexikon zu DMS-Funktionen wie Mehrbenutzerzugriff, Rechteverwaltung, Verteilung, Klassifizierung und Suche.',
    tags: ['unternehmenssoftware', 'dms', 'software'],
  },
  {
    id: 'gabler-cms',
    label: 'Springer Gabler Wirtschaftslexikon - Content Management System (CMS)',
    href: 'https://wirtschaftslexikon.gabler.de/definition/content-management-system-cms-31303',
    detail: 'Fachlexikon zu CMS mit Redaktionssystem, Content Repository, Publishing und Trennung von Inhalt und Layout.',
    tags: ['unternehmenssoftware', 'cms', 'software', 'web'],
  },
  {
    id: 'gabler-aida-regel',
    label: 'Springer Gabler Wirtschaftslexikon - AIDA-Regel',
    href: 'https://wirtschaftslexikon.gabler.de/definition/aida-regel-29523',
    detail: 'Fachlexikon zur AIDA-Regel als klassischem, aber nur begrenzt linearem Werbewirkungsmodell.',
    tags: ['wirtschaft', 'marketing', 'kommunikation', 'werbung', 'aida', 'werbewirkung'],
  },
  {
    id: 'gabler-werbewirkung',
    label: 'Springer Gabler Wirtschaftslexikon - Werbewirkung',
    href: 'https://wirtschaftslexikon.gabler.de/definition/werbewirkung-49647',
    detail: 'Fachlexikon zu psychischer und oekonomischer Werbewirkung sowie passenden Messgroessen.',
    tags: ['wirtschaft', 'marketing', 'kommunikation', 'werbung', 'werbewirkung'],
  },
  {
    id: 'bsi-grundschutz',
    label: 'BSI - IT-Grundschutz-Kompendium',
    href: 'https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/IT-Grundschutz/IT-Grundschutz-Kompendium/it-grundschutz-kompendium_node.html',
    detail: 'Praxisnaher Referenzrahmen für Informationssicherheit, Betrieb, Schutzbedarf und Maßnahmen.',
    tags: ['sicherheit', 'backup', 'firewall', 'dmz', 'passwort', 'krypto', 'verfuegbarkeit'],
  },
  {
    id: 'bsi-kryptografie',
    label: 'BSI - Kryptografie',
    href: 'https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Informationen-und-Empfehlungen/Kryptografie/kryptografie_node.html',
    detail: 'BSI-Einstieg zu kryptografischen Verfahren, Schutzzielen und sicheren Mechanismen.',
    tags: ['sicherheit', 'krypto', 'verschluesselung', 'hashing', 'passwort'],
  },
  {
    id: 'bsi-tr-02102-1',
    label: 'BSI TR-02102-1 - Kryptografische Verfahren',
    href: 'https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TG02102/BSI-TR-02102-1.html',
    detail: 'Technische Richtlinie des BSI zu kryptografischen Mechanismen, Empfehlungen und Schlüssellaengen.',
    tags: ['sicherheit', 'krypto', 'verschluesselung', 'hashing', 'signatur'],
  },
  {
    id: 'rfc-8446',
    label: 'RFC 8446 - TLS 1.3',
    href: 'https://www.rfc-editor.org/rfc/rfc8446',
    detail: 'IETF-Standard für Transport Layer Security, Grundlage für HTTPS und viele TLS-basierte VPNs.',
    tags: ['sicherheit', 'krypto', 'tls', 'zertifikat', 'verschluesselung'],
  },
  {
    id: 'rfc-5280',
    label: 'RFC 5280 - X.509 PKI Certificate and CRL Profile',
    href: 'https://www.rfc-editor.org/rfc/rfc5280',
    detail: 'IETF-Profil für X.509-Zertifikate, Zertifikatsketten, Widerrufslisten und Pfadpruefung.',
    tags: ['sicherheit', 'krypto', 'zertifikat', 'pki', 'signatur'],
  },
  {
    id: 'rfc-4301',
    label: 'RFC 4301 - IPsec Security Architecture',
    href: 'https://www.rfc-editor.org/rfc/rfc4301',
    detail: 'IETF-Standard zur Absicherung von IP-Verkehr, Security Associations, AH/ESP und IPsec-VPNs.',
    tags: ['sicherheit', 'krypto', 'vpn', 'ipsec', 'netzwerk'],
  },
  {
    id: 'rfc-9106',
    label: 'RFC 9106 - Argon2 Password Hashing',
    href: 'https://www.rfc-editor.org/rfc/rfc9106',
    detail: 'IRTF-RFC zu Argon2 als speicherhartes Passwort-Hashverfahren.',
    tags: ['sicherheit', 'krypto', 'hashing', 'passwort'],
  },
  {
    id: 'bsi-passwoerter',
    label: 'BSI - Umgang mit Passwoertern',
    href: 'https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Accountschutz/Sichere-Passwoerter-erstellen/Umgang-mit-Passwoertern/umgang-mit-passwoertern_node.html',
    detail: 'Empfehlungen zu Passwortschutz, Passwort-Managern und sicherem Umgang mit Zugangsdaten.',
    tags: ['sicherheit', 'passwort', 'hashing'],
  },
  {
    id: 'rfc-791',
    label: 'RFC 791 - Internet Protocol (IPv4)',
    href: 'https://www.rfc-editor.org/rfc/rfc791',
    detail: 'Originalspezifikation von IPv4; hilfreich für Paketaufbau, Adressierung und Grundlagen.',
    tags: ['netzwerk', 'ipv4', 'subnetting', 'osi'],
  },
  {
    id: 'rfc-1918',
    label: 'RFC 1918 - Address Allocation for Private Internets',
    href: 'https://www.rfc-editor.org/rfc/rfc1918',
    detail: 'Offizielle Grundlage für private IPv4-Adressbereiche wie 10.0.0.0/8, 172.16.0.0/12 und 192.168.0.0/16.',
    tags: ['netzwerk', 'ipv4', 'subnetting', 'private-adressen', 'nat', 'port-forwarding'],
  },
  {
    id: 'rfc-2663',
    label: 'RFC 2663 - IP Network Address Translator Terminology',
    href: 'https://www.rfc-editor.org/rfc/rfc2663',
    detail: 'IETF-RFC zu NAT-Begriffen, Adressraeumen, Basic NAT und NAPT.',
    tags: ['netzwerk', 'ipv4', 'nat', 'napt', 'pat', 'port-forwarding'],
  },
  {
    id: 'rfc-3022',
    label: 'RFC 3022 - Traditional IP Network Address Translator',
    href: 'https://www.rfc-editor.org/rfc/rfc3022',
    detail: 'IETF-RFC zu Traditional NAT, NAPT, Adress- und Portuebersetzung sowie Grenzen von NAT.',
    tags: ['netzwerk', 'ipv4', 'nat', 'napt', 'pat', 'port-forwarding'],
  },
  {
    id: 'rfc-4632',
    label: 'RFC 4632 - Classless Inter-domain Routing (CIDR)',
    href: 'https://www.rfc-editor.org/rfc/rfc4632',
    detail: 'Best Current Practice zu CIDR, Praefixnotation und classless IPv4-Adressierung.',
    tags: ['netzwerk', 'ipv4', 'subnetting', 'cidr'],
  },
  {
    id: 'rfc-3021',
    label: 'RFC 3021 - 31-Bit Prefixes on IPv4 Point-to-Point Links',
    href: 'https://www.rfc-editor.org/rfc/rfc3021',
    detail: 'Spezialfall für /31-Netze auf Punkt-zu-Punkt-Verbindungen.',
    tags: ['netzwerk', 'ipv4', 'subnetting', 'cidr'],
  },
  {
    id: 'iana-ipv4-special-registry',
    label: 'IANA - IPv4 Special-Purpose Address Space',
    href: 'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    detail: 'Offizielles Register für besondere IPv4-Adressbereiche wie Private-Use, Loopback und Link Local.',
    tags: ['netzwerk', 'ipv4', 'subnetting', 'special-purpose'],
  },
  {
    id: 'rfc-8200',
    label: 'RFC 8200 - Internet Protocol Version 6 (IPv6)',
    href: 'https://www.rfc-editor.org/rfc/rfc8200',
    detail: 'Aktuelle Standards-Track-Spezifikation für IPv6.',
    tags: ['netzwerk', 'ipv6', 'osi'],
  },
  {
    id: 'rfc-9293',
    label: 'RFC 9293 - Transmission Control Protocol (TCP)',
    href: 'https://www.rfc-editor.org/rfc/rfc9293',
    detail: 'Aktuelle TCP-Spezifikation; Grundlage für Ports, Verbindungen, Segmente und Zuverlaessigkeit.',
    tags: ['netzwerk', 'tcp', 'osi'],
  },
  {
    id: 'rfc-768',
    label: 'RFC 768 - User Datagram Protocol (UDP)',
    href: 'https://www.rfc-editor.org/rfc/rfc768',
    detail: 'UDP-Spezifikation für verbindungslose Transportkommunikation.',
    tags: ['netzwerk', 'udp', 'osi'],
  },
  {
    id: 'iana-service-port-registry',
    label: 'IANA - Service Name and Transport Protocol Port Number Registry',
    href: 'https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml',
    detail: 'Offizielles Register fuer Service-Namen, Portnummern und Transportprotokolle.',
    tags: ['netzwerk', 'tcp', 'udp', 'port', 'dienst'],
  },
  {
    id: 'rfc-9110',
    label: 'RFC 9110 - HTTP Semantics',
    href: 'https://www.rfc-editor.org/rfc/rfc9110',
    detail: 'Aktuelle HTTP-Semantik als Beispiel fuer ein Anwendungsprotokoll oberhalb der Transportschicht.',
    tags: ['netzwerk', 'http', 'web', 'tcp'],
  },
  {
    id: 'postgres-docs',
    label: 'PostgreSQL Documentation - SQL',
    href: 'https://www.postgresql.org/docs/current/sql.html',
    detail: 'Serioese SQL-Referenz für Abfragen, Joins, Datendefinition und Datenmanipulation.',
    tags: ['datenbank', 'sql', 'normalisierung', 'er'],
  },
  {
    id: 'sqlite-lang',
    label: 'SQLite Documentation - SQL Language',
    href: 'https://www.sqlite.org/lang.html',
    detail: 'Kompakte SQL-Referenz mit Syntaxbeispielen für Lern- und Prüfungsaufgaben.',
    tags: ['datenbank', 'sql'],
  },
  {
    id: 'scrum-guide',
    label: 'The Scrum Guide (2020)',
    href: 'https://scrumguides.org/scrum-guide.html',
    detail: 'Primaerquelle für Scrum: Accountabilities, fuenf Events, drei Artefakte mit Commitments (Product Goal, Sprint Goal, Definition of Done). Ken Schwaber und Jeff Sutherland, November 2020.',
    tags: ['projekt', 'scrum', 'agil', 'sprint', 'backlog', 'increment', 'product-goal', 'sprint-goal', 'definition-of-done'],
  },
  {
    id: 'scrum-guide-revisions',
    label: 'Scrum Guide - Revisionen 2017 → 2020',
    href: 'https://scrumguides.org/revisions.html',
    detail: 'Offizielle Aenderungsliste: Rollen heissen jetzt Accountabilities, eine Scrum-Team-Struktur ohne separates Development Team, Product Goal eingefuehrt, Commitments pro Artefakt, Warum als drittes Sprint-Planning-Thema.',
    tags: ['projekt', 'scrum', 'agil', 'accountabilities'],
  },
  {
    id: 'mountain-goat-scrum-2020',
    label: 'Mountain Goat Software - Top 5 Changes in the 2020 Scrum Guide',
    href: 'https://www.mountaingoatsoftware.com/blog/top-5-changes-in-the-2020-version-of-the-scrum-guide',
    detail: 'Kommentierter Vergleich der 2017er- und 2020er-Fassung mit didaktischer Einordnung von Mike Cohn und Brian Milner.',
    tags: ['projekt', 'scrum', 'agil', 'accountabilities'],
  },
  {
    id: 'axelos-itil-reader',
    label: 'AXELOS - ITIL 4 Practice Guide Reader Manual',
    href: 'https://www.axelos.com/resource-hub/practice/readers-manual-itil-4-practice-guide',
    detail: 'Offizielle Orientierung zu ITIL-Practices, Prozessen, Incident Management und Service Level Management.',
    tags: ['service', 'incident', 'support', 'sla', 'prozess'],
  },
  {
    id: 'axelos-service-desk',
    label: 'AXELOS - ITIL 4 Practitioner: Service Desk',
    href: 'https://www.axelos.com/certifications/itil-service-management/itil-practices-manager/itil-4-specialist-monitor-support-and-fulfil/itil-4-practitioner-service-desk',
    detail: 'Service Desk als zentraler Kontaktpunkt zwischen Service Provider und Nutzern.',
    tags: ['service', 'support', 'service-desk'],
  },
  {
    id: 'axelos-incident-management',
    label: 'AXELOS - ITIL 4 Practitioner: Incident Management',
    href: 'https://www.axelos.com/certifications/itil-service-management/itil-practices-manager/itil-4-specialist-monitor-support-and-fulfil/itil-4-practitioner-incident-management',
    detail: 'Incident Management mit Fokus auf schnelle Wiederherstellung des normalen Servicebetriebs.',
    tags: ['service', 'incident', 'support'],
  },
  {
    id: 'axelos-service-request',
    label: 'AXELOS - ITIL 4 Practitioner: Service Request Management',
    href: 'https://www.axelos.com/certifications/itil-service-management/itil-practices-manager/itil-4-specialist-monitor-support-and-fulfil/itil-4-practitioner-service-request-management',
    detail: 'Service Request Management für strukturierte, vordefinierte Nutzeranfragen.',
    tags: ['service', 'service-request', 'support', 'sla'],
  },
  {
    id: 'omg-bpmn',
    label: 'Object Management Group - BPMN',
    href: 'https://www.omg.org/spec/BPMN/',
    detail: 'Offizielle Spezifikation der Business Process Model and Notation.',
    tags: ['projekt', 'bpmn', 'prozess'],
  },
  {
    id: 'omg-uml',
    label: 'Object Management Group - UML',
    href: 'https://www.omg.org/spec/UML/',
    detail: 'Offizielle UML-Spezifikation für Aktivitaets-, Use-Case- und Klassendiagramme.',
    tags: ['software', 'uml', 'modellierung'],
  },
  {
    id: 'w3c-wcag',
    label: 'W3C - Web Content Accessibility Guidelines (WCAG)',
    href: 'https://www.w3.org/WAI/standards-guidelines/wcag/',
    detail: 'Grundlage für Barrierefreiheit und Softwareergonomie im Web.',
    tags: ['web', 'ergonomie', 'barrierefreiheit'],
  },
  {
    id: 'mdn-web',
    label: 'MDN Web Docs',
    href: 'https://developer.mozilla.org/',
    detail: 'Technische Referenz für Webtechnologien, HTTP, Browsergrundlagen und Frontend-Begriffe.',
    tags: ['web', 'software', 'http'],
  },
  {
    id: 'dsgvo',
    label: 'EUR-Lex - Datenschutz-Grundverordnung (DSGVO)',
    href: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj?locale=de',
    detail: 'Amtlicher EU-Text der DSGVO, besonders Art. 5 zu den Grundsaetzen der Verarbeitung.',
    tags: ['recht', 'dsgvo', 'sicherheit', 'datenschutz'],
  },
  {
    id: 'bgb',
    label: 'Buergerliches Gesetzbuch (BGB)',
    href: 'https://www.gesetze-im-internet.de/bgb/',
    detail: 'Amtliche Grundlage für Kaufvertrag, Leistungsstoerungen, Verzug, Gewaehrleistung und Garantie.',
    tags: ['recht', 'vertragsrecht', 'gewaehrleistung'],
  },
  {
    id: 'hgb',
    label: 'Handelsgesetzbuch (HGB)',
    href: 'https://www.gesetze-im-internet.de/hgb/',
    detail: 'Amtliche Grundlage für Handelsgeschaefte und Maengelruege im Handelskauf.',
    tags: ['recht', 'vertragsrecht', 'maengelruege'],
  },
  {
    id: 'afa-bmf',
    label: 'Bundesfinanzministerium - AfA-Tabellen',
    href: 'https://www.bundesfinanzministerium.de/Web/DE/Themen/Steuern/Weitere_Steuerthemen/Betriebspruefung/AfA_Tabellen/afa_tabellen.html',
    detail: 'Offizielle Orientierung für Nutzungsdauern und lineare Abschreibung.',
    tags: ['wirtschaft', 'afa', 'abschreibung'],
  },
  {
    id: 'destatis-preise',
    label: 'Statistisches Bundesamt - Preise',
    href: 'https://www.destatis.de/DE/Themen/Wirtschaft/Preise/_inhalt.html',
    detail: 'Serioese Datenquelle für wirtschaftliche Rahmenwerte und Preisentwicklung.',
    tags: ['wirtschaft', 'kosten', 'markt'],
  },
  {
    id: 'nist-binary-prefixes',
    label: 'NIST - Prefixes for Binary Multiples',
    href: 'https://physics.nist.gov/cuu/Units/binary.html',
    detail: 'Offizielle Definition der binaeren Praefixe (KiB, MiB, GiB) und Abgrenzung zu SI-Praefixen.',
    tags: ['ordnung', 'bit', 'byte', 'binaer', 'iec', 'praefix', 'datenmenge'],
  },
  {
    id: 'iec-80000-13',
    label: 'IEC 80000-13 - Information science and technology',
    href: 'https://webstore.iec.ch/publication/80483',
    detail: 'Internationaler Standard fuer Einheiten und Praefixe der Informationstechnik, definiert kibi, mebi, gibi und Folgepraefixe.',
    tags: ['ordnung', 'bit', 'byte', 'binaer', 'iec', 'praefix', 'datenmenge'],
  },
  {
    id: 'ansi-x3-4-ascii',
    label: 'ANSI INCITS 4-1986 (R2017) - 7-Bit ASCII',
    href: 'https://webstore.ansi.org/standards/incits/ansiincits41986r2017',
    detail: 'US-amerikanischer Standard fuer den 7-Bit-ASCII-Zeichensatz mit 128 Codepunkten.',
    tags: ['ordnung', 'ascii', 'zeichenkodierung', 'bit', 'byte'],
  },
  {
    id: 'bipm-si-prefixes',
    label: 'BIPM - SI prefixes',
    href: 'https://www.bipm.org/en/measurement-units/si-prefixes',
    detail: 'Internationales Bureau fuer Mass und Gewicht (BIPM): Offizielle SI-Praefixe k=10^3, M=10^6, G=10^9, T=10^12 etc. Die Verwendung von kilo (k) fuer 2^10 ist laut SI unzulaessig.',
    tags: ['ordnung', 'praefix', 'si', 'dezimal', 'datenmenge', 'bit', 'byte'],
  },
  {
    id: 'jedec-100b-01',
    label: 'JEDEC 100B.01 - Unit Prefixes for Semiconductor Storage Capacity',
    href: 'https://www.nomad.jedec.org/standards-documents/dictionary/terms/mega-m-prefix-units-semiconductor-storage-capacity',
    detail: 'JEDEC-Industriestandard: dokumentiert die in der Halbleiterindustrie verbreitete binaere Auslegung von K=1024, M=2^20, G=2^30 ausdruecklich nur "to reflect common usage" - erklaert die historische Wurzel der KB/KiB-Verwirrung.',
    tags: ['ordnung', 'praefix', 'binaer', 'datenmenge', 'bit', 'byte', 'industrie'],
  },
  {
    id: 'posix-chmod',
    label: 'IEEE Std 1003.1 (POSIX) - chmod',
    href: 'https://pubs.opengroup.org/onlinepubs/9699919799/utilities/chmod.html',
    detail: 'Open-Group-Spezifikation: definiert die zwoelf File-Mode-Bits als vier Oktalziffern. Wertigkeiten r=4, w=2, x=1 fuer die Rollen User, Group und Other - Grundlage fuer das Lesen von chmod 755, 644, 700.',
    tags: ['ordnung', 'betriebssystem', 'linux', 'chmod', 'oktal', 'dateirechte', 'posix', 'sicherheit'],
  },
  {
    id: 'rfc-9542',
    label: 'RFC 9542 - IANA Considerations and IETF Usage for IEEE 802 Parameters',
    href: 'https://www.rfc-editor.org/rfc/rfc9542.html',
    detail: 'Aktuelle IETF-Quelle (loest RFC 7042 ab) zur kanonischen Darstellung von 48-Bit-MAC-Adressen (EUI-48) als sechs Paare hexadezimaler Ziffern, getrennt durch Doppelpunkte oder Bindestriche.',
    tags: ['ordnung', 'netzwerk', 'mac-adresse', 'eui-48', 'hex', 'hexadezimal', 'ieee-802'],
  },
  {
    id: 'w3c-css-color-4',
    label: 'W3C - CSS Color Module Level 4',
    href: 'https://www.w3.org/TR/css-color-4/',
    detail: 'W3C-Spezifikation der Hex-Notation #RRGGBB[AA] fuer sRGB-Farben: drei (oder vier) Bytes Rot/Gruen/Blau (Alpha) als jeweils zwei Hex-Ziffern, 0x00 bis 0xFF pro Kanal.',
    tags: ['ordnung', 'web', 'css', 'farbe', 'hex', 'hexadezimal', 'rgb'],
  },
  {
    id: 'python-lexical-integer-literals',
    label: 'Python Language Reference - Integer literals',
    href: 'https://docs.python.org/3/reference/lexical_analysis.html#integer-literals',
    detail: 'Offizielle Python-Referenz zu Ganzzahl-Literalen: 0b fuer binaer, 0o fuer oktal, 0x fuer hexadezimal; fuehrende Nullen in Nicht-Null-Dezimalzahlen sind nicht erlaubt.',
    tags: ['ordnung', 'python', 'literal', 'binaer', 'oktal', 'hex', 'praefix'],
  },
  {
    id: 'ecma-262-numeric-literals',
    label: 'ECMAScript Language Specification - Numeric literals',
    href: 'https://262.ecma-international.org/15.0/',
    detail: 'Offizielle ECMAScript-Spezifikation fuer numerische Literale, unter anderem binaere, oktale und hexadezimale Schreibweisen.',
    tags: ['ordnung', 'javascript', 'ecmascript', 'literal', 'binaer', 'oktal', 'hex', 'praefix'],
  },
]
