import type { SourceEntry } from "../../lib/quellen/types"

export const sourceBank: SourceEntry[] = [
  {
    id: 'hgb-prokura-handlungsvollmacht',
    label: 'Handelsgesetzbuch (HGB) – §§ 48 bis 58',
    href: 'https://www.gesetze-im-internet.de/hgb/BJNR002190897.html',
    detail: 'Amtliche Primärquelle zu Erteilung, Umfang, Grenzen, Zeichnung und Erlöschen von Prokura und Handlungsvollmacht.',
    tags: ['wirtschaft', 'recht', 'vollmacht', 'prokura', 'handlungsvollmacht', 'vertretung', 'handelsregister'],
  },
  {
    id: 'bgb-stellvertretung',
    label: 'Bürgerliches Gesetzbuch (BGB) – §§ 164 bis 181',
    href: 'https://www.gesetze-im-internet.de/bgb/BJNR001950896.html',
    detail: 'Amtliche Primärquelle zu Wirkung der Stellvertretung, Vollmacht, Genehmigung und Haftung bei fehlender Vertretungsmacht.',
    tags: ['wirtschaft', 'recht', 'vollmacht', 'vertretung', 'vertretungsmacht', 'genehmigung'],
  },
  {
    id: 'ihk-pfalz-prokura-handlungsvollmacht',
    label: 'IHK Pfalz – Prokura und Handlungsvollmacht',
    href: 'https://www.ihk.de/pfalz/recht/handel-und-gesellschaftsrecht/handelsrecht/prokura-handlungsvollmacht-1281742',
    detail: 'Fachliche Einordnung von Erteilung, Registerwirkung, Umfang, gesetzlichen Grenzen sowie Innen- und Außenverhältnis.',
    tags: ['wirtschaft', 'recht', 'vollmacht', 'prokura', 'handlungsvollmacht', 'innenverhaeltnis', 'aussenverhaeltnis'],
  },
  {
    id: 'ihk-duesseldorf-vertretung-handelsrecht',
    label: 'IHK Düsseldorf – Die Vertretung im Handelsrecht',
    href: 'https://www.ihk.de/duesseldorf/recht-und-steuern/recht/die-vertretung-im-handelsrecht-5864042',
    detail: 'Aktuelles Merkblatt (Stand Dezember 2025) zur Prokura, Handlungsvollmacht und zu den Folgen fehlender Vertretungsmacht.',
    tags: ['wirtschaft', 'recht', 'vollmacht', 'prokura', 'handlungsvollmacht', 'vertretungsmacht'],
  },
  {
    id: 'bibb-fachinformatiker',
    label: 'BIBB - Fachinformatiker/Fachinformatikerin, Umsetzungshilfe',
    href: 'https://www.bibb.de/dienst/publikationen/de/16661',
    detail: 'Ausbildungsordnung, Ausbildungsrahmenplan, Lernfelder und Prüfungsstruktur der modernisierten IT-Berufe.',
    tags: ['ordnung', 'ausbildung', 'ap1', 'ap2', 'projekt', 'wirtschaft', 'sicherheit'],
  },
  {
    id: 'fiausbv',
    label: 'Fachinformatikerausbildungsverordnung (FIAusbV)',
    href: 'https://www.gesetze-im-internet.de/fiausbv/BJNR025000020.html',
    detail: 'Amtliche Rechtsgrundlage mit Ausbildungsrahmenplan und Anforderungen an die Abschlussprüfung.',
    tags: ['ordnung', 'ausbildung', 'recht', 'ap1', 'ap2'],
  },
  {
    id: 'bbig',
    label: 'Berufsbildungsgesetz (BBiG)',
    href: 'https://www.gesetze-im-internet.de/bbig_2005/',
    detail: 'Amtliche Grundlage für Berufsausbildungsvertrag, Rechte und Pflichten im Ausbildungsverhältnis, Probezeit und Kündigung.',
    tags: ['ordnung', 'ausbildung', 'recht', 'ausbildungsvertrag', 'ausbildungsnachweis'],
  },
  {
    id: 'kmk-rahmenlehrplan',
    label: 'KMK - Rahmenlehrplan Fachinformatiker/Fachinformatikerin',
    href: 'https://www.kmk.org/fileadmin/Dateien/pdf/Bildung/BeruflicheBildung/rlp/Fachinformatiker_19-12-13_EL.pdf',
    detail: 'Berufsschulische Lernfelder für die Fachinformatiker-Ausbildung.',
    tags: ['ordnung', 'ausbildung', 'lernfelder', 'ap1', 'ap2'],
  },
  {
    id: 'arbstaettv',
    label: 'Arbeitsstättenverordnung (ArbStättV)',
    href: 'https://www.gesetze-im-internet.de/arbst_ttv_2004/',
    detail: 'Amtliche Grundlage zu Arbeitsstätten, Telearbeitsplätzen und Bildschirmarbeit, besonders § 2 Abs. 7 und Anhang Nr. 6.',
    tags: ['recht', 'arbeitsschutz', 'ergonomie', 'telearbeit', 'bildschirmarbeit', 'barrierefreiheit'],
  },
  {
    id: 'arbschg',
    label: 'Arbeitsschutzgesetz (ArbSchG)',
    href: 'https://www.gesetze-im-internet.de/arbschg/',
    detail: 'Amtliche Grundlage für Arbeitgeberpflichten, Gefährdungsbeurteilung und Schutzmaßnahmen bei der Arbeit.',
    tags: ['recht', 'arbeitsschutz', 'ergonomie', 'telearbeit'],
  },
  {
    id: 'baua-gefaehrdungsbeurteilung',
    label: 'BAuA - Grundlagen der Gefährdungsbeurteilung',
    href: 'https://www.baua.de/DE/Themen/Arbeitsgestaltung/Gefaehrdungsbeurteilung/Handbuch-Gefaehrdungsbeurteilung/Grundlagenwissen/Grundlagen/Grundlagen_dossier?pos=2',
    detail: 'Fachliche Einordnung der Gefährdungsbeurteilung und des Arbeitsschutzes für Personen in Berufsausbildung.',
    tags: ['recht', 'arbeitsschutz', 'gefaehrdungsbeurteilung', 'ausbildung'],
  },
  {
    id: 'dihk-it-berufe-umsetzungshilfe',
    label: 'DIHK - Umsetzungsempfehlung für die Durchführung der Abschlussprüfung in den IT-Berufen',
    href: 'https://www.dihk.de/de/themen-und-positionen/fachkraefte/aus-und-weiterbildung/ausbildung/ausbildungspruefungen/it-berufe-umsetzungsempfehlung-75292',
    detail: 'Einordnung der gestreckten Abschlussprüfung und der beruflichen Handlungskompetenz in den IT-Berufen.',
    tags: ['ordnung', 'ausbildung', 'ap1', 'pruefungsrealitaet'],
  },
  {
    id: 'dguv-215-410',
    label: 'DGUV Information 215-410 - Bildschirm- und Büroarbeitsplätze',
    href: 'https://publikationen.dguv.de/regelwerk/dguv-informationen/3445/bildschirm-und-bueroarbeitsplaetze',
    detail: 'Praxisleitfaden der gesetzlichen Unfallversicherung zur ergonomischen Gestaltung von Bildschirm- und Büroarbeitsplätzen.',
    tags: ['arbeitsschutz', 'ergonomie', 'bildschirmarbeit', 'hardware', 'telearbeit'],
  },
  {
    id: 'baua-mobile-arbeit-homeoffice',
    label: 'BAuA - Mobile Arbeit und Homeoffice',
    href: 'https://www.baua.de/DE/Themen/Arbeitsgestaltung-im-Betrieb/Mobile-Arbeit-Homeoffice/_node.html',
    detail: 'Arbeitsschutzorientierte Einordnung von mobiler Arbeit, Homeoffice, Telearbeit und Gestaltung mobiler Arbeitsformen.',
    tags: ['arbeitsschutz', 'ergonomie', 'homeoffice', 'telearbeit', 'mobile-arbeit'],
  },
  {
    id: 'bitv-2-0',
    label: 'Barrierefreie-Informationstechnik-Verordnung (BITV 2.0)',
    href: 'https://www.gesetze-im-internet.de/bitv_2_0/',
    detail: 'Deutscher Rechtsrahmen für barrierefreie Informationstechnik öffentlicher Stellen des Bundes.',
    tags: ['recht', 'barrierefreiheit', 'web', 'softwareergonomie', 'wcag'],
  },
  {
    id: 'ausbildung-in-der-it-ap1',
    label: 'Ausbildung in der IT - AP Teil 1 der IT-Ausbildung',
    href: 'https://ausbildung-in-der-it.de/pruefung/teil-1-der-gestreckten-abschlusspruefung',
    detail: 'Sekundäre AP1-Orientierung zu Prüfungsform, Aufgabenformaten, typischen Themen und Vorbereitung. Als Prüfungsrealitäts- und Didaktikvergleich nutzen, nicht als alleinige Fachquelle.',
    tags: ['ap1', 'pruefung', 'pruefungsrealitaet', 'didaktik', 'aufgabenformat'],
  },
  {
    id: 'it-berufe-podcast-ap1-katalog-2025',
    label: 'IT-Berufe-Podcast #190 - Neuer AP1-Prüfungskatalog ab 2025',
    href: 'https://it-berufe-podcast.de/neuer-pruefungskatalog-fuer-die-ap1-der-it-berufe-ab-2025-it-berufe-podcast-190/',
    detail: 'Sekundärer Delta-Abgleich zum AP1-Prüfungskatalog ab 2025. Hinweise erst gegen offiziellen Katalog, FIAusbV, KMK, BIBB und Aufgabenmaterial absichern.',
    tags: ['ap1', 'pruefung', 'pruefungsrealitaet', 'pruefungskatalog', 'katalog2025'],
  },
  {
    id: 'it-berufe-podcast-ap1-themenliste',
    label: 'IT-Berufe-Podcast - Mögliche Themen Teil 1 der GAP',
    href: 'https://it-berufe-podcast.de/vorbereitung-auf-die-ihk-abschlusspruefung-der-it-berufe/moegliche-themen-von-teil-1-der-gestreckten-abschlusspruefung-gap-in-den-it-berufen/',
    detail: 'Breite AP1-Themenliste auf Basis des neuen Katalogstands und eigener Clusterung. Als Checkliste nutzen, nicht als Faktenanker.',
    tags: ['ap1', 'pruefung', 'pruefungsrealitaet', 'themenliste', 'katalog2025', 'didaktik'],
  },
  {
    id: 'smithsonian-edvac-first-draft',
    label: 'Smithsonian Libraries - John von Neumann: First Draft of a Report on the EDVAC',
    href: 'https://library.si.edu/digital-library/book/firstdraftofrepo00vonn',
    detail: 'Historische Primärquelle zur Stored-Program-Idee und zum EDVAC-Entwurf.',
    tags: ['ordnung', 'rechnerarchitektur', 'von-neumann', 'stored-program', 'edvac', 'speicher'],
  },
  {
    id: 'computer-history-museum-edvac',
    label: 'Computer History Museum - First Draft of Report on EDVAC published',
    href: 'https://www.computerhistory.org/tdih/june/30/',
    detail: 'Historische Einordnung des EDVAC-Reports und der Idee eines gemeinsamen Speichers für Instruktionen und Daten.',
    tags: ['ordnung', 'rechnerarchitektur', 'von-neumann', 'stored-program', 'edvac', 'speicher'],
  },
  {
    id: 'ibm-cpu-instruction-cycle',
    label: 'IBM - What is a Central Processing Unit (CPU)?',
    href: 'https://www.ibm.com/think/topics/central-processing-unit',
    detail: 'Einführung zu CPU, Control Unit und Instruction Cycle mit Fetch, Decode und Execute.',
    tags: ['ordnung', 'rechnerarchitektur', 'cpu', 'steuerwerk', 'instruction-cycle', 'fetch', 'decode', 'execute'],
  },
  {
    id: 'cornell-cpu-stages',
    label: 'Cornell CS 3410 - The 5 Classic CPU Stages',
    href: 'https://www.cs.cornell.edu/courses/cs3410/2025fa/notes/cpu_stages.html',
    detail: 'Lehrmaterial zu Fetch, Decode, Execute, Memory und Writeback als klassischem CPU-Stufenmodell.',
    tags: ['ordnung', 'rechnerarchitektur', 'cpu', 'alu', 'instruction-cycle', 'fetch', 'decode', 'execute', 'writeback', 'speicher'],
  },
  {
    id: 'intel-cpu-clock-speed',
    label: 'Intel - CPU Speed: What Is CPU Clock Speed?',
    href: 'https://www.intel.com/content/www/us/en/gaming/resources/cpu-clock-speed.html',
    detail: 'Herstellererklärung zu CPU-Takt, GHz, CPU-Zyklen und der Grenze von Taktfrequenz als alleinigem Leistungsvergleich.',
    tags: ['ordnung', 'hardware', 'cpu', 'taktfrequenz', 'ghz', 'kerne', 'cache', 'leistung'],
  },
  {
    id: 'microsoft-ssd-hdd-storage',
    label: 'Microsoft Support - All about SSD, HDD, and storage types',
    href: 'https://support.microsoft.com/en-us/windows/all-about-ssd-hdd-and-storage-types-9c6c7c59-7d1c-4611-9ba9-676d53cc0ff1',
    detail: 'Microsoft-Supportseite zu SSD, HDD, Kosten, Leistung und Speicherarten in PCs.',
    tags: ['ordnung', 'hardware', 'ssd', 'hdd', 'massenspeicher', 'speicher', 'storage'],
  },
  {
    id: 'nvmexpress-faq',
    label: 'NVM Express - NVMe FAQ',
    href: 'https://www.nvmexpress.org/wp-content/uploads/NVMe-FAQ.pdf',
    detail: 'Offizielle FAQ von NVM Express zu NVMe als für PCIe-basierte SSDs optimierter Schnittstellenspezifikation.',
    tags: ['ordnung', 'hardware', 'ssd', 'nvme', 'pcie', 'massenspeicher', 'speicher'],
  },
  {
    id: 'crucial-ddr-generations',
    label: 'Crucial - DDR memory generations explained',
    href: 'https://uk.crucial.com/content/crucial/en-gb/home/support/articles-faq-memory/difference-between-ddr4-ddr3-ddr2-ddr-sdram.html',
    detail: 'Herstellererklärung zu DDR-Generationen, Double Data Rate und fehlender Mischbarkeit verschiedener RAM-Generationen.',
    tags: ['ordnung', 'hardware', 'ram', 'ddr', 'ddr4', 'ddr5', 'arbeitsspeicher', 'kompatibilitaet'],
  },
  {
    id: 'hgb-rechtsformen',
    label: 'Handelsgesetzbuch - Kaufmann, OHG und KG',
    href: 'https://www.gesetze-im-internet.de/hgb/BJNR002190897.html',
    detail: 'Amtliche Grundlage für Kaufmannsbegriff sowie Begriff, Haftung, Geschäftsführung und Vertretung von OHG und KG.',
    tags: ['wirtschaft', 'recht', 'organisation', 'rechtsform', 'unternehmensform', 'einzelunternehmen', 'ohg', 'kg'],
  },
  {
    id: 'gmbhg-5-stammkapital',
    label: 'GmbHG Paragraf 5 - Stammkapital; Geschäftsanteil',
    href: 'https://www.gesetze-im-internet.de/gmbhg/__5.html',
    detail: 'Amtliche Grundlage für das Mindeststammkapital der GmbH von 25.000 Euro.',
    tags: ['wirtschaft', 'recht', 'rechtsform', 'gmbh', 'stammkapital', 'mindestkapital'],
  },
  {
    id: 'gmbhg-7-anmeldung',
    label: 'GmbHG Paragraf 7 - Anmeldung der Gesellschaft',
    href: 'https://www.gesetze-im-internet.de/gmbhg/__7.html',
    detail: 'Amtliche Grundlage für die bei einer Bargründung vor der Anmeldung erforderlichen Einzahlungen auf das Stammkapital.',
    tags: ['wirtschaft', 'recht', 'rechtsform', 'gmbh', 'stammkapital', 'einlage', 'anmeldung'],
  },
  {
    id: 'gmbhg-13-gmbh',
    label: 'GmbHG Paragraf 13 - Juristische Person; Handelsgesellschaft',
    href: 'https://www.gesetze-im-internet.de/gmbhg/__13.html',
    detail: 'Amtliche Grundlage zur GmbH mit eigener Rechtspersönlichkeit und Haftung mit Gesellschaftsvermögen.',
    tags: ['wirtschaft', 'recht', 'organisation', 'rechtsform', 'unternehmensform', 'gmbh'],
  },
  {
    id: 'gmbhg-35-vertretung',
    label: 'GmbHG Paragraf 35 - Vertretung der Gesellschaft',
    href: 'https://www.gesetze-im-internet.de/gmbhg/__35.html',
    detail: 'Amtliche Grundlage für die gerichtliche und außergerichtliche Vertretung der GmbH durch Geschäftsführer.',
    tags: ['wirtschaft', 'recht', 'rechtsform', 'gmbh', 'geschaeftsfuehrung', 'vertretung'],
  },
  {
    id: 'aktg-1-ag',
    label: 'AktG Paragraf 1 - Wesen der Aktiengesellschaft',
    href: 'https://www.gesetze-im-internet.de/aktg/__1.html',
    detail: 'Amtliche Grundlage zur Aktiengesellschaft mit eigener Rechtspersönlichkeit und in Aktien zerlegtem Grundkapital.',
    tags: ['wirtschaft', 'recht', 'organisation', 'rechtsform', 'unternehmensform', 'aktiengesellschaft', 'ag'],
  },
  {
    id: 'aktg-7-grundkapital',
    label: 'AktG Paragraf 7 - Mindestnennbetrag des Grundkapitals',
    href: 'https://www.gesetze-im-internet.de/aktg/__7.html',
    detail: 'Amtliche Grundlage für das Mindestgrundkapital der Aktiengesellschaft von 50.000 Euro.',
    tags: ['wirtschaft', 'recht', 'rechtsform', 'aktiengesellschaft', 'ag', 'grundkapital', 'mindestkapital'],
  },
  {
    id: 'aktg-76-vorstand',
    label: 'AktG Paragraf 76 - Leitung der Aktiengesellschaft',
    href: 'https://www.gesetze-im-internet.de/aktg/__76.html',
    detail: 'Amtliche Grundlage für die Leitung der Aktiengesellschaft durch den Vorstand in eigener Verantwortung.',
    tags: ['wirtschaft', 'recht', 'rechtsform', 'aktiengesellschaft', 'ag', 'vorstand', 'leitung'],
  },
  {
    id: 'aktg-111-aufsichtsrat',
    label: 'AktG Paragraf 111 - Aufgaben und Rechte des Aufsichtsrats',
    href: 'https://www.gesetze-im-internet.de/aktg/__111.html',
    detail: 'Amtliche Grundlage für die Überwachung der Geschäftsführung durch den Aufsichtsrat.',
    tags: ['wirtschaft', 'recht', 'rechtsform', 'aktiengesellschaft', 'ag', 'aufsichtsrat', 'kontrolle'],
  },
  {
    id: 'aktg-119-hauptversammlung',
    label: 'AktG Paragraf 119 - Rechte der Hauptversammlung',
    href: 'https://www.gesetze-im-internet.de/aktg/__119.html',
    detail: 'Amtliche Grundlage für die gesetzlich bestimmten Beschlussgegenstände der Hauptversammlung.',
    tags: ['wirtschaft', 'recht', 'rechtsform', 'aktiengesellschaft', 'ag', 'hauptversammlung', 'aktionaer'],
  },
  {
    id: 'ihk-karlsruhe-rechtsformwahl',
    label: 'IHK Karlsruhe - Wahl der Rechtsform und Registrierungspflichten',
    href: 'https://www.ihk.de/karlsruhe/fachthemen/recht/gesellschaftsrecht-handelsrecht/gesellschaftsrecht/wahl-der-rechtsform-und-registrierungspflichten-2459116',
    detail: 'Unabhängige Fachquelle zu Auswahlkriterien, Mindestkapital, Haftung und Registrierung wichtiger Rechtsformen.',
    tags: ['wirtschaft', 'recht', 'rechtsform', 'unternehmensform', 'einzelunternehmen', 'ohg', 'kg', 'gmbh', 'ag'],
  },
  {
    id: 'lksg-sorgfaltspflichten',
    label: 'Lieferkettensorgfaltspflichtengesetz',
    href: 'https://www.gesetze-im-internet.de/lksg/',
    detail: 'Amtliche Grundlage zu Anwendungsbereich, Risikomanagement und menschenrechtlichen sowie umweltbezogenen Sorgfaltspflichten.',
    tags: ['wirtschaft', 'recht', 'nachhaltigkeit', 'esg', 'lieferkette', 'governance'],
  },
  {
    id: 'eu-taxonomie-2020-852',
    label: 'Verordnung (EU) 2020/852 - EU-Taxonomie',
    href: 'https://eur-lex.europa.eu/eli/reg/2020/852/oj/eng',
    detail: 'Offizielle EU-Grundlage zu Umweltzielen und Kriterien für ökologisch nachhaltige wirtschaftliche Tätigkeiten.',
    tags: ['wirtschaft', 'nachhaltigkeit', 'esg', 'environmental', 'taxonomie', 'kreislaufwirtschaft'],
  },
  {
    id: 'eu-csrd-2022-2464',
    label: 'Richtlinie (EU) 2022/2464 - Corporate Sustainability Reporting Directive',
    href: 'https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX:32022L2464',
    detail: 'Offizielle EU-Grundlage zur Nachhaltigkeitsberichterstattung bestimmter Unternehmen.',
    tags: ['wirtschaft', 'nachhaltigkeit', 'esg', 'bericht', 'governance', 'csrd'],
  },
  {
    id: 'bundesregierung-sdgs',
    label: 'Bundesregierung - Die 17 globalen Nachhaltigkeitsziele',
    href: 'https://www.bundesregierung.de/breg-de/themen/nachhaltigkeitspolitik/nachhaltigkeitsziele-verstaendlich-erklaert-232174',
    detail: 'Offizielle Orientierung zu den Sustainable Development Goals der Agenda 2030.',
    tags: ['wirtschaft', 'nachhaltigkeit', 'sdg', 'esg'],
  },
  {
    id: 'bundesregierung-nachhaltigkeitsstrategie-2025',
    label: 'Bundesregierung – Deutsche Nachhaltigkeitsstrategie 2025',
    href: 'https://www.bundesregierung.de/resource/blob/975228/2335292/3962877378d74837d4f4c611749b6172/2025-05-13-dns-2025-data.pdf?download=1',
    detail: 'Offizielle Strategiequelle zum integrierten Zusammenspiel wirtschaftlicher, sozialer und ökologischer Nachhaltigkeitsdimensionen.',
    tags: ['wirtschaft', 'nachhaltigkeit', 'oekologisch', 'sozial', 'unternehmensziele', 'leitbild'],
  },
  {
    id: 'eu-public-procurement-lifecycle-costing',
    label: 'Richtlinie 2014/24/EU – Artikel 67 und 68 zur Lebenszykluskostenrechnung',
    href: 'https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32014L0024',
    detail: 'EU-Primärquelle zu überprüfbaren Beschaffungskriterien sowie Anschaffungs-, Nutzungs-, Wartungs-, Lebensende- und monetarisierbaren Umweltkosten.',
    tags: ['wirtschaft', 'beschaffung', 'lebenszyklus', 'lebenszykluskosten', 'tco', 'energie', 'wartung', 'recycling'],
  },
  {
    id: 'eu-environmental-footprint-2021-2279',
    label: 'Empfehlung (EU) 2021/2279 – Methoden für den Umweltfußabdruck',
    href: 'https://eur-lex.europa.eu/eli/reco/2021/2279/2021-12-30/eng',
    detail: 'Offizielle EU-Methodenquelle zu Lebenszyklus, funktionaler Einheit, Systemgrenze, vergleichbarer Funktion und transparenter Umweltkommunikation.',
    tags: ['nachhaltigkeit', 'lebenszyklus', 'funktionale-einheit', 'systemgrenze', 'umweltfussabdruck', 'vergleichbarkeit'],
  },
  {
    id: 'eu-espr-2024-1781',
    label: 'Verordnung (EU) 2024/1781 – Ökodesign für nachhaltige Produkte',
    href: 'https://eur-lex.europa.eu/eli/reg/2024/1781/2024-06-28/eng',
    detail: 'EU-Primärquelle für den Produktrahmen zu Haltbarkeit, Zuverlässigkeit, Reparierbarkeit, Aufrüstbarkeit, Wiederverwendung, Recycling sowie Energie- und Ressourceneffizienz.',
    tags: ['nachhaltigkeit', 'lebenszyklus', 'oekodesign', 'reparierbarkeit', 'aufruestung', 'kreislaufwirtschaft', 'ressourceneffizienz'],
  },
  {
    id: 'eu-waste-hierarchy',
    label: 'Richtlinie 2008/98/EG – Abfallhierarchie',
    href: 'https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02008L0098-20251016',
    detail: 'Konsolidierte EU-Primärquelle zur Rangfolge aus Vermeidung, Vorbereitung zur Wiederverwendung, Recycling, sonstiger Verwertung und Beseitigung.',
    tags: ['nachhaltigkeit', 'kreislaufwirtschaft', 'abfall', 'vermeidung', 'wiederverwendung', 'recycling', 'entsorgung'],
  },
  {
    id: 'eu-weee',
    label: 'Europäische Kommission – Elektro- und Elektronik-Altgeräte (WEEE)',
    href: 'https://environment.ec.europa.eu/topics/waste-and-recycling/waste-electrical-and-electronic-equipment-weee_en',
    detail: 'Offizielle Einordnung von Abfallvermeidung, Wiederverwendung, Recycling und Rückgewinnung wertvoller Sekundärrohstoffe bei Elektroaltgeräten.',
    tags: ['nachhaltigkeit', 'elektroaltgeraete', 'e-waste', 'wiederverwendung', 'recycling', 'ressourcen'],
  },
  {
    id: 'blauer-engel-computer-de-uz-78',
    label: 'Blauer Engel DE-UZ 78 – Computer, Tastaturen und Mäuse, Ausgabe Juli 2024',
    href: 'https://produktinfo.blauer-engel.de/uploads/criteriafile/de/232/DE-UZ%20078-202407-de%20Kriterien-V1.pdf',
    detail: 'Offizieller Kriterienkatalog mit Anforderungen unter anderem zu Langlebigkeit, Garantie, Reparatur, Ersatzteilen, Energie, sicherer Datenlöschung und sozialen Bedingungen.',
    tags: ['nachhaltigkeit', 'computer', 'umweltzeichen', 'reparierbarkeit', 'ersatzteile', 'energie', 'datenloeschung', 'lieferkette'],
  },
  {
    id: 'ec-corporate-sustainability-reporting',
    label: 'Europäische Kommission – aktueller Stand der Nachhaltigkeitsberichterstattung',
    href: 'https://finance.ec.europa.eu/financial-markets/company-reporting-and-auditing/company-reporting/corporate-sustainability-reporting_en',
    detail: 'Offizielle, fortgeschriebene Übersicht zu CSRD, ESRS, Umwelt-, Sozial- und Governance-Themen sowie laufenden Änderungen des Berichtsrahmens.',
    tags: ['nachhaltigkeit', 'esg', 'environmental', 'social', 'governance', 'csrd', 'esrs', 'bericht'],
  },
  {
    id: 'ustg-14-rechnungen',
    label: 'UStG Paragraf 14 - Ausstellung von Rechnungen',
    href: 'https://www.gesetze-im-internet.de/ustg_1980/__14.html',
    detail: 'Amtliche Grundlage für Rechnungsbegriff, E-Rechnung und Pflichtangaben.',
    tags: ['rechnung', 'e-rechnung', 'umsatzsteuer', 'pflichtangaben', 'wirtschaft', 'recht'],
  },
  {
    id: 'ustg-14b-aufbewahrung-rechnungen',
    label: 'UStG Paragraf 14b - Aufbewahrung von Rechnungen',
    href: 'https://www.gesetze-im-internet.de/ustg_1980/__14b.html',
    detail: 'Amtliche Grundlage für Aufbewahrung von Rechnungen, Fristbeginn und Sonderfälle.',
    tags: ['rechnung', 'aufbewahrung', 'aufbewahrungsfrist', 'buchungsbeleg', 'wirtschaft', 'recht'],
  },
  {
    id: 'ustdv-33-kleinbetragsrechnungen',
    label: 'UStDV Paragraf 33 - Rechnungen über Kleinbeträge',
    href: 'https://www.gesetze-im-internet.de/ustdv_1980/__33.html',
    detail: 'Vereinfachte Pflichtangaben für Kleinbetragsrechnungen bis 250 Euro.',
    tags: ['rechnung', 'kleinbetragsrechnung', 'pflichtangaben', 'umsatzsteuer', 'wirtschaft', 'recht'],
  },
  {
    id: 'ao-147-aufbewahrung',
    label: 'AO Paragraf 147 - Aufbewahrung von Unterlagen',
    href: 'https://www.gesetze-im-internet.de/ao_1977/__147.html',
    detail: 'Steuerliche Aufbewahrungsfristen für Bücher, Buchungsbelege und Geschäftsbriefe.',
    tags: ['aufbewahrung', 'aufbewahrungsfrist', 'buchungsbeleg', 'rechnung', 'wirtschaft', 'recht'],
  },
  {
    id: 'hgb-257-aufbewahrung',
    label: 'HGB Paragraf 257 - Aufbewahrung von Unterlagen',
    href: 'https://www.gesetze-im-internet.de/hgb/__257.html',
    detail: 'Handelsrechtliche Aufbewahrungsfristen für Kaufleute.',
    tags: ['aufbewahrung', 'aufbewahrungsfrist', 'buchungsbeleg', 'rechnung', 'wirtschaft', 'recht'],
  },
  {
    id: 'bgb-271-leistungszeit',
    label: 'BGB Paragraf 271 - Leistungszeit',
    href: 'https://www.gesetze-im-internet.de/bgb/__271.html',
    detail: 'Grundregel zur Fälligkeit, wenn keine Leistungszeit bestimmt ist.',
    tags: ['zahlungsziel', 'faelligkeit', 'zahlung', 'recht'],
  },
  {
    id: 'bgb-286-verzug',
    label: 'BGB Paragraf 286 - Verzug des Schuldners',
    href: 'https://www.gesetze-im-internet.de/bgb/__286.html',
    detail: 'Mahnung, kalendermässiger Termin und 30-Tage-Regel bei Entgeltforderungen.',
    tags: ['zahlungsziel', 'zahlungsverzug', 'mahnung', 'zahlung', 'recht'],
  },
  {
    id: 'bgb-288-verzugszinsen',
    label: 'BGB Paragraf 288 - Verzugszinsen und Verzugsschaden',
    href: 'https://www.gesetze-im-internet.de/bgb/__288.html',
    detail: 'Amtliche Grundlage für Verzugszinsen und 40-Euro-Pauschale im B2B-Verzug.',
    tags: ['zahlungsverzug', 'verzugszinsen', 'zahlung', 'recht'],
  },
  {
    id: 'bmf-e-rechnung-faq',
    label: 'BMF - FAQ zur verpflichtenden E-Rechnung ab 2025',
    href: 'https://www.bundesfinanzministerium.de/Content/DE/FAQ/e-rechnung.html',
    detail: 'Aktueller Stand zur E-Rechnung, sonstiger Rechnung, Ausnahmen und Übergangsregeln.',
    tags: ['rechnung', 'e-rechnung', 'umsatzsteuer', 'wirtschaft', 'recht'],
  },
  {
    id: 'gabler-nutzwertanalyse',
    label: 'Springer Gabler Wirtschaftslexikon - Nutzwertanalyse',
    href: 'https://wirtschaftslexikon.gabler.de/definition/nutzwertanalyse-42926',
    detail: 'Fachlexikon zur Bewertung von Alternativen mit gewichteten Kriterien und Nutzwerten.',
    tags: ['wirtschaft', 'angebot', 'angebotsvergleich', 'nutzwertanalyse', 'entscheidung'],
  },
  {
    id: 'gabler-make-or-buy',
    label: 'Springer Gabler Wirtschaftslexikon - Make or Buy',
    href: 'https://wirtschaftslexikon.gabler.de/definition/make-or-buy-38068',
    detail: 'Fachlexikon zur Entscheidung zwischen Eigenproduktion, Fremdbezug und vertikaler Integration.',
    tags: ['wirtschaft', 'entscheidung', 'make-or-buy', 'eigenfertigung', 'fremdbezug', 'transaktionskosten'],
  },
  {
    id: 'gabler-transaktionskosten',
    label: 'Springer Gabler Wirtschaftslexikon - Transaktionskosten',
    href: 'https://wirtschaftslexikon.gabler.de/definition/transaktionskosten-48987',
    detail: 'Fachlexikon zu Kosten der Anbahnung, Abwicklung und Koordination wirtschaftlicher Transaktionen.',
    tags: ['wirtschaft', 'entscheidung', 'make-or-buy', 'transaktionskosten'],
  },
  {
    id: 'ihk-pfalz-preisgestaltung-kalkulation',
    label: 'IHK Pfalz - Preisgestaltung und Kalkulation',
    href: 'https://www.ihk.de/pfalz/innovation-umwelt-und-existenzgruendung/unternehmensfuehrung/unternehmenssteuerung/preisgestaltung-kalkulation-1279088',
    detail: 'Kaufmännische Orientierung zu Preisbildung, Kalkulation und Angebotsrechnung.',
    tags: ['wirtschaft', 'angebot', 'angebotsvergleich', 'handelskalkulation', 'bezugspreis', 'kalkulation'],
  },
  {
    id: 'gabler-finanzierung',
    label: 'Springer Gabler Wirtschaftslexikon - Finanzierung',
    href: 'https://wirtschaftslexikon.gabler.de/definition/finanzierung-33079',
    detail: 'Fachlexikon zur Mittelbeschaffung, Innen- und Außenfinanzierung sowie Eigen- und Fremdfinanzierung.',
    tags: ['finanzierung', 'innenfinanzierung', 'aussenfinanzierung', 'eigenfinanzierung', 'fremdfinanzierung'],
  },
  {
    id: 'gabler-eigenfinanzierung',
    label: 'Springer Gabler Wirtschaftslexikon - Eigenfinanzierung',
    href: 'https://wirtschaftslexikon.gabler.de/definition/eigenfinanzierung-35656',
    detail: 'Fachlexikon zu Eigenfinanzierung als Beschaffung von Eigenkapital.',
    tags: ['finanzierung', 'eigenfinanzierung', 'eigenkapital'],
  },
  {
    id: 'gabler-fremdfinanzierung',
    label: 'Springer Gabler Wirtschaftslexikon - Fremdfinanzierung',
    href: 'https://wirtschaftslexikon.gabler.de/definition/fremdfinanzierung-35508',
    detail: 'Fachlexikon zu Fremdfinanzierung, Gläubigerstellung, Fristigkeit, Zins und Tilgung.',
    tags: ['finanzierung', 'fremdfinanzierung', 'fremdkapital', 'darlehen', 'kredit'],
  },
  {
    id: 'bgb-488-darlehensvertrag',
    label: 'BGB Paragraf 488 - Darlehensvertrag',
    href: 'https://www.gesetze-im-internet.de/bgb/__488.html',
    detail: 'Amtliche Grundlage für Bereitstellung eines Darlehens, Zinszahlung und Rückzahlung.',
    tags: ['finanzierung', 'darlehen', 'kredit', 'zins', 'tilgung'],
  },
  {
    id: 'hgb-247-bilanz',
    label: 'HGB Paragraf 247 - Inhalt der Bilanz',
    href: 'https://www.gesetze-im-internet.de/hgb/__247.html',
    detail: 'Amtliche Grundlage für den gesonderten Ausweis von Vermögen, Eigenkapital, Schulden und Rechnungsabgrenzung.',
    tags: ['finanzierung', 'bilanz', 'eigenkapital', 'fremdkapital'],
  },
  {
    id: 'hgb-266-bilanzgliederung',
    label: 'HGB Paragraf 266 - Gliederung der Bilanz',
    href: 'https://www.gesetze-im-internet.de/hgb/__266.html',
    detail: 'Amtliche Bilanzgliederung mit Eigenkapital, Rückstellungen und Verbindlichkeiten auf der Passivseite.',
    tags: ['finanzierung', 'bilanz', 'eigenkapital', 'fremdkapital'],
  },
  {
    id: 'bgb-433-kaufvertrag',
    label: 'BGB Paragraf 433 - Kaufvertrag',
    href: 'https://www.gesetze-im-internet.de/bgb/__433.html',
    detail: 'Amtliche Grundlage für Übergabe, Eigentumsverschaffung, Kaufpreiszahlung und Abnahme.',
    tags: ['wirtschaft', 'recht', 'vertragsrecht', 'vertragsarten', 'kaufvertrag', 'kauf', 'kauf-leasing-miete', 'gewaehrleistung'],
  },
  {
    id: 'bgb-434-sachmangel',
    label: 'BGB Paragraf 434 - Sachmangel',
    href: 'https://www.gesetze-im-internet.de/bgb/__434.html',
    detail: 'Amtliche Grundlage für subjektive, objektive und Montage-Anforderungen an eine mangelfreie Kaufsache.',
    tags: ['recht', 'vertragsrecht', 'gewaehrleistung', 'sachmangel', 'mangel'],
  },
  {
    id: 'bgb-437-maengelrechte',
    label: 'BGB Paragraf 437 - Rechte des Käufers bei Mängeln',
    href: 'https://www.gesetze-im-internet.de/bgb/__437.html',
    detail: 'Amtliche Grundlage für Nacherfuellung, Rücktritt, Minderung, Schadensersatz und Aufwendungsersatz bei Mängeln.',
    tags: ['recht', 'vertragsrecht', 'gewaehrleistung', 'maengelrechte', 'nacherfuellung', 'ruecktritt', 'minderung', 'schadensersatz'],
  },
  {
    id: 'bgb-438-verjaehrung-maengel',
    label: 'BGB Paragraf 438 - Verjährung der Mängelansprüche',
    href: 'https://www.gesetze-im-internet.de/bgb/__438.html',
    detail: 'Amtliche Grundlage für Verjährungsfristen kaufrechtlicher Mängelansprüche.',
    tags: ['recht', 'vertragsrecht', 'gewaehrleistung', 'verjaehrung', 'maengelrechte'],
  },
  {
    id: 'bgb-443-garantie',
    label: 'BGB Paragraf 443 - Garantie',
    href: 'https://www.gesetze-im-internet.de/bgb/__443.html',
    detail: 'Amtliche Grundlage für Garantieerklärungen und Rechte gegen den Garantiegeber.',
    tags: ['recht', 'vertragsrecht', 'gewaehrleistung', 'garantie'],
  },
  {
    id: 'bgb-477-beweislast',
    label: 'BGB Paragraf 477 - Beweislastumkehr',
    href: 'https://www.gesetze-im-internet.de/bgb/__477.html',
    detail: 'Amtliche Grundlage für die Vermutung im Verbrauchsgüterkauf, wenn sich ein mangelhafter Zustand innerhalb eines Jahres zeigt.',
    tags: ['recht', 'vertragsrecht', 'gewaehrleistung', 'verbrauchsgueterkauf', 'beweislast'],
  },
  {
    id: 'hgb-377-maengelruege',
    label: 'HGB Paragraf 377 - Untersuchungs- und Rügepflicht',
    href: 'https://www.gesetze-im-internet.de/hgb/__377.html',
    detail: 'Amtliche Grundlage für unverzügliche Untersuchung und Mängelrüge beim beidseitigen Handelskauf.',
    tags: ['recht', 'vertragsrecht', 'gewaehrleistung', 'maengelruege', 'handelskauf'],
  },
  {
    id: 'bgb-611-dienstvertrag',
    label: 'BGB Paragraf 611 - Dienstvertrag',
    href: 'https://www.gesetze-im-internet.de/bgb/__611.html',
    detail: 'Amtliche Grundlage für versprochene Dienste gegen Vergütung.',
    tags: ['recht', 'vertragsrecht', 'vertragsarten', 'dienstvertrag', 'dienstleistung'],
  },
  {
    id: 'bgb-631-werkvertrag',
    label: 'BGB Paragraf 631 - Werkvertrag',
    href: 'https://www.gesetze-im-internet.de/bgb/__631.html',
    detail: 'Amtliche Grundlage für Herstellung eines Werks oder herbeizuführenden Erfolgs gegen Vergütung.',
    tags: ['recht', 'vertragsrecht', 'vertragsarten', 'werkvertrag', 'erfolgspflicht'],
  },
  {
    id: 'bgb-640-abnahme',
    label: 'BGB Paragraf 640 - Abnahme',
    href: 'https://www.gesetze-im-internet.de/bgb/__640.html',
    detail: 'Amtliche Grundlage für die Abnahme eines vertragsgemäss hergestellten Werks.',
    tags: ['recht', 'vertragsrecht', 'vertragsarten', 'werkvertrag', 'abnahme'],
  },
  {
    id: 'bgb-641-verguetung-werkvertrag',
    label: 'BGB Paragraf 641 - Fälligkeit der Vergütung',
    href: 'https://www.gesetze-im-internet.de/bgb/__641.html',
    detail: 'Amtliche Grundlage zur Vergütung beim Werkvertrag im Zusammenhang mit der Abnahme.',
    tags: ['recht', 'vertragsrecht', 'vertragsarten', 'werkvertrag', 'abnahme', 'verguetung'],
  },
  {
    id: 'bgb-535-mietvertrag',
    label: 'BGB Paragraf 535 - Mietvertrag',
    href: 'https://www.gesetze-im-internet.de/bgb/__535.html',
    detail: 'Amtliche Grundlage der zeitweisen Gebrauchsüberlassung gegen Miete.',
    tags: ['wirtschaft', 'recht', 'miete', 'kauf-leasing-miete'],
  },
  {
    id: 'hgb-246-zurechnung',
    label: 'HGB Paragraf 246 - Wirtschaftliche Zurechnung',
    href: 'https://www.gesetze-im-internet.de/hgb/__246.html',
    detail: 'Bilanzierungsgrundsatz, nach dem Vermögensgegenstände beim wirtschaftlich Zurechenbaren auszuweisen sind.',
    tags: ['wirtschaft', 'recht', 'bilanz', 'leasing', 'kauf-leasing-miete'],
  },
  {
    id: 'hgb-255-anschaffungskosten',
    label: 'HGB Paragraf 255 - Anschaffungskosten',
    href: 'https://www.gesetze-im-internet.de/hgb/__255.html',
    detail: 'Definition der Anschaffungskosten als Grundlage für Kauf- und Aktivierungsfragen.',
    tags: ['wirtschaft', 'recht', 'bilanz', 'kauf', 'kauf-leasing-miete', 'angebot', 'bezugspreis', 'anschaffungskosten'],
  },
  {
    id: 'estg-7-afa',
    label: 'EStG Paragraf 7 - Absetzung für Abnutzung',
    href: 'https://www.gesetze-im-internet.de/estg/__7.html',
    detail: 'Amtliche Grundlage für lineare AfA bei Wirtschaftsgütern mit Nutzungsdauer über einem Jahr.',
    tags: ['wirtschaft', 'afa', 'abschreibung', 'kauf-leasing-miete'],
  },
  {
    id: 'bafin-finanzierungsleasing',
    label: 'BaFin - Merkblatt Finanzierungsleasing',
    href: 'https://www.bafin.de/SharedDocs/Veroeffentlichungen/DE/Merkblatt/mb_090119_tatbestand_finanzierungsleasing.html',
    detail: 'Abgrenzung von Finanzierungsleasing und Operate-Leasing aus aufsichtsrechtlicher Sicht.',
    tags: ['wirtschaft', 'recht', 'leasing', 'finance-leasing', 'operate-leasing', 'kauf-leasing-miete'],
  },
  {
    id: 'microsoft-processes-threads',
    label: 'Microsoft Learn - About Processes and Threads',
    href: 'https://learn.microsoft.com/en-us/windows/win32/procthread/about-processes-and-threads',
    detail: 'Offizielle Microsoft-Dokumentation zu Prozessressourcen, Threads, Thread-Kontext und preemptivem Multitasking.',
    tags: ['betriebssystem', 'prozess', 'thread', 'task', 'scheduler', 'multitasking'],
  },
  {
    id: 'microsoft-processes-threads-overview',
    label: 'Microsoft Learn - Processes and Threads',
    href: 'https://learn.microsoft.com/en-us/windows/win32/procthread/processes-and-threads',
    detail: 'Grunddefinitionen: Prozess als ausgeführtes Programm und Thread als Einheit für Prozessorzeit.',
    tags: ['betriebssystem', 'prozess', 'thread', 'task'],
  },
  {
    id: 'microsoft-scheduling-priorities',
    label: 'Microsoft Learn - Scheduling Priorities',
    href: 'https://learn.microsoft.com/en-us/windows/win32/procthread/scheduling-priorities',
    detail: 'Offizielle Beschreibung von Thread-Prioritäten, Zeitscheiben und Unterbrechung durch höhere Priorität.',
    tags: ['betriebssystem', 'scheduler', 'thread', 'prioritaet', 'multitasking'],
  },
  {
    id: 'linux-kernel-cfs',
    label: 'Linux Kernel Documentation - CFS Scheduler',
    href: 'https://docs.kernel.org/scheduler/sched-design-CFS.html',
    detail: 'Linux-Kernel-Dokumentation zum Scheduler und zur fairen Verteilung von CPU-Zeit auf Tasks.',
    tags: ['betriebssystem', 'linux', 'scheduler', 'task', 'prozess', 'thread'],
  },
  {
    id: 'microsoft-ad-ds-overview',
    label: 'Microsoft Learn - Active Directory Domain Services overview',
    href: 'https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/virtual-dc/active-directory-domain-services-overview',
    detail: 'Offizielle Beschreibung zentraler Verzeichnisdienste, Benutzer-, Computer-, Gruppen- und Rechteverwaltung.',
    tags: ['betriebssystem', 'zentral', 'dezentral', 'verzeichnisdienst', 'active-directory', 'benutzerverwaltung', 'client-server'],
  },
  {
    id: 'bsi-cloud-grundlagen',
    label: 'BSI - Cloud Computing Grundlagen',
    href: 'https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Informationen-und-Empfehlungen/Empfehlungen-nach-Angriffszielen/Cloud-Computing/Grundlagen/grundlagen.html',
    detail: 'BSI-Grundlagen zu Cloud Computing, gemeinsam genutzten Ressourcen, Skalierbarkeit, Elastizität und Selbstbedienung.',
    tags: ['cloud', 'zentral', 'dezentral', 'hybrid', 'betriebssystem', 'it-infrastruktur'],
  },
  {
    id: 'nist-sp-800-145',
    label: 'NIST SP 800-145 - The NIST Definition of Cloud Computing',
    href: 'https://www.nist.gov/publications/nist-definition-cloud-computing',
    detail: 'Standarddefinition von Cloud Computing mit wesentlichen Merkmalen, Service- und Bereitstellungsmodellen.',
    tags: ['cloud', 'iaas', 'paas', 'saas', 'hybrid', 'it-infrastruktur'],
  },
  {
    id: 'ieee-80211-working-group',
    label: 'IEEE 802.11 Working Group - About 802.11',
    href: 'https://www.ieee802.org/11/abt80211.html',
    detail: 'Offizielle Einordnung der IEEE-802.11-Arbeitsgruppe und des Standards für Wireless LAN MAC/PHY.',
    tags: ['wlan', 'wifi', 'wi-fi', '802.11', 'funknetz', 'access-point'],
  },
  {
    id: 'ieee-sa-p802-11',
    label: 'IEEE SA - P802.11',
    href: 'https://standards.ieee.org/802_11.html',
    detail: 'Offizielle IEEE-Seite zum 802.11-Standard für Wireless LAN.',
    tags: ['wlan', 'wifi', 'wi-fi', '802.11', 'standard'],
  },
  {
    id: 'ieee-80211ax-2021',
    label: 'IEEE SA - IEEE 802.11ax-2021',
    href: 'https://standards.ieee.org/ieee/802.11ax/7180/',
    detail: 'IEEE-Amendment für High-Efficiency-WLAN; Grundlage für 802.11ax, Wi-Fi 6 und Wi-Fi 6E.',
    tags: ['wlan', 'wifi', 'wi-fi', '802.11', '802.11ax', 'wifi-6', 'wifi-6e', 'effizienz', '6-ghz'],
  },
  {
    id: 'ieee-80211be-2024',
    label: 'IEEE SA - IEEE 802.11be-2024',
    href: 'https://standards.ieee.org/ieee/802.11be/7516/',
    detail: 'IEEE-Amendment für Extremely High Throughput; Grundlage für 802.11be, Wi-Fi 7, Multi-Link Operation und 2,4/5/6-GHz-Koexistenz.',
    tags: ['wlan', 'wifi', 'wi-fi', '802.11', '802.11be', 'wifi-7', 'eht', 'multi-link-operation', '6-ghz'],
  },
  {
    id: 'wifi-alliance-security',
    label: 'Wi-Fi Alliance - Wi-Fi security',
    href: 'https://www.wi-fi.org/discover-wi-fi/security',
    detail: 'Wi-Fi-Alliance-Informationen zu WPA3 und WLAN-Sicherheitsgenerationen.',
    tags: ['wlan', 'wifi', 'wi-fi', 'wpa2', 'wpa3', 'sicherheit'],
  },
  {
    id: 'bsi-wlan-lan-grundlagen',
    label: 'BSI - WLAN und LAN: was man wissen sollte',
    href: 'https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Router-WLAN-VPN/WLAN-LAN-was-man-wissen-sollte/wlan-lan-was-man-wissen-sollte_node.html',
    detail: 'BSI-Grundlagen zu WLAN, LAN und der Empfehlung, WPA2 oder WPA3 zu verwenden.',
    tags: ['wlan', 'lan', 'wpa2', 'wpa3', 'sicherheit'],
  },
  {
    id: 'bsi-wlan-sicherheitstipps',
    label: 'BSI - Sicherheitstipps im privaten und öffentlichen WLAN',
    href: 'https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Router-WLAN-VPN/Sicherheitstipps-fuer-privates-und-oeffentliches-WLAN/sicherheitstipps-fuer-privates-und-oeffentliches-wlan.html',
    detail: 'BSI-Empfehlungen zu Routerpasswörtern, sicherer Konfiguration und vorsichtiger Nutzung fremder WLANs.',
    tags: ['wlan', 'router', 'sicherheit', 'passwort', 'gastnetz'],
  },
  {
    id: 'bsi-router-wlan-vpn',
    label: 'BSI - Router und WLAN sicher einrichten',
    href: 'https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Router-WLAN-VPN/router-wlan-vpn.html',
    detail: 'BSI-Hinweise zum sicheren Betrieb von Routern als zentrale Schnittstelle zwischen Internet und Heimnetz.',
    tags: ['router', 'nat', 'port-forwarding', 'firewall', 'vpn', 'sicherheit', 'netzwerk'],
  },
  {
    id: 'microsoft-windows-wifi',
    label: 'Microsoft Support - Faster and more secure Wi-Fi in Windows',
    href: 'https://support.microsoft.com/en-us/windows/faster-and-more-secure-wi-fi-in-windows-26177a28-38ed-1a8e-7eca-66f24dc63f09',
    detail: 'Herstellerdokumentation zu Wi-Fi 6/6E, Wi-Fi 7, WPA3 und Windows-Unterstützung; nur als Praxis- und Kompatibilitätsvergleich nutzen.',
    tags: ['wlan', 'wifi', 'wi-fi', '802.11ax', '802.11be', 'wifi-6', 'wifi-6e', 'wifi-7', 'wpa3', 'windows'],
  },
  {
    id: 'bsi-firewall',
    label: 'BSI - Firewall - Schutz vor dem Angriff von außen',
    href: 'https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Virenschutz-Firewall/Firewall/firewall.html',
    detail: 'BSI-Grundlagen zur Aufgabe von Firewalls zwischen internem und externem Netz.',
    tags: ['firewall', 'sicherheit', 'netzwerk', 'port-forwarding', 'dmz'],
  },
  {
    id: 'bsi-net-1-1-netzarchitektur',
    label: 'BSI IT-Grundschutz - NET.1.1 Netzarchitektur und -design',
    href: 'https://it-grundschutzkompendium.de/net_netze_und_kommunikation/net.1.1_netzarchitektur_und_-design',
    detail: 'BSI-Grundschutz-Baustein zu Netztrennung in Zonen, DMZ, Außenanbindung und Absicherung von Zonenübergängen.',
    tags: ['firewall', 'dmz', 'netzsegmentierung', 'sicherheit', 'netzwerk', 'allowlist'],
  },
  {
    id: 'bsi-net-3-2-firewall',
    label: 'BSI IT-Grundschutz - NET.3.2 Firewall',
    href: 'https://it-grundschutzkompendium.de/net_netze_und_kommunikation/net.3.2_firewall',
    detail: 'BSI-Grundschutz-Baustein zu Firewalls als Kopplung IP-basierter Netze und zur Einschränkung erlaubter Kommunikation.',
    tags: ['firewall', 'dmz', 'paketfilter', 'application-layer-gateway', 'sicherheit', 'netzwerk'],
  },
  {
    id: 'bsi-vpn',
    label: 'BSI - Virtual Private Networks (VPNs)',
    href: 'https://www.bsi.bund.de/EN/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Router-WLAN-VPN/Virtual-Private-Networks-VPN/virtual-private-networks-vpn_node.html',
    detail: 'BSI-Erklärung zu VPNs und Hinweis, dass Port Forwarding für eigene VPN-/NAS-Lösungen risikobehaftet sein kann.',
    tags: ['vpn', 'router', 'port-forwarding', 'sicherheit', 'netzwerk'],
  },
  {
    id: 'gabler-mitarbeitermotivation',
    label: 'Springer Gabler Wirtschaftslexikon - Mitarbeitermotivation',
    href: 'https://wirtschaftslexikon.gabler.de/definition/mitarbeitermotivation-52003',
    detail: 'Fachlexikon zu Mitarbeitermotivation und Einflussfaktoren im Unternehmen.',
    tags: ['motivation', 'team', 'change', 'personal', 'kommunikation'],
  },
  {
    id: 'tuckman-jensen-teamphasen',
    label: 'Tuckman & Jensen - Stages of Small-Group Development Revisited',
    href: 'https://doi.org/10.1177/105960117700200404',
    detail: 'Wissenschaftliche Quelle für Forming, Storming, Norming, Performing und Adjourning.',
    tags: ['team', 'teamphasen', 'projekt', 'kommunikation'],
  },
  {
    id: 'gabler-change-management',
    label: 'Springer Gabler Wirtschaftslexikon - Change Management',
    href: 'https://wirtschaftslexikon.gabler.de/definition/change-management-28354',
    detail: 'Fachlexikon zu Zielen, Anlässen und Gestaltung organisatorischer Veränderungen.',
    tags: ['change', 'projekt', 'kommunikation', 'prozess'],
  },
  {
    id: 'iso-10015',
    label: 'ISO 10015:2019 - Quality management - Guidelines for competence management and people development',
    href: 'https://www.iso.org/standard/69459.html',
    detail: 'Internationale Norm mit Leitlinien zu Kompetenzmanagement und Entwicklung von Personen in Organisationen.',
    tags: ['schulung', 'kompetenz', 'qualitaet', 'personal', 'prozess'],
  },
  {
    id: 'gabler-crm',
    label: 'Springer Gabler Wirtschaftslexikon - Customer Relationship Management (CRM)',
    href: 'https://wirtschaftslexikon.gabler.de/definition/customer-relationship-management-crm-30809',
    detail: 'Fachlexikon zu CRM als strategischem Ansatz für Kundenlebenszyklus, Kundenprozesse und CRM-Software.',
    tags: ['unternehmenssoftware', 'crm', 'software', 'service'],
  },
  {
    id: 'gabler-erp-system',
    label: 'Springer Gabler Wirtschaftslexikon - Enterprise-Resource-Planning-System',
    href: 'https://wirtschaftslexikon.gabler.de/definition/enterprise-resource-planning-system-51587',
    detail: 'Fachlexikon zu ERP-Systemen mit Modulen, gemeinsamer Datenbasis und bereichsübergreifender Prozessunterstützung.',
    tags: ['unternehmenssoftware', 'erp', 'software'],
  },
  {
    id: 'gabler-dms',
    label: 'Springer Gabler Wirtschaftslexikon - Dokumentenmanagementsystem',
    href: 'https://wirtschaftslexikon.gabler.de/definition/dokumentenmanagementsystem-32496',
    detail: 'Fachlexikon zu DMS-Funktionen wie Mehrbenutzerzugriff, Rechteverwaltung, Verteilung, Klassifizierung und Suche.',
    tags: ['unternehmenssoftware', 'dms', 'software'],
  },
  {
    id: 'gabler-cms',
    label: 'Springer Gabler Wirtschaftslexikon - Content Management System (CMS)',
    href: 'https://wirtschaftslexikon.gabler.de/definition/content-management-system-cms-31303',
    detail: 'Fachlexikon zu CMS mit Redaktionssystem, Content Repository, Publishing und Trennung von Inhalt und Layout.',
    tags: ['unternehmenssoftware', 'cms', 'software', 'web'],
  },
  {
    id: 'bpb-markt',
    label: 'Bundeszentrale für politische Bildung - Markt',
    href: 'https://www.bpb.de/kurz-knapp/lexika/lexikon-der-wirtschaft/240374/markt/',
    detail: 'Grunddefinition des Marktes als nicht ortsgebundenes Zusammentreffen von Angebot und Nachfrage für bestimmte Güter.',
    tags: ['wirtschaft', 'markt', 'angebot', 'nachfrage', 'preisbildung'],
  },
  {
    id: 'bpb-preisbildung',
    label: 'Bundeszentrale für politische Bildung - Preisbildung',
    href: 'https://www.bpb.de/kurz-knapp/lexika/lexikon-der-wirtschaft/20309/preisbildung/',
    detail: 'Fachquelle zum vereinfachten Marktmodell mit Angebots- und Nachfragemenge, Gleichgewicht sowie Angebots- und Nachfrageüberhang.',
    tags: ['wirtschaft', 'markt', 'angebot', 'nachfrage', 'preisbildung', 'marktgleichgewicht'],
  },
  {
    id: 'bpb-marktformen',
    label: 'Bundeszentrale für politische Bildung - Marktformen',
    href: 'https://www.bpb.de/kurz-knapp/lexika/lexikon-der-wirtschaft/20075/marktformen/',
    detail: 'Fachquelle zur Einteilung von Märkten nach der Zahl der Anbieter und Nachfrager in Polypol, Oligopol und Monopol.',
    tags: ['wirtschaft', 'markt', 'marktform', 'polypol', 'oligopol', 'monopol'],
  },
  {
    id: 'bundeskartellamt-wettbewerb-verbraucher',
    label: 'Bundeskartellamt - Wettbewerbsschutz ist Verbraucherschutz',
    href: 'https://www.bundeskartellamt.de/DE/Verbraucherschutz/Wettbewerbsschutz_Verbraucher/Wettbewerbsschutz_Verbraucher_node.html',
    detail: 'Behördliche Einordnung der Wirkungen funktionsfähigen Wettbewerbs auf Preise, Auswahl, Qualität und Innovation.',
    tags: ['wirtschaft', 'markt', 'wettbewerb', 'verbraucherschutz', 'innovation', 'marktmacht'],
  },
  {
    id: 'gwb-18-marktbeherrschung',
    label: 'Gesetz gegen Wettbewerbsbeschränkungen (GWB) - § 18 Marktbeherrschung',
    href: 'https://www.gesetze-im-internet.de/gwb/__18.html',
    detail: 'Amtliche Kriterien zur Beurteilung von Marktbeherrschung; die bloße Anbieterzahl ist dafür nicht allein entscheidend.',
    tags: ['wirtschaft', 'recht', 'markt', 'wettbewerb', 'marktmacht', 'marktbeherrschung'],
  },
  {
    id: 'gabler-zielgruppe',
    label: 'Springer Gabler Wirtschaftslexikon - Zielgruppe',
    href: 'https://wirtschaftslexikon.gabler.de/definition/zielgruppe-48977',
    detail: 'Fachlexikon zur Zielgruppe als Menge tatsächlicher oder potenzieller Adressaten einer Marketingaktivität.',
    tags: ['wirtschaft', 'marketing', 'zielgruppe', 'marktsegmentierung'],
  },
  {
    id: 'gabler-marktsegmentierung',
    label: 'Springer Gabler Wirtschaftslexikon - Marktsegmentierung',
    href: 'https://wirtschaftslexikon.gabler.de/definition/marktsegmentierung-40268',
    detail: 'Fachlexikon zur Aufteilung eines Gesamtmarkts in intern ähnliche und untereinander unterscheidbare Käufergruppen.',
    tags: ['wirtschaft', 'marketing', 'zielgruppe', 'marktsegmentierung', 'kundennutzen'],
  },
  {
    id: 'gabler-kundennutzen',
    label: 'Springer Gabler Wirtschaftslexikon - Kundennutzen',
    href: 'https://wirtschaftslexikon.gabler.de/definition/kundennutzen-39021',
    detail: 'Fachlexikon zum Kundennutzen als Grad, in dem ein Angebot Bedürfnisse eines Kunden erfüllt.',
    tags: ['wirtschaft', 'marketing', 'kundennutzen', 'bedarf', 'zielgruppe'],
  },
  {
    id: 'gabler-aida-regel',
    label: 'Springer Gabler Wirtschaftslexikon - AIDA-Regel',
    href: 'https://wirtschaftslexikon.gabler.de/definition/aida-regel-29523',
    detail: 'Fachlexikon zur AIDA-Regel als bekanntem, inzwischen veraltetem linearem Werbewirkungsmodell, das nur als Checkliste taugt.',
    tags: ['wirtschaft', 'marketing', 'kommunikation', 'werbung', 'aida', 'werbewirkung'],
  },
  {
    id: 'schulz-von-thun-kommunikationsquadrat',
    label: 'Schulz von Thun Institut - Das Kommunikationsquadrat',
    href: 'https://www.schulz-von-thun.de/die-modelle/das-kommunikationsquadrat',
    detail: 'Primärnahe Erläuterung der vier Nachrichtenseiten Sachinhalt, Selbstkundgabe, Beziehungshinweis und Appell sowie der vier Schnäbel und vier Ohren.',
    tags: ['kommunikation', 'kommunikationsquadrat', 'vier-ohren', 'schulz-von-thun', 'feedback'],
  },
  {
    id: 'shannon-1948-communication',
    label: 'Claude E. Shannon - A Mathematical Theory of Communication (1948)',
    href: 'https://people.math.harvard.edu/~ctm/home/text/others/shannon/entropy/entropy.pdf',
    detail: 'Primärquelle zum technischen Übertragungsmodell mit Informationsquelle, Sender, Kanal, Störquelle, Empfänger und Ziel; semantische Bedeutung ist ausdrücklich nicht Gegenstand des Modells.',
    tags: ['kommunikation', 'sender-empfaenger', 'kanal', 'stoerung', 'information'],
  },
  {
    id: 'rogers-farson-active-listening',
    label: 'Carl R. Rogers und Richard E. Farson - Active Listening',
    href: 'https://wholebeinginstitute.com/wp-content/uploads/Rogers_Farson_Active-Listening.pdf',
    detail: 'Primärtext zum aktiven Zuhören als respektvolle Haltung und zum prüfbaren Erfassen der Perspektive des Gegenübers.',
    tags: ['kommunikation', 'aktives-zuhoeren', 'paraphrasieren', 'feedback', 'gespraech'],
  },
  {
    id: 'ccl-sbi-feedback',
    label: 'Center for Creative Leadership - Situation-Behavior-Impact (SBI)',
    href: 'https://www.ccl.org/articles/leading-effectively-articles/closing-the-gap-between-intent-vs-impact-sbii/',
    detail: 'Offizielle Erläuterung von Situation, beobachtbarem Verhalten und Auswirkung sowie der ergänzenden Frage nach der Absicht für einen zweiseitigen Feedbackdialog.',
    tags: ['kommunikation', 'feedback', 'sbi', 'ich-botschaft', 'gespraech'],
  },
  {
    id: 'ireb-cpre-foundation-3-3',
    label: 'IREB - CPRE Foundation Level Syllabus 3.3.0',
    href: 'https://cockpit-v1.ireb.org/media/pages/downloads/cpre-foundation-level-syllabus/f305d53dab-1775054523/cpre_foundationlevel_syllabus_en_v.3.3.0.pdf',
    detail: 'Fachstandardnaher Überblick zu Anforderungsquellen, Erhebungstechniken, Dokumentation, Konfliktlösung und Validierung im Requirements Engineering.',
    tags: ['bedarf', 'bedarfsanalyse', 'anforderung', 'requirements', 'interview', 'fragebogen', 'beobachtung', 'workshop'],
  },
  {
    id: 'w3c-accessible-presentations',
    label: 'W3C WAI - Making Events and Presentations Accessible',
    href: 'https://www.w3.org/WAI/teach-advocate/accessible-presentations/',
    detail: 'Offizieller WAI-Leitfaden zu zugänglicher Planung und Durchführung von Präsentationen, darunter Beschreiben visueller Informationen, klare Sprache, Verarbeitungspausen und hörbare Fragen.',
    tags: ['praesentation', 'kommunikation', 'barrierefreiheit', 'vortrag', 'medien', 'zielgruppe'],
  },
  {
    id: 'microsoft-powerpoint-accessibility',
    label: 'Microsoft Support - PowerPoint-Präsentationen barrierefrei gestalten',
    href: 'https://support.microsoft.com/en-us/accessibility/powerpoint/make-your-powerpoint-presentations-accessible-to-people-with-disabilities',
    detail: 'Herstellerdokumentation zu eindeutigen Folientiteln, Lesereihenfolge, Alternativtexten, Kontrast, Schrift, Untertiteln, zugänglichen Links und Barrierefreiheitsprüfung in PowerPoint.',
    tags: ['praesentation', 'powerpoint', 'barrierefreiheit', 'alternativtext', 'lesereihenfolge', 'kontrast'],
  },
  {
    id: 'urhg-51-zitate',
    label: 'Urheberrechtsgesetz - § 51 Zitate',
    href: 'https://www.gesetze-im-internet.de/urhg/__51.html',
    detail: 'Amtliche Rechtsquelle zur Nutzung veröffentlichter Werke für einen echten Zitatzweck in einem durch diesen Zweck gerechtfertigten Umfang.',
    tags: ['recht', 'urheberrecht', 'zitat', 'praesentation', 'quelle', 'medien'],
  },
  {
    id: 'urhg-63-quellenangabe',
    label: 'Urheberrechtsgesetz - § 63 Quellenangabe',
    href: 'https://www.gesetze-im-internet.de/urhg/__63.html',
    detail: 'Amtliche Rechtsquelle zu deutlichen Quellenangaben bei gesetzlich erlaubten Nutzungen, darunter Zitate nach § 51 UrhG.',
    tags: ['recht', 'urheberrecht', 'quellenangabe', 'zitat', 'praesentation', 'dokumentation'],
  },
  {
    id: 'creative-commons-attribution',
    label: 'Creative Commons - Recommended practices for attribution',
    href: 'https://wiki.creativecommons.org/wiki/Recommended_practices_for_attribution',
    detail: 'Offizielle Creative-Commons-Empfehlung zur Namensnennung mit Title, Author, Source und License (TASL) sowie zum Kennzeichnen von Bearbeitungen.',
    tags: ['urheberrecht', 'creative-commons', 'lizenz', 'quellenangabe', 'praesentation', 'medien'],
  },
  {
    id: 'gabler-werbewirkung',
    label: 'Springer Gabler Wirtschaftslexikon - Werbewirkung',
    href: 'https://wirtschaftslexikon.gabler.de/definition/werbewirkung-49647',
    detail: 'Fachlexikon zu psychischer und ökonomischer Werbewirkung sowie passenden Messgrössen.',
    tags: ['wirtschaft', 'marketing', 'kommunikation', 'werbung', 'werbewirkung'],
  },
  {
    id: 'bsi-grundschutz',
    label: 'BSI - IT-Grundschutz-Kompendium',
    href: 'https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/IT-Grundschutz/IT-Grundschutz-Kompendium/it-grundschutz-kompendium_node.html',
    detail: 'Praxisnaher Referenzrahmen für Informationssicherheit, Betrieb, Schutzbedarf und Maßnahmen.',
    tags: ['sicherheit', 'backup', 'firewall', 'dmz', 'passwort', 'krypto', 'verfuegbarkeit'],
  },
  {
    id: 'bsi-kryptografie',
    label: 'BSI - Kryptografie',
    href: 'https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Informationen-und-Empfehlungen/Kryptografie/kryptografie_node.html',
    detail: 'BSI-Einstieg zu kryptografischen Verfahren, Schutzzielen und sicheren Mechanismen.',
    tags: ['sicherheit', 'krypto', 'verschluesselung', 'hashing', 'passwort'],
  },
  {
    id: 'bsi-tr-02102-1',
    label: 'BSI TR-02102-1 - Kryptografische Verfahren',
    href: 'https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TG02102/BSI-TR-02102-1.html',
    detail: 'Technische Richtlinie des BSI zu kryptografischen Mechanismen, Empfehlungen und Schlüssellängen.',
    tags: ['sicherheit', 'krypto', 'verschluesselung', 'hashing', 'signatur'],
  },
  {
    id: 'rfc-8446',
    label: 'RFC 8446 - TLS 1.3',
    href: 'https://www.rfc-editor.org/rfc/rfc8446',
    detail: 'IETF-Standard für Transport Layer Security, Grundlage für HTTPS und viele TLS-basierte VPNs.',
    tags: ['sicherheit', 'krypto', 'tls', 'zertifikat', 'verschluesselung', 'netzwerk', 'osi'],
  },
  {
    id: 'rfc-5280',
    label: 'RFC 5280 - X.509 PKI Certificate and CRL Profile',
    href: 'https://www.rfc-editor.org/rfc/rfc5280',
    detail: 'IETF-Profil für X.509-Zertifikate, Zertifikatsketten, Widerrufslisten und Pfadprüfung.',
    tags: ['sicherheit', 'krypto', 'zertifikat', 'pki', 'signatur'],
  },
  {
    id: 'rfc-6960',
    label: 'RFC 6960 - X.509 Internet Public Key Infrastructure Online Certificate Status Protocol',
    href: 'https://www.rfc-editor.org/rfc/rfc6960',
    detail: 'IETF-Standard zu OCSP als Online-Abfrage für den Widerrufsstatus einzelner Zertifikate.',
    tags: ['sicherheit', 'krypto', 'zertifikat', 'pki', 'ocsp', 'widerruf'],
  },
  {
    id: 'rfc-4301',
    label: 'RFC 4301 - IPsec Security Architecture',
    href: 'https://www.rfc-editor.org/rfc/rfc4301',
    detail: 'IETF-Standard zur Absicherung von IP-Verkehr, Security Associations, AH/ESP und IPsec-VPNs.',
    tags: ['sicherheit', 'krypto', 'vpn', 'ipsec', 'netzwerk'],
  },
  {
    id: 'rfc-9106',
    label: 'RFC 9106 - Argon2 Password Hashing',
    href: 'https://www.rfc-editor.org/rfc/rfc9106',
    detail: 'IRTF-RFC zu Argon2 als speicherhartes Passwort-Hashverfahren.',
    tags: ['sicherheit', 'krypto', 'hashing', 'passwort'],
  },
  {
    id: 'bsi-passwoerter',
    label: 'BSI - Umgang mit Passwörtern',
    href: 'https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Accountschutz/Sichere-Passwoerter-erstellen/Umgang-mit-Passwoertern/umgang-mit-passwoertern_node.html',
    detail: 'Empfehlungen zu Passwortschutz, Passwort-Managern und sicherem Umgang mit Zugangsdaten.',
    tags: ['sicherheit', 'passwort', 'hashing'],
  },
  {
    id: 'itu-x200-osi-basic-model',
    label: 'ITU-T X.200 - OSI Basic Reference Model',
    href: 'https://www.itu.int/rec/T-REC-X.200/',
    detail: 'Normative Referenz zum OSI-Basisreferenzmodell; identischer Text zu ISO/IEC 7498-1.',
    tags: ['netzwerk', 'osi', 'referenzmodell', 'schichtenmodell'],
  },
  {
    id: 'iso-7498-1',
    label: 'ISO/IEC 7498-1:1994 - OSI Basic Reference Model',
    href: 'https://www.iso.org/standard/20269.html',
    detail: 'ISO/IEC-Norm zum OSI-Basisreferenzmodell und den sieben Schichten.',
    tags: ['netzwerk', 'osi', 'referenzmodell', 'schichtenmodell'],
  },
  {
    id: 'rfc-1122',
    label: 'RFC 1122 - Requirements for Internet Hosts: Communication Layers',
    href: 'https://www.rfc-editor.org/rfc/rfc1122',
    detail: 'Internet-Host-Anforderungen zu Link-, Internet- und Transport-Schicht sowie zur Einordnung des TCP/IP-Stapels.',
    tags: ['netzwerk', 'tcp-ip', 'osi', 'internet', 'link-layer', 'transport'],
  },
  {
    id: 'rfc-791',
    label: 'RFC 791 - Internet Protocol (IPv4)',
    href: 'https://www.rfc-editor.org/rfc/rfc791',
    detail: 'Originalspezifikation von IPv4; hilfreich für Paketaufbau, Adressierung und Grundlagen.',
    tags: ['netzwerk', 'ipv4', 'subnetting', 'osi'],
  },
  {
    id: 'rfc-1918',
    label: 'RFC 1918 - Address Allocation for Private Internets',
    href: 'https://www.rfc-editor.org/rfc/rfc1918',
    detail: 'Offizielle Grundlage für private IPv4-Adressbereiche wie 10.0.0.0/8, 172.16.0.0/12 und 192.168.0.0/16.',
    tags: ['netzwerk', 'ipv4', 'subnetting', 'private-adressen', 'nat', 'port-forwarding'],
  },
  {
    id: 'rfc-2663',
    label: 'RFC 2663 - IP Network Address Translator Terminology',
    href: 'https://www.rfc-editor.org/rfc/rfc2663',
    detail: 'IETF-RFC zu NAT-Begriffen, Adressräumen, Basic NAT und NAPT.',
    tags: ['netzwerk', 'ipv4', 'nat', 'napt', 'pat', 'port-forwarding'],
  },
  {
    id: 'rfc-3022',
    label: 'RFC 3022 - Traditional IP Network Address Translator',
    href: 'https://www.rfc-editor.org/rfc/rfc3022',
    detail: 'IETF-RFC zu Traditional NAT, NAPT, Adress- und Portübersetzung sowie Grenzen von NAT.',
    tags: ['netzwerk', 'ipv4', 'nat', 'napt', 'pat', 'port-forwarding'],
  },
  {
    id: 'rfc-5737',
    label: 'RFC 5737 - IPv4 Address Blocks Reserved for Documentation',
    href: 'https://www.rfc-editor.org/rfc/rfc5737',
    detail: 'IETF-RFC zu den IPv4-Beispielnetzen 192.0.2.0/24, 198.51.100.0/24 und 203.0.113.0/24 für Dokumentation.',
    tags: ['netzwerk', 'ipv4', 'dokumentation', 'beispieladresse', 'port-forwarding'],
  },
  {
    id: 'rfc-6333',
    label: 'RFC 6333 - Dual-Stack Lite Broadband Deployments',
    href: 'https://www.rfc-editor.org/rfc/rfc6333',
    detail: 'IETF-RFC zu DS-Lite, IPv4-in-IPv6-Tunneln und providerseitiger NAT-Infrastruktur nach IPv4-Adressknappheit.',
    tags: ['netzwerk', 'ipv4', 'ipv6', 'nat', 'ds-lite', 'cgnat', 'port-forwarding'],
  },
  {
    id: 'rfc-6888',
    label: 'RFC 6888 - Common Requirements for Carrier-Grade NATs',
    href: 'https://www.rfc-editor.org/rfc/rfc6888',
    detail: 'Best Current Practice zu Carrier-Grade NAT als NAT-Funktion im Provider-Netz, bei der mehrere Kunden IPv4-Adressen teilen können.',
    tags: ['netzwerk', 'ipv4', 'nat', 'cgnat', 'carrier-grade-nat', 'port-forwarding'],
  },
  {
    id: 'rfc-4632',
    label: 'RFC 4632 - Classless Inter-domain Routing (CIDR)',
    href: 'https://www.rfc-editor.org/rfc/rfc4632',
    detail: 'Best Current Practice zu CIDR, Präfixnotation und classless IPv4-Adressierung.',
    tags: ['netzwerk', 'ipv4', 'subnetting', 'cidr'],
  },
  {
    id: 'rfc-3021',
    label: 'RFC 3021 - 31-Bit Prefixes on IPv4 Point-to-Point Links',
    href: 'https://www.rfc-editor.org/rfc/rfc3021',
    detail: 'Spezialfall für /31-Netze auf Punkt-zu-Punkt-Verbindungen.',
    tags: ['netzwerk', 'ipv4', 'subnetting', 'cidr'],
  },
  {
    id: 'iana-ipv4-special-registry',
    label: 'IANA - IPv4 Special-Purpose Address Space',
    href: 'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    detail: 'Offizielles Register für besondere IPv4-Adressbereiche wie Private-Use, Loopback und Link Local.',
    tags: ['netzwerk', 'ipv4', 'subnetting', 'special-purpose'],
  },
  {
    id: 'rfc-2131',
    label: 'RFC 2131 - Dynamic Host Configuration Protocol',
    href: 'https://www.rfc-editor.org/rfc/rfc2131',
    detail: 'DHCP-Spezifikation zu Client-/Server-Ablauf, Discover/Offer/Request/Ack, Lease-Verwaltung und Optionen.',
    tags: ['netzwerk', 'dhcp', 'ipv4', 'udp', 'netzwerkkonfiguration'],
  },
  {
    id: 'rfc-2132',
    label: 'RFC 2132 - DHCP Options and BOOTP Vendor Extensions',
    href: 'https://www.rfc-editor.org/rfc/rfc2132',
    detail: 'DHCP-Optionen für Subnetzmaske, Router, DNS-Server, Domainname, Lease-Dauer sowie T1/T2.',
    tags: ['netzwerk', 'dhcp', 'ipv4', 'netzwerkkonfiguration'],
  },
  {
    id: 'microsoft-ipconfig',
    label: 'Microsoft Learn - ipconfig',
    href: 'https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/ipconfig',
    detail: 'Offizielle Windows-Dokumentation zur Anzeige von IPv4-/IPv6-, DHCP- und DNS-Konfigurationen.',
    tags: ['netzwerk', 'windows', 'diagnose', 'dhcp', 'dns'],
  },
  {
    id: 'microsoft-ping',
    label: 'Microsoft Learn - ping',
    href: 'https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/ping',
    detail: 'Offizielle Windows-Dokumentation zu ICMP-Echo, Namensprüfung und der Meldung Request timed out.',
    tags: ['netzwerk', 'windows', 'diagnose', 'icmp'],
  },
  {
    id: 'microsoft-tracert',
    label: 'Microsoft Learn - TRACERT troubleshooting',
    href: 'https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/trace-route-troubleshoot-tcp-ip-problems',
    detail: 'Offizielle Einordnung antwortender Hops, Time-Exceeded-Meldungen und nicht antwortender Router.',
    tags: ['netzwerk', 'windows', 'diagnose', 'routing'],
  },
  {
    id: 'microsoft-dns-troubleshooting',
    label: 'Microsoft Learn - Troubleshooting DNS Servers',
    href: 'https://learn.microsoft.com/en-us/windows-server/networking/dns/troubleshoot/troubleshoot-dns-server',
    detail: 'Offizielle Diagnosehinweise zu DNS-Timeouts, Resolverantworten und Port 53 über UDP/TCP.',
    tags: ['netzwerk', 'windows', 'diagnose', 'dns'],
  },
  {
    id: 'rfc-1034',
    label: 'RFC 1034 - Domain Names: Concepts and Facilities',
    href: 'https://www.rfc-editor.org/rfc/rfc1034',
    detail: 'Grundlagen des Domain Name Systems: Namensraum, Resolver, Caching, rekursive und iterative Auflösung.',
    tags: ['netzwerk', 'dns', 'namensaufloesung', 'netzwerkkonfiguration'],
  },
  {
    id: 'rfc-1035',
    label: 'RFC 1035 - Domain Names: Implementation and Specification',
    href: 'https://www.rfc-editor.org/rfc/rfc1035',
    detail: 'DNS-Spezifikation zu Nachrichtenformat, Resource Records, TTL und Standardport 53.',
    tags: ['netzwerk', 'dns', 'ttl', 'port', 'netzwerkkonfiguration'],
  },
  {
    id: 'rfc-7766',
    label: 'RFC 7766 - DNS Transport over TCP',
    href: 'https://www.rfc-editor.org/rfc/rfc7766',
    detail: 'IETF-Standard zu DNS über TCP; allgemeine DNS-Implementierungen müssen UDP und TCP unterstützen.',
    tags: ['netzwerk', 'dns', 'tcp', 'udp', 'port', 'netzwerkkonfiguration'],
  },
  {
    id: 'rfc-826',
    label: 'RFC 826 - Ethernet Address Resolution Protocol',
    href: 'https://www.rfc-editor.org/rfc/rfc826',
    detail: 'ARP-Grundlage für die Auflösung von IPv4-Adressen in MAC-Adressen im lokalen Netz.',
    tags: ['netzwerk', 'arp', 'mac-adresse', 'ipv4', 'netzwerkkonfiguration'],
  },
  {
    id: 'rfc-3927',
    label: 'RFC 3927 - Dynamic Configuration of IPv4 Link-Local Addresses',
    href: 'https://www.rfc-editor.org/rfc/rfc3927',
    detail: 'IPv4-Link-Local-Adressen im Bereich 169.254.0.0/16, Konfliktprüfung per ARP und Grenzen der Routbarkeit.',
    tags: ['netzwerk', 'ipv4', 'apipa', 'link-local', 'netzwerkkonfiguration'],
  },
  {
    id: 'rfc-8200',
    label: 'RFC 8200 - Internet Protocol Version 6 (IPv6)',
    href: 'https://www.rfc-editor.org/rfc/rfc8200',
    detail: 'Aktuelle Standards-Track-Spezifikation für IPv6.',
    tags: ['netzwerk', 'ipv6', 'osi'],
  },
  {
    id: 'rfc-4291',
    label: 'RFC 4291 - IP Version 6 Addressing Architecture',
    href: 'https://www.rfc-editor.org/rfc/rfc4291',
    detail: 'IPv6-Adressarchitektur mit Adressformat, Unicast, Link-Local, Multicast, Loopback und Modified EUI-64.',
    tags: ['netzwerk', 'ipv6', 'adressierung', 'link-local', 'multicast', 'eui-64'],
  },
  {
    id: 'rfc-5952',
    label: 'RFC 5952 - IPv6 Address Text Representation',
    href: 'https://www.rfc-editor.org/rfc/rfc5952',
    detail: 'Empfohlene kanonische Textdarstellung von IPv6-Adressen: Kleinschreibung, führende Nullen entfernen und eindeutige ::-Kürzung.',
    tags: ['netzwerk', 'ipv6', 'adressierung', 'hex', 'textdarstellung'],
  },
  {
    id: 'rfc-4862',
    label: 'RFC 4862 - IPv6 Stateless Address Autoconfiguration',
    href: 'https://www.rfc-editor.org/rfc/rfc4862',
    detail: 'SLAAC-Spezifikation zur automatischen IPv6-Adressbildung durch Hosts auf Basis von Router Advertisements.',
    tags: ['netzwerk', 'ipv6', 'slaac', 'autokonfiguration', 'router-advertisement'],
  },
  {
    id: 'rfc-8981',
    label: 'RFC 8981 - Temporary Address Extensions for SLAAC',
    href: 'https://www.rfc-editor.org/rfc/rfc8981',
    detail: 'Temporäre IPv6-Adressen für SLAAC, um langfristige Wiedererkennbarkeit von Interfaces zu erschweren.',
    tags: ['netzwerk', 'ipv6', 'slaac', 'privacy', 'interface-identifier'],
  },
  {
    id: 'rfc-7217',
    label: 'RFC 7217 - Stable and Opaque Interface Identifiers',
    href: 'https://www.rfc-editor.org/rfc/rfc7217',
    detail: 'Verfahren für stabile, aber nicht direkt aus der MAC-Adresse ableitbare IPv6-Interface-Identifier.',
    tags: ['netzwerk', 'ipv6', 'slaac', 'privacy', 'interface-identifier'],
  },
  {
    id: 'rfc-4193',
    label: 'RFC 4193 - Unique Local IPv6 Unicast Addresses',
    href: 'https://www.rfc-editor.org/rfc/rfc4193',
    detail: 'Unique Local IPv6 Unicast Addresses im Bereich fc00::/7 für interne Adressierung.',
    tags: ['netzwerk', 'ipv6', 'unique-local', 'ula', 'adressierung'],
  },
  {
    id: 'rfc-3849',
    label: 'RFC 3849 - IPv6 Address Prefix Reserved for Documentation',
    href: 'https://www.rfc-editor.org/rfc/rfc3849',
    detail: 'Reserviert 2001:db8::/32 als IPv6-Dokumentationspräfix für Beispiele.',
    tags: ['netzwerk', 'ipv6', 'dokumentation', 'beispieladresse'],
  },
  {
    id: 'rfc-9293',
    label: 'RFC 9293 - Transmission Control Protocol (TCP)',
    href: 'https://www.rfc-editor.org/rfc/rfc9293',
    detail: 'Aktuelle TCP-Spezifikation; Grundlage für Ports, Verbindungen, Segmente und Zuverlässigkeit.',
    tags: ['netzwerk', 'tcp', 'osi'],
  },
  {
    id: 'rfc-768',
    label: 'RFC 768 - User Datagram Protocol (UDP)',
    href: 'https://www.rfc-editor.org/rfc/rfc768',
    detail: 'UDP-Spezifikation für verbindungslose Transportkommunikation.',
    tags: ['netzwerk', 'udp', 'osi'],
  },
  {
    id: 'iana-service-port-registry',
    label: 'IANA - Service Name and Transport Protocol Port Number Registry',
    href: 'https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml',
    detail: 'Offizielles Register für Service-Namen, Portnummern und Transportprotokolle.',
    tags: ['netzwerk', 'tcp', 'udp', 'port', 'dienst'],
  },
  {
    id: 'rfc-6335',
    label: 'RFC 6335 - Service Name and Transport Protocol Port Number Registry',
    href: 'https://www.rfc-editor.org/rfc/rfc6335',
    detail: 'IANA-Verfahren und Portbereiche: System/Well Known 0-1023, User/Registered 1024-49151 und Dynamic/Private 49152-65535.',
    tags: ['netzwerk', 'tcp', 'udp', 'port', 'dienst', 'iana'],
  },
  {
    id: 'rfc-9110',
    label: 'RFC 9110 - HTTP Semantics',
    href: 'https://www.rfc-editor.org/rfc/rfc9110',
    detail: 'Aktuelle HTTP-Semantik als Beispiel für ein Anwendungsprotokoll oberhalb der Transportschicht.',
    tags: ['netzwerk', 'http', 'web', 'tcp'],
  },
  {
    id: 'postgres-docs',
    label: 'PostgreSQL Documentation - SQL',
    href: 'https://www.postgresql.org/docs/current/sql.html',
    detail: 'Seriöse SQL-Referenz für Abfragen, Joins, Datendefinition und Datenmanipulation.',
    tags: ['datenbank', 'sql', 'normalisierung', 'er'],
  },
  {
    id: 'sqlite-lang',
    label: 'SQLite Documentation - SQL Language',
    href: 'https://www.sqlite.org/lang.html',
    detail: 'Kompakte SQL-Referenz mit Syntaxbeispielen für Lern- und Prüfungsaufgaben.',
    tags: ['datenbank', 'sql'],
  },
  {
    id: 'scrum-guide',
    label: 'The Scrum Guide (2020)',
    href: 'https://scrumguides.org/scrum-guide.html',
    detail: 'Primärquelle für Scrum: Accountabilities, fünf Events, drei Artefakte mit Commitments (Product Goal, Sprint Goal, Definition of Done). Ken Schwaber und Jeff Sutherland, November 2020.',
    tags: ['projekt', 'scrum', 'agil', 'sprint', 'backlog', 'increment', 'product-goal', 'sprint-goal', 'definition-of-done'],
  },
  {
    id: 'scrum-guide-revisions',
    label: 'Scrum Guide - Revisionen 2017 → 2020',
    href: 'https://scrumguides.org/revisions.html',
    detail: 'Offizielle Änderungsliste: Rollen heißen jetzt Accountabilities, eine Scrum-Team-Struktur ohne separates Development Team, Product Goal eingeführt, Commitments pro Artefakt, Warum als drittes Sprint-Planning-Thema.',
    tags: ['projekt', 'scrum', 'agil', 'accountabilities'],
  },
  {
    id: 'mountain-goat-scrum-2020',
    label: 'Mountain Goat Software - Top 5 Changes in the 2020 Scrum Guide',
    href: 'https://www.mountaingoatsoftware.com/blog/top-5-changes-in-the-2020-version-of-the-scrum-guide',
    detail: 'Kommentierter Vergleich der 2017er- und 2020er-Fassung mit didaktischer Einordnung von Mike Cohn und Brian Milner.',
    tags: ['projekt', 'scrum', 'agil', 'accountabilities'],
  },
  {
    id: 'royce-1970-waterfall',
    label: 'Royce 1970 - Managing the Development of Large Software Systems',
    href: 'https://www.cs.huji.ac.il/w~feit/sem/se09/Waterfall.pdf',
    detail: 'Winston W. Royce, Proceedings of IEEE WESCON 1970, S. 328-388. Quelle, in der das später „Wasserfall" genannte Phasenmodell erstmals beschrieben wird — von Royce ausdrücklich als „risky and invites failure" bezeichnet, mit Vorschlag für iteratives Vorgehen.',
    tags: ['projekt', 'wasserfall', 'lebenszyklus', 'historisch'],
  },
  {
    id: 'v-modell-xt-bund',
    label: 'V-Modell XT - CIO Bund',
    href: 'https://www.cio.bund.de/Webs/CIO/DE/digitaler-wandel/Achitekturen_und_Standards/V_modell_xt/v_modell_xt-artikel.html',
    detail: 'Offizielle Bundes-Referenz zum V-Modell XT (aktuelle Version 2.4) sowie zur Bund-Variante V-Modell XT Bund: Vorgehensmodell für IT-Projekte der öffentlichen Verwaltung, mit V-förmiger Verzahnung von Konstruktions- und Prüfphasen.',
    tags: ['projekt', 'v-modell', 'v-modell-xt', 'oeffentliche-verwaltung', 'lebenszyklus'],
  },
  {
    id: 'agile-manifesto',
    label: 'Manifesto for Agile Software Development (2001)',
    href: 'https://agilemanifesto.org/',
    detail: 'Originaltext des Agilen Manifests von 2001 mit den vier Wertepaaren („Individün und Interaktionen mehr als Prozesse und Werkzeuge" usw.) sowie 12 Prinzipien. Unterzeichnet von 17 Autoren, darunter Kent Beck, Martin Fowler, Ken Schwaber und Jeff Sutherland.',
    tags: ['projekt', 'agil', 'manifest', 'werte'],
  },
  {
    id: 'axelos-itil-reader',
    label: 'AXELOS - ITIL 4 Practice Guide Reader Manual',
    href: 'https://www.axelos.com/resource-hub/practice/readers-manual-itil-4-practice-guide',
    detail: 'Offizielle Orientierung zu ITIL-Practices, Prozessen, Incident Management und Service Level Management.',
    tags: ['service', 'incident', 'support', 'sla', 'prozess'],
  },
  {
    id: 'axelos-service-desk',
    label: 'AXELOS - ITIL 4 Practitioner: Service Desk',
    href: 'https://www.axelos.com/certifications/itil-service-management/itil-practices-manager/itil-4-specialist-monitor-support-and-fulfil/itil-4-practitioner-service-desk',
    detail: 'Service Desk als zentraler Kontaktpunkt zwischen Service Provider und Nutzern.',
    tags: ['service', 'support', 'service-desk'],
  },
  {
    id: 'axelos-incident-management',
    label: 'AXELOS - ITIL 4 Practitioner: Incident Management',
    href: 'https://www.axelos.com/certifications/itil-service-management/itil-practices-manager/itil-4-specialist-monitor-support-and-fulfil/itil-4-practitioner-incident-management',
    detail: 'Incident Management mit Fokus auf schnelle Wiederherstellung des normalen Servicebetriebs.',
    tags: ['service', 'incident', 'support'],
  },
  {
    id: 'axelos-service-request',
    label: 'AXELOS - ITIL 4 Practitioner: Service Request Management',
    href: 'https://www.axelos.com/certifications/itil-service-management/itil-practices-manager/itil-4-specialist-monitor-support-and-fulfil/itil-4-practitioner-service-request-management',
    detail: 'Service Request Management für strukturierte, vordefinierte Nutzeranfragen.',
    tags: ['service', 'service-request', 'support', 'sla'],
  },
  {
    id: 'omg-bpmn',
    label: 'Object Management Group - BPMN',
    href: 'https://www.omg.org/spec/BPMN/',
    detail: 'Offizielle Spezifikation der Business Process Model and Notation.',
    tags: ['projekt', 'bpmn', 'prozess'],
  },
  {
    id: 'omg-uml',
    label: 'Object Management Group - UML',
    href: 'https://www.omg.org/spec/UML/',
    detail: 'Offizielle UML-Spezifikation für Aktivitäts-, Use-Case- und Klassendiagramme.',
    tags: ['software', 'uml', 'modellierung'],
  },
  {
    id: 'w3c-wcag',
    label: 'W3C - Web Content Accessibility Guidelines (WCAG) 2.2',
    href: 'https://www.w3.org/TR/WCAG22/',
    detail: 'W3C Recommendation für barrierefreie Webinhalte mit vier Prinzipien und testbaren Erfolgskriterien, darunter Textalternativen, Farbnutzung und Mindestkontraste.',
    tags: ['web', 'ergonomie', 'barrierefreiheit', 'softwareergonomie', 'wcag'],
  },
  {
    id: 'mdn-web',
    label: 'MDN Web Docs',
    href: 'https://developer.mozilla.org/',
    detail: 'Technische Referenz für Webtechnologien, HTTP, Browsergrundlagen und Frontend-Begriffe.',
    tags: ['web', 'software', 'http'],
  },
  {
    id: 'dsgvo',
    label: 'EUR-Lex - Datenschutz-Grundverordnung (DSGVO)',
    href: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj?locale=de',
    detail: 'Amtlicher EU-Text der DSGVO, besonders Art. 5 zu den Grundsätzen der Verarbeitung.',
    tags: ['recht', 'dsgvo', 'sicherheit', 'datenschutz'],
  },
  {
    id: 'sap-mdm-definition',
    label: 'SAP Help Portal - What is MDM?',
    href: 'https://help.sap.com/docs/SAP_NETWEAVER_MASTER_DATA_MANAGEMENT/99218f2c48044ddc8f2ea30adc0e38a1/471c5928cd0412b8e10000000a1553f7.html',
    detail: 'SAP-Quelle zu Master Data als Kerndaten eines Unternehmens, die unabhängig von einzelnen Transaktionen bestehen und in Geschäftsvorgängen referenziert werden.',
    tags: ['daten', 'stammdaten', 'master-data', 'mdm', 'erp', 'datenqualitaet'],
  },
  {
    id: 'microsoft-enterprise-data-types',
    label: 'Microsoft Learn - Data architecture and modeling',
    href: 'https://learn.microsoft.com/en-us/dynamics365/guidance/implementation-guide/data-management-architecture',
    detail: 'Microsoft unterscheidet Enterprise Data in Master Data, Configuration Data, Transactional Data und Inferred Data und beschreibt den Zusammenhang zu Datenqualität.',
    tags: ['daten', 'stammdaten', 'transaktionsdaten', 'referenzdaten', 'datenqualitaet', 'datenarchitektur'],
  },
  {
    id: 'ibm-master-data-management',
    label: 'IBM - What is master data management?',
    href: 'https://www.ibm.com/think/topics/master-data-management',
    detail: 'IBM beschreibt Master Data Management, typische Master-Data-Domains wie Customer, Product, Supplier und Location sowie Probleme durch Dubletten und Inkonsistenzen.',
    tags: ['daten', 'stammdaten', 'master-data', 'mdm', 'datenqualitaet', 'datenmanagement'],
  },
  {
    id: 'bgb',
    label: 'Bürgerliches Gesetzbuch (BGB)',
    href: 'https://www.gesetze-im-internet.de/bgb/',
    detail: 'Amtliche Grundlage für Kaufvertrag, Leistungsstörungen, Verzug, Gewährleistung und Garantie.',
    tags: ['recht', 'vertragsrecht', 'gewaehrleistung'],
  },
  {
    id: 'hgb',
    label: 'Handelsgesetzbuch (HGB)',
    href: 'https://www.gesetze-im-internet.de/hgb/',
    detail: 'Amtliche Grundlage für Handelsgeschäfte und Mängelrüge im Handelskauf.',
    tags: ['recht', 'vertragsrecht', 'maengelruege'],
  },
  {
    id: 'afa-bmf',
    label: 'Bundesfinanzministerium - AfA-Tabellen',
    href: 'https://www.bundesfinanzministerium.de/Web/DE/Themen/Steuern/Weitere_Steuerthemen/Betriebspruefung/AfA_Tabellen/afa_tabellen.html',
    detail: 'Offizielle Orientierung für Nutzungsdauern und lineare Abschreibung.',
    tags: ['wirtschaft', 'afa', 'abschreibung'],
  },
  {
    id: 'destatis-preise',
    label: 'Statistisches Bundesamt - Preise',
    href: 'https://www.destatis.de/DE/Themen/Wirtschaft/Preise/_inhalt.html',
    detail: 'Seriöse Datenquelle für wirtschaftliche Rahmenwerte und Preisentwicklung.',
    tags: ['wirtschaft', 'kosten', 'markt'],
  },
  {
    id: 'nist-binary-prefixes',
    label: 'NIST - Prefixes for Binary Multiples',
    href: 'https://physics.nist.gov/cuu/Units/binary.html',
    detail: 'Offizielle Definition der binären Präfixe (KiB, MiB, GiB) und Abgrenzung zu SI-Präfixen.',
    tags: ['ordnung', 'bit', 'byte', 'binaer', 'iec', 'praefix', 'binaerpraefix', 'datenmenge'],
  },
  {
    id: 'nist-ir-8354-digital-investigation',
    label: 'NIST IR 8354 - Digital Investigation Techniques',
    href: 'https://nvlpubs.nist.gov/nistpubs/ir/2022/NIST.IR.8354.pdf',
    detail: 'NIST-Grundlagenbericht mit kompakter Darstellung von Stellenwertnotation, Basis 2/8/16, Hex-Gruppierung, 8-Bit-Bytes und der Kontextabhängigkeit von Bitmustern.',
    tags: ['ordnung', 'bit', 'byte', 'binaer', 'hex', 'hexadezimal', 'oktal', 'oktalsystem', 'dezimal', 'stellenwert', 'nibble', 'daten'],
  },
  {
    id: 'openstax-boolean-operations',
    label: 'OpenStax - Introduction to Python Programming: Boolean operations',
    href: 'https://openstax.org/books/introduction-python-programming/pages/4-3-boolean-operations',
    detail: 'Erklärt logische Operatoren, Wahrheitswerte und Wahrheitstabellen für and, or und not als Software-Perspektive auf Boolesche Logik.',
    tags: ['ordnung', 'software', 'boolesch', 'boolesche-algebra', 'wahrheitswert', 'wahrheitstabelle', 'und', 'oder', 'nicht', 'pseudocode'],
  },
  {
    id: 'openstax-truth-tables',
    label: 'OpenStax - Contemporary Mathematics: Constructing Truth Tables',
    href: 'https://openstax.org/books/contemporary-mathematics/pages/2-3-constructing-truth-tables',
    detail: 'Mathematische Grundlage für Wahrheitstabellen, Negation, Konjunktion und Disjunktion.',
    tags: ['ordnung', 'boolesch', 'boolesche-algebra', 'wahrheitstabelle', 'wahrheitswert', 'und', 'oder', 'nicht'],
  },
  {
    id: 'nist-dads-nand',
    label: 'NIST DADS - NAND',
    href: 'https://xlinux.nist.gov/dads/HTML/nand.html',
    detail: 'NIST Dictionary of Algorithms and Data Structures zu NAND als boolescher Funktion und universellem Logikgatter.',
    tags: ['ordnung', 'boolesch', 'boolesche-algebra', 'logikgatter', 'nand', 'digitaltechnik'],
  },
  {
    id: 'ti-logic-guide',
    label: 'Texas Instruments - Logic Guide',
    href: 'https://www.ti.com/lit/ml/sdyu001z/sdyu001z.pdf',
    detail: 'Herstellerreferenz zu realen Logikbausteinen und Gatterfamilien; stützt den Hardwarebezug von UND, ODER, NICHT und NAND.',
    tags: ['ordnung', 'hardware', 'digitaltechnik', 'logikgatter', 'und', 'oder', 'nicht', 'nand'],
  },
  {
    id: 'iec-80000-13',
    label: 'IEC 80000-13 - Information science and technology',
    href: 'https://webstore.iec.ch/publication/80483',
    detail: 'Internationaler Standard für Einheiten und Präfixe der Informationstechnik, definiert kibi, mebi, gibi und Folgepräfixe.',
    tags: ['ordnung', 'bit', 'byte', 'binaer', 'iec', 'praefix', 'binaerpraefix', 'datenmenge'],
  },
  {
    id: 'rfc-20-ascii',
    label: 'RFC 20 - ASCII format for Network Interchange',
    href: 'https://www.rfc-editor.org/rfc/rfc20.html',
    detail: 'Frei zugängliche Primärquelle zum 7-Bit-ASCII-Code: "standard 7-bit ASCII embedded in an 8 bit byte whose high order bit is always 0" – belegt die Einbettung von ASCII in ein 8-Bit-Byte.',
    tags: ['ordnung', 'ascii', 'zeichen', 'zeichenkodierung', 'bit', 'byte'],
  },
  {
    id: 'ansi-x3-4-ascii',
    label: 'ANSI INCITS 4-1986 (R2017) - 7-Bit ASCII',
    href: 'https://webstore.ansi.org/standards/incits/ansiincits41986r2017',
    detail: 'US-amerikanischer Standard für den 7-Bit-ASCII-Zeichensatz mit 128 Codepunkten.',
    tags: ['ordnung', 'ascii', 'zeichen', 'zeichenkodierung', 'bit', 'byte'],
  },
  {
    id: 'unicode-utf-8',
    label: 'Unicode Standard - UTF-8',
    href: 'https://www.unicode.org/versions/latest/core-spec/chapter-3/',
    detail: 'Unicode-Standard zur UTF-8-Codierung: ASCII-Codepunkte werden mit einem Byte dargestellt, weitere Codepunkte mit mehreren Bytes.',
    tags: ['ordnung', 'unicode', 'utf-8', 'zeichen', 'zeichenkodierung', 'bit', 'byte'],
  },
  {
    id: 'rfc-3629-utf8',
    label: 'RFC 3629 - UTF-8, a transformation format of ISO 10646',
    href: 'https://www.rfc-editor.org/rfc/rfc3629.html',
    detail: 'Frei zugängliche Primärquelle zu UTF-8: US-ASCII-Zeichen (0x00-0x7F) werden unverändert mit einem Oktett codiert, weitere Zeichen mit bis zu vier Oktetten.',
    tags: ['ordnung', 'unicode', 'utf-8', 'zeichen', 'zeichenkodierung', 'bit', 'byte'],
  },
  {
    id: 'bipm-si-prefixes',
    label: 'BIPM - SI prefixes',
    href: 'https://www.bipm.org/en/measurement-units/si-prefixes',
    detail: 'Internationales Bureau für Mass und Gewicht (BIPM): Offizielle SI-Präfixe k=10^3, M=10^6, G=10^9, T=10^12 etc. Die Verwendung von kilo (k) für 2^10 ist laut SI unzulässig.',
    tags: ['ordnung', 'praefix', 'dezimalpraefix', 'si', 'dezimal', 'datenmenge', 'datenrate', 'bit', 'byte'],
  },
  {
    id: 'jedec-100b-01',
    label: 'JEDEC 100B.01 - Unit Prefixes for Semiconductor Storage Capacity',
    href: 'https://www.nomad.jedec.org/standards-documents/dictionary/terms/mega-m-prefix-units-semiconductor-storage-capacity',
    detail: 'JEDEC-Industriestandard: dokumentiert die in der Halbleiterindustrie verbreitete binäre Auslegung von K=1024, M=2^20, G=2^30 ausdrücklich nur "to reflect common usage" - erklärt die historische Wurzel der KB/KiB-Verwirrung.',
    tags: ['ordnung', 'praefix', 'binaerpraefix', 'binaer', 'datenmenge', 'bit', 'byte', 'industrie'],
  },
  {
    id: 'ibm-storage-units',
    label: 'IBM - Units of measurement for storage data',
    href: 'https://www.ibm.com/docs/en/storage-insights?topic=overview-units-measurement-storage-data',
    detail: 'IBM-Dokumentation zu dezimalen und binären Speichereinheiten, Prozentabweichungen zwischen KB/KiB bis TB/TiB und praktischer Verwendung in Storage-Anzeigen.',
    tags: ['ordnung', 'praefix', 'dezimalpraefix', 'binaerpraefix', 'si', 'iec', 'datenmenge', 'storage'],
  },
  {
    id: 'gnu-coreutils-df',
    label: 'GNU Coreutils Manual - df invocation',
    href: 'https://www.gnu.org/software/coreutils/df',
    detail: 'GNU-Coreutils-Dokumentation zu df: human-readable nutzt 1024er-Schritte, --si nutzt 1000er-Schritte.',
    tags: ['ordnung', 'praefix', 'binaerpraefix', 'dezimalpraefix', 'linux', 'coreutils', 'datenmenge'],
  },
  {
    id: 'iso-iec-10918-1-jpeg',
    label: 'ISO/IEC 10918-1 - JPEG still image compression',
    href: 'https://www.iso.org/standard/18902.html',
    detail: 'Internationaler Standard für digitale Kompression und Codierung kontinuierlicher Graustufen- und Farbbilder; Grundlage für JPEG als verlustbehaftetes Bildformat.',
    tags: ['datenmenge', 'bilddaten', 'jpeg', 'kompression', 'verlustbehaftet', 'foto'],
  },
  {
    id: 'w3c-png-3',
    label: 'W3C - Portable Network Graphics (PNG) Specification',
    href: 'https://www.w3.org/TR/png/',
    detail: 'Offizielle PNG-Spezifikation: PNG ist ein verlustfreies Rasterbildformat; IHDR enthält Breite, Höhe, Bit Depth und Color Type.',
    tags: ['datenmenge', 'bilddaten', 'png', 'kompression', 'verlustfrei', 'farbtiefe'],
  },
  {
    id: 'itu-t-h264',
    label: 'ITU-T H.264 - Advanced video coding',
    href: 'https://www.itu.int/rec/T-REC-H.264',
    detail: 'ITU-T-Empfehlung zu H.264/AVC als Videocodierungsstandard; relevant für Ziel-Bitraten und den Unterschied zwischen Rohdaten und komprimiertem Video.',
    tags: ['datenmenge', 'video', 'h264', 'kompression', 'bitrate', 'verlustbehaftet'],
  },
  {
    id: 'itu-t-g1010',
    label: 'ITU-T G.1010 - End-user multimedia QoS categories',
    href: 'https://www.itu.int/rec/T-REC-G.1010',
    detail: 'ITU-T-Empfehlung zu Dienstgüte-Anforderungen aus Nutzersicht, unter anderem Latenz, Jitter und Datenraten für Multimedia-Anwendungen.',
    tags: ['netzwerk', 'datenrate', 'durchsatz', 'latenz', 'jitter', 'multimedia'],
  },
  {
    id: 'posix-chmod',
    label: 'IEEE Std 1003.1 (POSIX) - chmod',
    href: 'https://pubs.opengroup.org/onlinepubs/9699919799/utilities/chmod.html',
    detail: 'Open-Group-Spezifikation: definiert die zwölf File-Mode-Bits als vier Oktalziffern. Wertigkeiten r=4, w=2, x=1 für die Rollen User, Group und Other - Grundlage für das Lesen von chmod 755, 644, 700.',
    tags: ['ordnung', 'betriebssystem', 'linux', 'chmod', 'oktal', 'oktalsystem', 'dateirechte', 'posix', 'sicherheit'],
  },
  {
    id: 'gnu-coreutils-chmod',
    label: 'GNU Coreutils Manual - chmod invocation',
    href: 'https://www.gnu.org/software/coreutils/manual/html_node/chmod-invocation.html',
    detail: 'GNU-Coreutils-Dokumentation zur praktischen chmod-Nutzung mit symbolischen und numerischen Modi in Unix-/Linux-Umgebungen.',
    tags: ['betriebssystem', 'linux', 'chmod', 'dateirechte', 'posix', 'sicherheit', 'rwx'],
  },
  {
    id: 'linux-man-pages-chmod2',
    label: 'Linux man-pages - chmod(2)',
    href: 'https://man7.org/linux/man-pages/man2/chmod.2.html',
    detail: 'Linux-Systemaufruf zum Ändern von Dateimodi; beschreibt normale Rechte und Sonderbits wie set-user-ID, set-group-ID und sticky bit.',
    tags: ['betriebssystem', 'linux', 'chmod', 'dateirechte', 'suid', 'sgid', 'sticky', 'sicherheit'],
  },
  {
    id: 'rfc-9542',
    label: 'RFC 9542 - IANA Considerations and IETF Usage for IEEE 802 Parameters',
    href: 'https://www.rfc-editor.org/rfc/rfc9542.html',
    detail: 'Aktuelle IETF-Quelle (löst RFC 7042 ab) zu IEEE-802-Parametern und 48-Bit-Identifiern als sechs Paare hexadezimaler Ziffern.',
    tags: ['ordnung', 'netzwerk', 'mac-adresse', 'eui-48', 'hex', 'hexadezimal', 'ieee-802'],
  },
  {
    id: 'w3c-css-color-4',
    label: 'W3C - CSS Color Module Level 4',
    href: 'https://www.w3.org/TR/css-color-4/',
    detail: 'W3C-Spezifikation der Hex-Notation #RRGGBB[AA] für sRGB-Farben: drei (oder vier) 8-Bit-Komponenten Rot/Grün/Blau (Alpha) als jeweils zwei Hex-Ziffern, 0x00 bis 0xFF pro Kanal.',
    tags: ['ordnung', 'web', 'css', 'farbe', 'hex', 'hexadezimal', 'rgb'],
  },
  {
    id: 'python-lexical-integer-literals',
    label: 'Python Language Reference - Integer literals',
    href: 'https://docs.python.org/3/reference/lexical_analysis.html#integer-literals',
    detail: 'Offizielle Python-Referenz zu Ganzzahl-Literalen: 0b für binär, 0o für oktal, 0x für hexadezimal; führende Nullen in Nicht-Null-Dezimalzahlen sind nicht erlaubt.',
    tags: ['ordnung', 'python', 'literal', 'binaer', 'oktal', 'hex', 'praefix'],
  },
  {
    id: 'ecma-262-numeric-literals',
    label: 'ECMAScript Language Specification - Numeric literals',
    href: 'https://tc39.es/ecma262/2026/multipage/ecmascript-language-lexical-grammar.html',
    detail: 'Aktuelle offizielle ECMAScript-Spezifikation für numerische Literale, unter anderem binäre, oktale und hexadezimale Schreibweisen.',
    tags: ['ordnung', 'javascript', 'ecmascript', 'literal', 'binaer', 'oktal', 'hex', 'praefix'],
  },
  {
    id: 'ieee-754-2019',
    label: 'IEEE Std 754-2019 - Floating-Point Arithmetic',
    href: 'https://standards.ieee.org/ieee/754/6210/',
    detail: 'IEEE-Standard für binäre und dezimale Gleitkomma-Arithmetik, darunter binary32 und binary64 mit Vorzeichen, Exponent und Signifikand.',
    tags: ['ordnung', 'ieee', 'gleitkomma', 'floating-point', 'binary32', 'binary64', 'exponent', 'mantisse'],
  },
  {
    id: 'destatis-bruttowertschoepfung',
    label: 'Statistisches Bundesamt – Bruttowertschöpfung',
    href: 'https://www.destatis.de/DE/Themen/Wirtschaft/Volkswirtschaftliche-Gesamtrechnungen-Inlandsprodukt/Glossar/bruttowertschoepfung.html',
    detail: 'Amtliche Definition: Bruttowertschöpfung ist Produktionswert abzüglich Vorleistungen und beschreibt den im Produktionsprozess geschaffenen Mehrwert.',
    tags: ['wirtschaft', 'unternehmen', 'betrieb', 'wertschoepfung', 'vorleistung', 'produktionswert'],
  },
  {
    id: 'eu-esrs-stakeholder',
    label: 'Delegierte Verordnung (EU) 2023/2772 – Interessenträger und Wertschöpfungskette',
    href: 'https://eur-lex.europa.eu/eli/reg/2023/2772/oj?locale=de',
    detail: 'Amtliche EU-Quelle: Interessenträger können ein Unternehmen beeinflussen oder von ihm beeinflusst werden; behandelt zudem vor- und nachgelagerte Wertschöpfungsketten.',
    tags: ['wirtschaft', 'unternehmen', 'wertschoepfung', 'wertschoepfungskette', 'anspruchsgruppe', 'stakeholder'],
  },
  {
    id: 'bpb-stakeholder-management',
    label: 'bpb – Shareholder-Value-Management und Stakeholder-Management',
    href: 'https://www.bpb.de/kurz-knapp/lexika/lexikon-der-wirtschaft/20611/shareholder-value-management/',
    detail: 'Fachlexikon zur Orientierung an Anspruchsgruppen; nennt unter anderem Mitarbeitende, Lieferanten, Kunden, Staat, Umwelt und Öffentlichkeit.',
    tags: ['wirtschaft', 'unternehmen', 'anspruchsgruppe', 'stakeholder', 'kunden', 'lieferanten'],
  },
  {
    id: 'refa-aufbauorganisation',
    label: 'REFA – Aufbauorganisation',
    href: 'https://refa.de/service/lean-beratung/lean-methoden/aufbauorganisation',
    detail: 'Aktuelle Fachquelle zu Organigramm, Leitungssystem und den Grundformen Linien-, Stab-Linien-, Mehrlinien- und Matrixorganisation.',
    tags: ['wirtschaft', 'organisation', 'aufbauorganisation', 'organigramm', 'leitungssystem', 'linienorganisation', 'matrixorganisation'],
  },
  {
    id: 'refa-ablauforganisation',
    label: 'REFA – Ablauforganisation',
    href: 'https://refa.de/service/lean-beratung/lean-methoden/ablauforganisation',
    detail: 'Aktuelle Fachquelle zur zeitlichen und räumlichen Folge von Tätigkeiten sowie zu Ablaufplan, Schnittstellen, Abhängigkeiten und Verantwortlichkeiten.',
    tags: ['wirtschaft', 'organisation', 'ablauforganisation', 'prozess', 'ablaufplan', 'schnittstelle'],
  },
  {
    id: 'bsi-orp-1-organisation',
    label: 'BSI – IT-Grundschutz-Baustein ORP.1 Organisation',
    href: 'https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Grundschutz/IT-GS-Kompendium_Einzel_PDFs_2023/02_ORP_Organisation_und_Personal/ORP_1_Organisation_Edition_2023.pdf?__blob=publicationFile&v=3',
    detail: 'Amtliche IT-Fachquelle: Informationsflüsse, Prozesse, Rollenverteilungen sowie Aufbau- und Ablauforganisation sollen geregelt werden.',
    tags: ['sicherheit', 'organisation', 'aufbauorganisation', 'ablauforganisation', 'prozess', 'rolle', 'informationsfluss'],
  },
  {
    id: 'ihk-aka-pruefungs-news-2024',
    label: 'IHK-AkA – Prüfungs-News 09/24 zu IT-Prüfungskatalogen',
    href: 'https://www.ihk-zpa.de/export/sites/default/LinkRepository/IHK-Pruefungs-News/IHK-Pruefungs-News_09-24.pdf',
    detail: 'Offizielle Prüfungsinformation zur zweiten Auflage ab AP1 Frühjahr 2025: SQL und RAID nur AP2, PAP und Struktogramm gestrichen sowie Übergang zu UML/BPMN und neuen KI-Themen.',
    tags: ['ausbildung', 'ap1', 'pruefung', 'pruefungskatalog', 'pruefungsrealitaet'],
  },
]
