/**
 * Grundlast · Quellen — Tag-Mappings
 *
 * Datenbasis fuer die automatische Zuordnung von Quellen zu Lektionen.
 */

export const slugTags: Record<string, string[]> = {
  'von-neumann': ['ordnung', 'rechnerarchitektur', 'von-neumann', 'stored-program', 'edvac', 'cpu', 'alu', 'steuerwerk', 'ram', 'speicher', 'bus', 'instruction-cycle', 'fetch', 'decode', 'execute', 'cache', 'flaschenhals', 'harvard'],
  'bit-byte': ['ordnung', 'bit', 'byte', 'binaer', 'ascii', 'praefix', 'datenmenge', 'zeichenkodierung'],
  'zahlensysteme': ['ordnung', 'bit', 'byte', 'binaer', 'hex', 'hexadezimal', 'oktal', 'dezimal', 'stellenwert', 'nibble', 'chmod', 'dateirechte', 'mac-adresse', 'eui-48', 'cidr', 'subnetting', 'farbe', 'css', 'rgb', 'python', 'javascript', 'ecmascript', 'literal'],
  'prefixe': ['ordnung', 'bit', 'byte', 'binaer', 'iec', 'praefix', 'datenmenge', 'si', 'dezimal'],
  'cpu-ram-speicher': ['ordnung'],
  'hardware-schnittstellen': ['ordnung', 'sicherheit', 'ergonomie'],
  'raid-systeme': ['sicherheit', 'backup'],
  'usv-systeme': ['sicherheit', 'verfuegbarkeit'],
  'scan-bilddaten': ['ordnung'],
  'linux-chmod': ['sicherheit', 'betriebssystem', 'linux', 'chmod', 'oktal', 'dateirechte', 'posix', 'rwx', 'owner', 'group', 'other', 'suid', 'sgid', 'sticky'],
  'prozess-thread': ['betriebssystem', 'prozess', 'thread', 'task', 'scheduler', 'multitasking'],
  'zentral-dezentral': ['betriebssystem', 'zentral', 'dezentral', 'hybrid', 'cloud', 'verzeichnisdienst', 'client-server', 'it-infrastruktur'],
  virtualisierung: ['sicherheit'],
  'wlan-standards': ['wlan', 'wifi', 'wi-fi', '802.11', 'wpa2', 'wpa3', 'access-point', 'sicherheit', 'netzwerk'],
  'port-forwarding': ['nat', 'napt', 'pat', 'port-forwarding', 'ipv4', 'private-adressen', 'firewall', 'dmz', 'vpn', 'netzwerk', 'sicherheit'],
  'osi-modell': ['netzwerk', 'osi'],
  'tcp-udp': ['tcp', 'udp', 'netzwerk', 'port', 'dienst', 'http', 'tls'],
  'ipv4-subnetting': ['ipv4', 'subnetting', 'netzwerk'],
  'datenrate-berechnung': ['netzwerk', 'datenrate', 'bandbreite', 'durchsatz', 'bit', 'byte', 'backup', 'wlan'],
  netzwerkkonfiguration: ['netzwerk', 'ipv4', 'dhcp', 'dns', 'arp', 'apipa', 'subnetting'],
  'firewall-dmz': ['firewall', 'dmz', 'sicherheit', 'netzsegmentierung', 'allowlist', 'paketfilter', 'application-layer-gateway'],
  'er-grundlagen': ['datenbank', 'er'],
  'sql-grundlagen': ['datenbank', 'sql'],
  normalisierung: ['datenbank', 'normalisierung'],
  'serviceanfragen-support-level': ['service', 'support', 'incident', 'service-request', 'sla'],
  'fehlermanagement-stoerungsannahme': ['service', 'support', 'incident', 'service-request', 'sla', 'prozess'],
  'bedarfsanalyse-feedback': ['service', 'support', 'feedback', 'prozess'],
  'mitarbeitermotivation-teamphasen-change': ['motivation', 'team', 'teamphasen', 'change', 'kommunikation', 'prozess'],
  'schulung-einweisung-key-user': ['schulung', 'kompetenz', 'service', 'support', 'change', 'kommunikation', 'prozess'],
  'crm-erp-dms': ['unternehmenssoftware', 'crm', 'erp', 'dms', 'cms', 'software', 'service'],
  'pseudocode-einstieg': ['software'],
  'uml-aktivitaet': ['uml', 'software'],
  netzplan: ['projekt'],
  vorgehensmodelle: ['projekt', 'agil', 'wasserfall', 'v-modell', 'v-modell-xt', 'scrum', 'kanban', 'manifest', 'iterativ', 'inkrementell', 'lebenszyklus', 'historisch'],
  bpmn: ['bpmn', 'prozess'],
  scrum: ['projekt', 'scrum', 'agil', 'sprint', 'backlog', 'increment', 'product-goal', 'sprint-goal', 'definition-of-done', 'accountabilities'],
  'lastenheft-pflichtenheft': ['projekt'],
  'dsgvo-basics': ['dsgvo', 'datenschutz', 'recht'],
  'verschluesselung-hash-vpn': ['krypto', 'verschluesselung', 'hashing', 'zertifikat', 'pki', 'signatur', 'vpn', 'ipsec', 'tls'],
  'verschluesselung-sicherheit': ['krypto', 'sicherheit'],
  'passwoerter-hashing': ['passwort', 'hashing', 'krypto'],
  schutzziele: ['sicherheit'],
  'backup-strategien': ['backup', 'sicherheit'],
  'mtbf-mttf': ['verfuegbarkeit', 'sicherheit'],
  'kaufmaennische-rechenaufgaben': ['wirtschaft', 'kosten'],
  'break-even': ['wirtschaft', 'kosten'],
  handelskalkulation: ['wirtschaft'],
  'afa-abschreibung': ['wirtschaft', 'afa', 'abschreibung'],
  'variable-fixe-kosten': ['wirtschaft', 'kosten'],
  gewinnermittlung: ['wirtschaft', 'kosten'],
  energiekosten: ['wirtschaft', 'kosten'],
  nutzwertanalyse: ['wirtschaft', 'projekt'],
  'make-or-buy': ['wirtschaft', 'entscheidung', 'make-or-buy', 'eigenfertigung', 'fremdbezug', 'transaktionskosten', 'nutzwertanalyse'],
  angebotsvergleich: ['wirtschaft', 'angebot', 'angebotsvergleich', 'bezugspreis', 'nutzwertanalyse', 'entscheidung'],
  'kauf-leasing-miete': ['kauf-leasing-miete', 'wirtschaft', 'kosten', 'recht', 'leasing', 'afa'],
  vertragsarten: ['vertragsarten', 'vertragsrecht', 'kaufvertrag', 'dienstvertrag', 'werkvertrag', 'abnahme', 'erfolgspflicht'],
  'rechnung-zahlungsziel-aufbewahrungsfristen': ['rechnung', 'e-rechnung', 'zahlungsziel', 'zahlungsverzug', 'aufbewahrung', 'aufbewahrungsfrist', 'buchungsbeleg'],
  marktformen: ['wirtschaft', 'markt'],
  eigenfremdfinanzierung: ['finanzierung', 'eigenfinanzierung', 'fremdfinanzierung', 'eigenkapital', 'fremdkapital', 'darlehen', 'zins', 'tilgung'],
  'aida-formel': ['wirtschaft', 'marketing', 'kommunikation', 'werbung', 'aida', 'werbewirkung'],
  'organisationsformen-leitbild-nachhaltigkeit-esg': ['wirtschaft', 'organisation', 'rechtsform', 'unternehmensform', 'einzelunternehmen', 'gmbh', 'aktiengesellschaft', 'ohg', 'kg', 'leitbild', 'nachhaltigkeit', 'esg', 'governance'],
}

export const lessonSourceIds: Record<string, string[]> = {
  'von-neumann': [
    'smithsonian-edvac-first-draft',
    'computer-history-museum-edvac',
    'ibm-cpu-instruction-cycle',
    'cornell-cpu-stages',
  ],
  'linux-chmod': [
    'posix-chmod',
    'gnu-coreutils-chmod',
    'linux-man-pages-chmod2',
  ],
  zahlensysteme: [
    'posix-chmod',
    'rfc-9542',
    'w3c-css-color-4',
    'rfc-4632',
    'python-lexical-integer-literals',
    'ecma-262-numeric-literals',
  ],
  'ipv4-subnetting': [
    'rfc-791',
    'rfc-4632',
    'rfc-1918',
    'rfc-3021',
    'iana-ipv4-special-registry',
  ],
}

export const lernfeldTags: Record<string, string[]> = {
  grundlagen: ['ordnung'],
  hardware: ['ordnung', 'sicherheit'],
  betriebssysteme: ['sicherheit'],
  netzwerke: ['netzwerk'],
  daten: ['datenbank'],
  software: ['software'],
  projekt: ['projekt'],
  sicherheit: ['sicherheit'],
  wirtschaft: ['wirtschaft'],
  vertragsrecht: ['recht', 'vertragsrecht'],
  qualitaet: ['projekt'],
  webmedia: ['web'],
  aktuell: ['ordnung'],
  arbeitsrecht: ['recht', 'ausbildung'],
}
