/**
 * Grundlast · Quellen — Tag-Mappings
 *
 * Datenbasis fuer die automatische Zuordnung von Quellen zu Lektionen.
 */

export const slugTags: Record<string, string[]> = {
  'von-neumann': ['ordnung', 'rechnerarchitektur', 'von-neumann', 'stored-program', 'edvac', 'cpu', 'alu', 'steuerwerk', 'ram', 'speicher', 'bus', 'instruction-cycle', 'fetch', 'decode', 'execute', 'cache', 'flaschenhals', 'harvard'],
  'bit-byte': ['ordnung', 'bit', 'byte', 'binaer', 'ascii', 'unicode', 'utf-8', 'zeichen', 'zeichenkodierung', 'praefix', 'dezimalpraefix', 'binaerpraefix', 'datenmenge', 'datenrate', 'si', 'iec'],
  'zahlensysteme': ['ordnung', 'bit', 'byte', 'binaer', 'hex', 'hexadezimal', 'oktal', 'oktalsystem', 'dezimal', 'stellenwert', 'nibble', 'chmod', 'dateirechte', 'mac-adresse', 'eui-48', 'cidr', 'subnetting', 'farbe', 'css', 'rgb', 'exponent', 'mantisse', 'literal'],
  'prefixe': ['ordnung', 'bit', 'byte', 'binaer', 'iec', 'praefix', 'dezimalpraefix', 'binaerpraefix', 'datenmenge', 'datenrate', 'si', 'dezimal', 'industrie', 'storage', 'linux', 'coreutils'],
  'cpu-ram-speicher': ['ordnung', 'hardware', 'lf2', 'cpu', 'ram', 'arbeitsspeicher', 'massenspeicher', 'ssd', 'hdd', 'nvme', 'sata', 'pcie', 'cache', 'taktfrequenz', 'kerne', 'threads', 'ddr', 'ddr4', 'ddr5', 'mainboard'],
  'hardware-schnittstellen': ['ordnung', 'sicherheit', 'ergonomie'],
  'homeoffice-ergonomie': ['ordnung', 'hardware', 'arbeitsschutz', 'ergonomie', 'barrierefreiheit', 'telearbeit', 'homeoffice', 'mobile-arbeit', 'softwareergonomie', 'wcag', 'bitv'],
  'raid-systeme': ['sicherheit', 'backup'],
  'usv-systeme': ['sicherheit', 'verfuegbarkeit'],
  'scan-bilddaten': ['ordnung'],
  'linux-chmod': ['sicherheit', 'betriebssystem', 'linux', 'chmod', 'oktal', 'dateirechte', 'posix', 'rwx', 'owner', 'group', 'other', 'suid', 'sgid', 'sticky'],
  'prozess-thread': ['betriebssystem', 'prozess', 'thread', 'task', 'scheduler', 'multitasking'],
  'zentral-dezentral': ['betriebssystem', 'zentral', 'dezentral', 'hybrid', 'cloud', 'verzeichnisdienst', 'client-server', 'it-infrastruktur'],
  virtualisierung: ['sicherheit'],
  'wlan-standards': ['wlan', 'wifi', 'wi-fi', '802.11', '802.11ax', '802.11be', 'wifi-6', 'wifi-6e', 'wifi-7', 'wpa2', 'wpa3', 'access-point', 'ssid', 'frequenzband', 'wlan-kanal', 'roaming', 'wps', 'gastnetz', 'sicherheit', 'netzwerk'],
  'port-forwarding': ['nat', 'napt', 'pat', 'port-forwarding', 'ipv4', 'private-adressen', 'firewall', 'dmz', 'vpn', 'ds-lite', 'cgnat', 'carrier-grade-nat', 'netzwerk', 'sicherheit'],
  'osi-modell': ['netzwerk', 'osi', 'tcp-ip', 'schichtenmodell', 'pdu', 'ethernet', 'arp', 'ip', 'tcp', 'udp', 'dns', 'tls', 'http'],
  'tcp-udp': ['tcp', 'udp', 'netzwerk', 'port', 'dienst', 'http', 'tls', 'dns', 'dhcp', 'firewall', 'nat'],
  'ipv6-grundlagen': ['ipv6', 'adressierung', 'praefix', 'prefix', 'slaac', 'autokonfiguration', 'link-local', 'unique-local', 'ula', 'multicast', 'eui-64', 'interface-identifier', 'privacy'],
  'ipv4-subnetting': ['ipv4', 'subnetting', 'netzwerk'],
  'datenrate-berechnung': ['netzwerk', 'datenrate', 'bandbreite', 'durchsatz', 'bit', 'byte', 'backup', 'wlan'],
  'datenvolumen-berechnung': ['ordnung', 'netzwerk', 'datenmenge', 'datenrate', 'bandbreite', 'durchsatz', 'bit', 'byte', 'praefix', 'dezimalpraefix', 'binaerpraefix', 'scan', 'bilddaten', 'dpi', 'farbtiefe', 'kompression', 'bitrate', 'video'],
  netzwerkkonfiguration: ['netzwerk', 'ipv4', 'dhcp', 'dns', 'arp', 'apipa', 'subnetting'],
  'firewall-dmz': ['firewall', 'dmz', 'sicherheit', 'netzsegmentierung', 'allowlist', 'paketfilter', 'application-layer-gateway'],
  'er-grundlagen': ['datenbank', 'er'],
  'sql-grundlagen': ['datenbank', 'sql'],
  normalisierung: ['datenbank', 'normalisierung'],
  'stamm-bewegungsdaten': ['ordnung', 'daten', 'datenart', 'stammdaten', 'bewegungsdaten', 'bestandsdaten', 'referenzdaten', 'transaktionsdaten', 'datenqualitaet', 'datenbank', 'erp', 'crm', 'datenschutz', 'dsgvo'],
  'serviceanfragen-support-level': ['service', 'support', 'incident', 'service-request', 'sla'],
  'fehlermanagement-stoerungsannahme': ['service', 'support', 'incident', 'service-request', 'sla', 'prozess'],
  'bedarfsanalyse-feedback': ['service', 'support', 'feedback', 'prozess'],
  'mitarbeitermotivation-teamphasen-change': ['motivation', 'team', 'teamphasen', 'change', 'kommunikation', 'prozess'],
  'schulung-einweisung-key-user': ['schulung', 'kompetenz', 'service', 'support', 'change', 'kommunikation', 'prozess'],
  'crm-erp-dms': ['unternehmenssoftware', 'crm', 'erp', 'dms', 'cms', 'software', 'service'],
  'pseudocode-einstieg': ['software', 'pseudocode', 'algorithmus', 'kontrollstruktur', 'bedingung', 'boolesch', 'wahrheitswert', 'und', 'oder', 'nicht'],
  'uml-aktivitaet': ['uml', 'software'],
  netzplan: ['projekt'],
  vorgehensmodelle: ['projekt', 'agil', 'wasserfall', 'v-modell', 'v-modell-xt', 'scrum', 'kanban', 'manifest', 'iterativ', 'inkrementell', 'lebenszyklus', 'historisch'],
  bpmn: ['bpmn', 'prozess'],
  scrum: ['projekt', 'scrum', 'agil', 'sprint', 'backlog', 'increment', 'product-goal', 'sprint-goal', 'definition-of-done', 'accountabilities'],
  'lastenheft-pflichtenheft': ['projekt'],
  'dsgvo-basics': ['dsgvo', 'datenschutz', 'recht'],
  'verschluesselung-hash-vpn': ['krypto', 'verschluesselung', 'hashing', 'zertifikat', 'pki', 'signatur', 'vpn', 'ipsec', 'tls'],
  'pki-zertifikate': ['krypto', 'zertifikat', 'pki', 'signatur', 'tls', 'ocsp', 'widerruf'],
  'verschluesselung-sicherheit': ['krypto', 'sicherheit'],
  'passwoerter-hashing': ['passwort', 'hashing', 'krypto'],
  schutzziele: ['sicherheit'],
  'backup-strategien': ['backup', 'sicherheit'],
  'mtbf-mttf': ['verfuegbarkeit', 'sicherheit'],
  'kaufmaennische-rechenaufgaben': ['wirtschaft', 'kosten'],
  'break-even': ['wirtschaft', 'kosten'],
  handelskalkulation: ['wirtschaft'],
  'afa-abschreibung': ['wirtschaft', 'afa', 'abschreibung'],
  'variable-fixe-kosten': ['wirtschaft', 'kosten'],
  gewinnermittlung: ['wirtschaft', 'kosten'],
  energiekosten: ['wirtschaft', 'kosten'],
  nutzwertanalyse: ['wirtschaft', 'projekt'],
  'make-or-buy': ['wirtschaft', 'entscheidung', 'make-or-buy', 'eigenfertigung', 'fremdbezug', 'transaktionskosten', 'nutzwertanalyse'],
  angebotsvergleich: ['wirtschaft', 'angebot', 'angebotsvergleich', 'bezugspreis', 'nutzwertanalyse', 'entscheidung'],
  'kauf-leasing-miete': ['kauf-leasing-miete', 'wirtschaft', 'kosten', 'recht', 'leasing', 'afa'],
  vertragsarten: ['vertragsarten', 'vertragsrecht', 'kaufvertrag', 'dienstvertrag', 'werkvertrag', 'abnahme', 'erfolgspflicht'],
  gewaehrleistung: ['recht', 'vertragsrecht', 'gewaehrleistung', 'garantie', 'sachmangel', 'maengelrechte', 'nacherfuellung', 'ruecktritt', 'minderung', 'schadensersatz', 'verbrauchsgueterkauf', 'maengelruege'],
  'rechnung-zahlungsziel-aufbewahrungsfristen': ['rechnung', 'e-rechnung', 'zahlungsziel', 'zahlungsverzug', 'aufbewahrung', 'aufbewahrungsfrist', 'buchungsbeleg'],
  marktformen: ['wirtschaft', 'markt'],
  eigenfremdfinanzierung: ['finanzierung', 'eigenfinanzierung', 'fremdfinanzierung', 'eigenkapital', 'fremdkapital', 'darlehen', 'zins', 'tilgung'],
  'aida-formel': ['wirtschaft', 'marketing', 'kommunikation', 'werbung', 'aida', 'werbewirkung'],
  'organisationsformen-leitbild-nachhaltigkeit-esg': ['wirtschaft', 'organisation', 'rechtsform', 'unternehmensform', 'einzelunternehmen', 'gmbh', 'aktiengesellschaft', 'ohg', 'kg', 'leitbild', 'nachhaltigkeit', 'esg', 'governance'],
}

export const lessonSourceIds: Record<string, string[]> = {
  'von-neumann': [
    'smithsonian-edvac-first-draft',
    'computer-history-museum-edvac',
    'ibm-cpu-instruction-cycle',
    'cornell-cpu-stages',
  ],
  'bit-byte': [
    'kmk-rahmenlehrplan',
    'fiausbv',
    'bibb-fachinformatiker',
    'nist-ir-8354-digital-investigation',
    'iec-80000-13',
    'nist-binary-prefixes',
    'bipm-si-prefixes',
    'rfc-20',
    'rfc-3629',
    'unicode-utf-8',
  ],
  'prefixe': [
    'kmk-rahmenlehrplan',
    'fiausbv',
    'bibb-fachinformatiker',
    'iec-80000-13',
    'nist-binary-prefixes',
    'bipm-si-prefixes',
    'jedec-100b-01',
    'ibm-storage-units',
    'gnu-coreutils-df',
  ],
  'linux-chmod': [
    'posix-chmod',
    'gnu-coreutils-chmod',
    'linux-man-pages-chmod2',
  ],
  'cpu-ram-speicher': [
    'kmk-rahmenlehrplan',
    'fiausbv',
    'bibb-fachinformatiker',
    'ibm-cpu-instruction-cycle',
    'intel-cpu-clock-speed',
    'microsoft-ssd-hdd-storage',
    'nvmexpress-faq',
    'crucial-ddr-generations',
  ],
  zahlensysteme: [
    'kmk-rahmenlehrplan',
    'fiausbv',
    'bibb-fachinformatiker',
    'nist-ir-8354-digital-investigation',
    'iec-80000-13',
    'posix-chmod',
    'rfc-9542',
    'w3c-css-color-4',
    'rfc-4632',
    'ieee-754-2019',
  ],
  'stamm-bewegungsdaten': [
    'kmk-rahmenlehrplan',
    'fiausbv',
    'bibb-fachinformatiker',
    'sap-mdm-definition',
    'microsoft-enterprise-data-types',
    'ibm-master-data-management',
    'dsgvo',
  ],
  'pseudocode-einstieg': [
    'kmk-rahmenlehrplan',
    'fiausbv',
    'bibb-fachinformatiker',
    'openstax-boolean-operations',
  ],
  'ipv4-subnetting': [
    'rfc-791',
    'rfc-4632',
    'rfc-1918',
    'rfc-3021',
    'iana-ipv4-special-registry',
  ],
  netzwerkkonfiguration: [
    'kmk-rahmenlehrplan',
    'fiausbv',
    'bibb-fachinformatiker',
    'rfc-2131',
    'rfc-1034',
    'rfc-1035',
    'rfc-826',
    'rfc-3927',
    'rfc-791',
    'iana-ipv4-special-registry',
  ],
  'osi-modell': [
    'kmk-rahmenlehrplan',
    'fiausbv',
    'bibb-fachinformatiker',
    'itu-x200-osi-basic-model',
    'iso-7498-1',
    'rfc-1122',
    'rfc-791',
    'rfc-826',
    'rfc-9293',
    'rfc-768',
    'rfc-9110',
    'rfc-8446',
  ],
  'tcp-udp': [
    'kmk-rahmenlehrplan',
    'fiausbv',
    'bibb-fachinformatiker',
    'rfc-9293',
    'rfc-768',
    'rfc-6335',
    'iana-service-port-registry',
    'rfc-1035',
    'rfc-7766',
    'rfc-2131',
    'rfc-9110',
    'rfc-8446',
  ],
  'firewall-dmz': [
    'kmk-rahmenlehrplan',
    'fiausbv',
    'bibb-fachinformatiker',
    'bsi-net-3-2-firewall',
    'bsi-net-1-1-netzarchitektur',
    'bsi-firewall',
    'bsi-router-wlan-vpn',
    'rfc-1918',
  ],
  'port-forwarding': [
    'kmk-rahmenlehrplan',
    'fiausbv',
    'bibb-fachinformatiker',
    'rfc-1918',
    'rfc-2663',
    'rfc-3022',
    'rfc-5737',
    'rfc-6333',
    'rfc-6888',
    'bsi-router-wlan-vpn',
    'bsi-firewall',
    'bsi-net-1-1-netzarchitektur',
    'bsi-vpn',
  ],
  'ipv6-grundlagen': [
    'kmk-rahmenlehrplan',
    'fiausbv',
    'bibb-fachinformatiker',
    'rfc-8200',
    'rfc-4291',
    'rfc-5952',
    'rfc-4862',
    'rfc-8981',
    'rfc-7217',
    'rfc-4193',
    'rfc-3849',
  ],
  'wlan-standards': [
    'kmk-rahmenlehrplan',
    'fiausbv',
    'bibb-fachinformatiker',
    'ieee-80211-working-group',
    'ieee-sa-p802-11',
    'ieee-80211ax-2021',
    'ieee-80211be-2024',
    'wifi-alliance-security',
    'bsi-wlan-lan-grundlagen',
    'bsi-wlan-sicherheitstipps',
    'microsoft-windows-wifi',
  ],
  'datenrate-berechnung': [
    'kmk-rahmenlehrplan',
    'fiausbv',
    'bibb-fachinformatiker',
    'bipm-si-prefixes',
    'nist-binary-prefixes',
    'iec-80000-13',
    'rfc-9293',
    'rfc-9110',
    'ieee-80211-working-group',
    'bsi-wlan-lan-grundlagen',
  ],
  'datenvolumen-berechnung': [
    'kmk-rahmenlehrplan',
    'fiausbv',
    'bibb-fachinformatiker',
    'bipm-si-prefixes',
    'nist-binary-prefixes',
    'iec-80000-13',
    'nist-ir-8354-digital-investigation',
    'rfc-791',
    'rfc-9293',
    'rfc-9110',
    'iso-iec-10918-1-jpeg',
    'w3c-png-3',
    'itu-t-h264',
    'itu-t-g1010',
  ],
  'homeoffice-ergonomie': [
    'kmk-rahmenlehrplan',
    'fiausbv',
    'bibb-fachinformatiker',
    'arbstaettv',
    'arbschg',
    'dguv-215-410',
    'baua-mobile-arbeit-homeoffice',
    'w3c-wcag',
    'bitv-2-0',
  ],
  'pki-zertifikate': [
    'rfc-5280',
    'rfc-6960',
    'rfc-8446',
    'bsi-kryptografie',
    'bsi-tr-02102-1',
    'bibb-fachinformatiker',
  ],
  gewaehrleistung: [
    'bgb-433-kaufvertrag',
    'bgb-434-sachmangel',
    'bgb-437-maengelrechte',
    'bgb-438-verjaehrung-maengel',
    'bgb-443-garantie',
    'hgb-377-maengelruege',
  ],
}

export const lernfeldTags: Record<string, string[]> = {
  grundlagen: ['ordnung'],
  hardware: ['ordnung', 'sicherheit'],
  betriebssysteme: ['sicherheit'],
  netzwerke: ['netzwerk'],
  daten: ['datenbank'],
  software: ['software'],
  projekt: ['projekt'],
  sicherheit: ['sicherheit'],
  wirtschaft: ['wirtschaft'],
  vertragsrecht: ['recht', 'vertragsrecht'],
  qualitaet: ['projekt'],
  webmedia: ['web'],
  aktuell: ['ordnung'],
  arbeitsrecht: ['recht', 'ausbildung'],
}
